### ISSUE TITLE
File "tuf/client_setup_and_repository_example.md" is extermely outdated

### ISSUE THREAD

**Issue by Silvanoc** [theupdateframework/tuf#1000]
**Description of issue or feature request**:

The file [tuf/client_setup_and_repository_example.md](https://github.com/theupdateframework/tuf/blob/develop/tuf/client_setup_and_repository_example.md) is extermely outdated.

It refers to the file `basic_client.py`, but that file was moved from `tuf/client` to `tuf/scripts` on commit e17550873f76086ef1044ed62fe3c0e2004ad1c6 (2016).

It was later renamed to `tuf/scripts/client.py` on commit d7bb67b8c4f564e033714e417cdaebdd8c9f9924 (2018).

**Current behavior**:

File file [tuf/client_setup_and_repository_example.md](https://github.com/theupdateframework/tuf/blob/develop/tuf/client_setup_and_repository_example.md) is outdated.

**Expected behavior**:

File [tuf/client_setup_and_repository_example.md](https://github.com/theupdateframework/tuf/blob/develop/tuf/client_setup_and_repository_example.md) gets updated or removed.

**Comment by lukpueh** [comment]
Many thanks for submitting the issue, @Silvanoc! FYI, we have an extensive list of documentation issues in #808. But removing `tuf/client_setup_and_repository_example.md` seems like a sensible partial fix (see #1001).
