### ISSUE TITLE
Improve TUF onboarding for new users

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#1006]
**Description of issue or feature request**:

We need a much easier to understand, coding-first, reading-later introduction to TUF.

**Current behavior**:

Following up on our PEP 458 WG meeting today, people who are new to TUF find it too difficult to read [all of the academic papers and specification](https://python.zulipchat.com/#narrow/stream/223926-pep458-implementation/topic/onboarding) before ramping up with working code.

**Expected behavior**:

There are many options here. One is to have a friendly, interactive website that quickly introduces programmers w/o security backgrounds to the problem, and how to use python-tuf to solve most use cases w/o thinking too much about it.

Cc @joshuagl and his colleagues

**Comment by lukpueh** [comment]
**Highly related:**
- #808 tracks ongoing efforts and ideas for overhauling and consolidating the existing documentation
- #881 discusses the future of the repo and client cli tools, which some have said are useful for learning python-tuf. It also lists a few related issues 

Btw. I have doubts that this is a *"good first issue"*. The task requires deep knowledge about TUF and python-tuf. Do you mind if I remove the label?

**Comment by trishankatdatadog** [comment]
Nope, go for it!

**Comment by lukpueh** [comment]
#1797 seems like a duplicate but with more up-to-date references. Closing here...
