### ISSUE TITLE
Provide TARGETPATH normalizing convenience interface

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1019]
**Description of issue or feature request**:
#1008 removes ambiguity in interfaces that take [TARGETPATH](https://github.com/theupdateframework/specification/blame/69b8456614796b57c6076d3894568a83b3f7ce1a/tuf-spec.md#L808-L815) arguments, by only accepting paths and path patterns that use "/" as directory separator and don't start with "/", as recommended in the specification (see #1018 for even stricter vetting of these arguments).

To provide a friendly user interface we should add normalizing functionality that transforms paths as returned by `os.listdir`, `os.walk`, `repository_tool.Repository.get_filepaths_in_directory`, etc... into a format that is accepted by methods that take TARGETPATHs.

Normalizing includes
- strip targets directory prefix from absolute paths
- convert Windows-style dir separators "\" to Unix-style separators "/"
- maybe perform `os.path.normpath`-like normalization, like collapsing redundant separators and up-level references

#957 has some discussions about least-suprise in TARGETPATH, e.g. what do do if an absolute path does not have the targets directory as prefix, or a relative path is passed, etc...

I envision an interface that may be used like this:

```python
target_role.add_targets(normalize_target_paths(get_filepaths_in_directory(dir_path)))
```
or the with the latter two combined

```python
target_role.add_targets(get_normalized_paths_in_directory(dir_path)))

```

**Comment by jku** [comment]
I'm not closing this directly, maybe there is something here... However, current implementation does try to consider target paths as URL fragments, that may or may not map to a local path

**Comment by lukpueh** [comment]
The `add_target`-like interface of the new Metadata API requires callers to be explicit about the `target_file_path` as it appears in the targets metadata, and the  the local path, used to determine hashes and length of the target file to be added:

https://github.com/theupdateframework/python-tuf/blob/8ac7167f8d27f60955b8d984c65b5cdefa19d987/tuf/api/metadata.py#L1545-L1556

To keep the Metadata API minimal, I suggest to implement the requested convenience interface in a future repository tool. Since we don't have a roadmap for that yet, I'll close this issue and add a comment/reference in #1136.
