### ISSUE TITLE
Memory-inefficient updater may cause denial of service

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#104]
The way the updater currently works, it must read the entire metadata into memory in order to check its format, or read an entire target or metadata file into memory in order to check its hashes and so on. This is clearly inefficient with regard to memory, and could cause denial of service. We should read files as efficiently as possible.

**Comment by trishankatdatadog** [comment]
Not really a security issue: the worst that can happen is that the updater crashes, but no arbitrary software attacks should happen. Also, since then, we have default upper bound limits on metadata and targets file sizes.
