### ISSUE TITLE
Delegated roles metadata can be written to disk without signing

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1050]
**Description of issue or feature request**:
Delegated roles can be written to disk without any signature.

When a role is delegated but no signing keys are loaded to the role, one can still write the metadata on disk without any signature or any error being raised.
```
repository.targets.delegate('unclaimed', [public_unclaimed_key], ['myproject/*.txt'])
repository.mark_dirty(['snapshot', 'targets','timestamp', 'unclaimed'])
repository.writeall()
```

unclaimed.json: 
```
{
 "signatures": [],
 "signed": {
  "_type": "targets",
  "delegations": {
   "keys": {},
   "roles": []
  },
  "expires": "2020-09-08T21:27:27Z",
  "spec_version": "1.0.0",
  "targets": {},
  "version": 1
 }
}
```
**Current behavior**:

Delegated roles are allowed to be written without a signature.

**Expected behavior**:

Raise an error if there is no key loaded for a delegated role.

**Comment by sechkova** [comment]
Delegated roles are allowed to be partially signed and do not go through the same [verification steps](https://github.com/theupdateframework/tuf/blob/5d40ffa3c49f6ce8ba5908abacec5630833829e8/tuf/repository_lib.py#L179) as the top level roles but partially signed should not equal not signed at all.

**Comment by joshuagl** [comment]
`repository_lib.sign_metadata()` takes a list of *keyid*'s for the signing keys and loops over the list, trying to sign the metadata with each associated key.

Only nowhere do we __ensure__ that there are a non-zero number of _keyid_'s passed to `sign_metadata()`. Therefore, if the list is empty (as in the case demonstrated here) the for loop exits and the function returns indicating everything is OK.

Note: `repository_lib.sign_metadata()` attempts to ensure that the generated signable object is legitimate before returning by calling `tuf.formats.check_signable_object_format()`, but that function does not check that the signatures field is non-empty.

We should:
* Ensure that keyids has one or more items (this might just be a check in `sign_metadata()`, or maybe it would make more sense for `securesystemslib.formats.KEYIDS_SCHEMA` to set the *min_count* of `securesystemslib.schema.ListOf`?
* Consider adding verification to `sign_metadata()` to ensure that at least one signature has been added to the returned signable object

**Comment by sechkova** [comment]
I would prefer modifying `KEYIDS_SCHEMA` or `SIGNATURES_SCHEMA` with a _min_count_ of 1 but currently the code base heavily relies on using them as empty ones.
As a second best option I added an additional check in `tuf.formats.check_signable_object_format()` and opened #1100.
