### ISSUE TITLE
Document public API

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1053]
**Description of issue or feature request**:
The public API (if any) of the reference implementation should be clearly documented.

**Current behavior**:
The actual source files seem to be documented (see e.g. tuf/client/updater.py) but since the documentation is seemingly not published anywhere it's not really clear to an outsider what is actually supported as external API (nothing? just tuf.client.updater? more?)

**Expected behavior**:
The API reference is published and then linked to from e.g. https://pypi.org/project/tuf/

**Comment by jku** [comment]
I guess depending on the answer to "what is actually supported as external API" there might be a followup issue: should tuf.client.updater be packaged into it's own wheel, with just the dependencies it needs?

**Comment by lukpueh** [comment]
Thanks for submitting this request, @jku! I aggree with you  100%. Currently, the best way to check what parts of TUF are "public API" is to look at the functions used in the [Tutorial](https://github.com/theupdateframework/tuf/blob/develop/docs/TUTORIAL.md). 

The good news is that we are planning a larger refactor, part of which will be to clearly define and document the supported API, similarly to what we just did for TUF's sister project in-toto (see https://github.com/in-toto/in-toto/pull/369). There are also discussions about making TUF more modular (see e.g. #881).

**Comment by jku** [comment]
Well what do you know: https://theupdateframework.readthedocs.io/en/latest/

**Comment by jku** [comment]
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.
