### ISSUE TITLE
Detect metadata and data mismatch on server when possible

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#106]
Justin thinks that we should try to detect metadata and data mismatch on the server when possible.

For example, a target file could be longer than what the targets metadata signed for. This may happen when the targets metadata is out-of-sync with the target files. In this case, what the updater can do is to try to download an extra byte and see whether it succeeds. If it does, then the updater may throw a tuf.TargetFileBiggerThanExpectedError. Otherwise, all is good.

**Comment by lukpueh** [comment]
@trishankatdatadog, is this the same issue as #55?

**Comment by trishankatdatadog** [comment]
Not the same, but related. I think it's safe to close this issue. Metadata running out of sync with targets is not strictly a TUF problem.
