### ISSUE TITLE
Resource warnings when running the test files

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1123]
**Description of issue or feature request**:
When you run `python <test_file>` on the development branch we are getting resource warnings.

**Current behavior**:
For example, if you run `python test_download.py` from the `tests` directory you will get:
![image](https://user-images.githubusercontent.com/16246778/92642190-83746800-f2e8-11ea-8ac3-a7082b3f43a5.png)

**Expected behavior**:
No unclosed files, sockets, or resources as a whole to be left after a test run and thus no resource warnings to be found.

**Comment by jku** [comment]
This _might_ be same as #1099 (but I'm not sure)

**Comment by MVrachev** [comment]
Maybe, but this problem exists not only in the `test_updater.py`, but most likely in almost all of our test files...
