### ISSUE TITLE
Design repository library

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1136]
*[Update 2/14/22]* 

- [ADR 10](https://github.com/theupdateframework/python-tuf/blob/develop/docs/adr/0010-repository-library-design.md) shows the updated direction of this issue including further reading (design document, prototype implementation)
- Comments in thread here below point to survey documents for existing repository tooling, based on which ADR 10 was developed

---

*[Original issue description]*

Identify what functionality from existing repository_tool/repository_lib/roledb/keydb modules should exist in a TUF repository library on top of a metadata model as sketched in #1112.

Start with API functionality.

Coordinate with #1134.

**Comment by joshuagl** [comment]
I think a good place to start with this would be looking at what scaffolding Warehouse ends up building on top of the metadata API.

https://github.com/pypa/warehouse/pull/7488
https://github.com/pypa/warehouse/pull/8955

**Comment by joshuagl** [comment]
See also a WIP addition to the specification describes the repository workflow for adding/updating targets which this library should implement: https://github.com/theupdateframework/specification/pull/153

**Comment by joshuagl** [comment]
> See also a WIP addition to the specification describes the repository workflow for adding/updating targets which this library should implement: https://github.com/theupdateframework/specification/pull/153

This has landed and can be referenced here https://theupdateframework.github.io/specification/latest/#adding-updating-targets

**Comment by jku** [comment]
Linking to https://github.com/theupdateframework/python-tuf/issues/1459#issuecomment-953729281. If this issue is top-down design that one is definitely bottom-up: I'm creating initial repositories in a few places and the code always looks quite ugly but the last comment maybe has a decent idea that would work without lots of new API.

**Comment by lukpueh** [comment]
Adding the list of surveys of existing TUF repository implementations here so that we can close #1612...

- [python-tuf](https://docs.google.com/document/d/1zk41LSC_wsEEOq9TQSPR4h_0w2dnz0f9Zx_FjESm1qQ)
- [repository-editor-for-tuf](https://docs.google.com/document/d/1IIvr6_54NC02mcfpkzKYA_Zwt-06jW4fkjHVhVrYZf8/edit#heading=h.yjb9nkwgv5op)
- [go-tuf and php-tuf](https://docs.google.com/document/d/1vqB-KDG8GGBQUkwX8VHlS4FOmKjgDYGfzMDfcGLtQXE/edit)
- [AWS Tough](https://docs.google.com/document/d/1zFl4em6PZUrgnjiy4VnpOh918x_BCPozoc8d4KuVcYo/edit)
- [Warehouse](https://docs.google.com/document/d/16kM9SruqTcHXrTHeQDf-F6-qz3xwBzRJIVTqdudCEu0)

**Comment by lukpueh** [comment]
Adding more relevant documents ...
- [TUF (Re-)Design Document / Section: Repo tool](https://docs.google.com/document/d/13cY0MD3uzwFYGnj_GkPS_rwvDEzzNpDu6cteyeYP6fY/edit#bookmark=id.3mmgo7cr7nqt) -- *high-level directions, potential functionality*
- [Repo Usage Scenarios](https://docs.google.com/document/d/1qBNR-_HuS312H9YjFdIbll8MW8Abe9ORYzx43z-bpEk) -- *details required inputs, e.g. knowledge about role metadata, for each scenario*
- [Repo Tool Design](https://docs.google.com/document/d/1hNWDPe2iMDcI0wat9BkYTu1lWgIiK7IqfLDnM1CUgmU/edit#heading=h.srkj4dge82lo) -- *basic high-level design with many open questions*
- [Strawman repo design proposal](https://docs.google.com/document/d/1ZsXWMP_JgsI6RLhyiDn1Fr6rSCMFVoYSBwBakMzspjs/edit#) -- *bottom-up design, based on [vmware-labs/repository-editor-for-tuf](https://github.com/vmware-labs/repository-editor-for-tuf), seems very promising...*

Next steps:
- Revise open questions  and generalize problems
- Revise strawman design for suitability to answer these questions
- Revise strawman design / prototype implementation for remaining open questions
- Write design document

**Comment by lukpueh** [comment]
> Next steps:
> 
> * Revise open questions  and generalize problems
> * Revise strawman design for suitability to answer these questions
> * Revise strawman design / prototype implementation for remaining open questions
> * Write design document

See updated issue description above for latest results...

**Comment by lukpueh** [comment]
*Feature request:*
Convenience interface that takes a path to local target file(s) and constructs targets metadata, computing length and hashes from the local file and normalizing the path to match the TARGETPATH specification (see #1019 and #1018 for details and challenges)

**Comment by prateek041** [comment]
I would like to work on this issue, where should I start ?

**Comment by lukpueh** [comment]
> I would like to work on this issue, where should I start ?

Reading the resources referenced above in the issue description and brainstorming designs seems like the way to start. 

But as @jku has mentioned on [slack](https://cloud-native.slack.com/archives/C01GT17AC5D/p1649402131676979?thread_ts=1649399315.799889&cid=C01GT17AC5D), this *is likely a long term issue that is going to require experimentation and quite a bit of team work to solve*.

**Comment by joshuagl** [comment]
Another implementation we could look to for inspiration is [Rugged](https://rugged.works), which implements [repository](https://gitlab.com/rugged/rugged/-/blob/main/rugged/tuf/repo.py) and a [key manager](https://gitlab.com/rugged/rugged/-/blob/main/rugged/tuf/key_manager.py) classes on top of the low-level metadata API.

A key manager/keyring feels like a useful helper to provide.

**Comment by jku** [comment]
I've decided to just do a PR of this:
* a tiny repository abstraction
* example implementation of that abstraction (a in-memory ephemeral repository a bit like the one in tests)
* demo repository application using that in-memory implementation that simulates a live  repository by generating changes every few seconds

I have that 90% ready, will push the PR this week. Future steps would include:
* example developer tool (built using the same building blocks as the repository) that is able to sign changes and submit them to the demo repository application. I have a rough idea, should not be too much work

I have no assumptions that the API would be final in this PR: as minimal as it is, new use cases seem to always bring new complications... So I suggest we 
* try to merge something soon
* keep the repository abstraction as unstable API for now
* build more implementations to gather data (potential ones at least RSTUF, repository-editor-for-tuf, repository-playground)
* improve as new ideas come up
