### ISSUE TITLE
Add input validation to simple metadata api

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1140]
Coordinate with validation guidelines https://github.com/theupdateframework/tuf/issues/1130

**Description of issue or feature request**:
Some suggestions:
   - Avoid schema, see secure-systems-lab/securesystemslib#183 (just don't use it)
   - Make use of type hints for simple type validation
   - Perform additional non-metadata parameter validation at user boundary
   - Provide methods to validate JSON representation at user boundary, i.e. fail on bad json metadata in `from_json_file`/`to_json_file` method, but with option to
     disable check as there might be a justified reason to read or write WIP
     metadata to json.
   - Be lenient on bad/invalid metadata objects in memory, they might be
     work in progress. E.g. it might be convenient to create empty metadata
     and assign attributes later on.
   - Consider using in-toto style `ValidationMixin` (see the [`mixin`](https://github.com/in-toto/in-toto/blob/74da7a/in_toto/models/common.py#L27-L40) and it's [usage](https://github.com/in-toto/in-toto/blob/74da7a/in_toto/models/layout.py#L420-L438) for details).

**Current behavior**:
No input validation

**Expected behavior**:
Add input validation

**Comment by joshuagl** [comment]
> * Consider using in-toto style `ValidationMixin` (see the [`mixin`](https://github.com/in-toto/in-toto/blob/74da7a/in_toto/models/common.py#L27-L40) and it's [usage](https://github.com/in-toto/in-toto/blob/74da7a/in_toto/models/layout.py#L420-L438) for details).

This looks like a nice pattern. Each class defines appropriate validation methods, which are called by the Mixin's `validate()` method at the end of the object's construction. Any thoughts on whether a decorator might be a more idiomatic approach than a Mixin? We can

This article suggests how to to type validation with type hints https://aboutsimon.com/blog/2018/04/04/Python3-Type-Checking-And-Data-Validation-With-Type-Hints.html

**Comment by joshuagl** [comment]
> * Consider using in-toto style `ValidationMixin` (see the [`mixin`](https://github.com/in-toto/in-toto/blob/74da7a/in_toto/models/common.py#L27-L40) and it's [usage](https://github.com/in-toto/in-toto/blob/74da7a/in_toto/models/layout.py#L420-L438) for details).

This looks like a nice pattern. Each class defines appropriate validation methods, which are called by the Mixin's `validate()` method at the end of the object's construction. 

Any thoughts on whether a decorator might be a more idiomatic approach than a Mixin? We could wrap classes with a decorator which performs validation after init, before returning the instantiated object.

* https://aboutsimon.com/blog/2018/04/04/Python3-Type-Checking-And-Data-Validation-With-Type-Hints.html
* https://realpython.com/primer-on-python-decorators

**Comment by trishankatdatadog** [comment]
Another idea is to copy validation techniques Django/Rails use...

**Comment by joshuagl** [comment]
Nice idea. I took a brief look those look to be quite complicated and not equivalent to what we're trying to do here [Django Model validation](https://docs.djangoproject.com/en/3.1/ref/models/instances/#validating-objects).

**Comment by lukpueh** [comment]
Good thinking, @trishankatdatadog. But I agree with @joshuagl that we might not need something as powerful (Django's validation is really tailored towards web forms and/or ORM, similar is true for `WTForms`, which I also briefly considered).

I think the in-toto approach is not so bad. It's also featured in this quite interesting [blog post about different instance attribute validation techniques](https://towardsdatascience.com/6-approaches-to-validate-class-attributes-in-python-b51cffb8c4ea), at least the "individual validation functions" aspect (not the neat self-inspecting mixin part).

The blog also mentions two promising validation libraries, [`marshmallow`](https://marshmallow.readthedocs.io/en/stable/index.html) and [`pydantic`](https://pydantic-docs.helpmanual.io/),  which both are actually de/serialization libraries with validation features.  Given that we want to minimize dependencies (see #1165), I'm leaning towards rolling our own validation, which doesn't even have to be that generic (see secure-systems-lab/securesystemslib#183).

The blog also mentions a Python built-in feature, i.e. `Descriptors`, that [as per official docs seems well-suited for attribute validators](https://docs.python.org/3/howto/descriptor.html#custom-validators). Although it looks interesting, I'm unsure if it gives us the flexibility of e.g. initializing empty objects, assigning values, and only then calling validate, which might be a desirable usage pattern (see snippet 2 in https://github.com/theupdateframework/tuf/pull/1223#issuecomment-737188686). Same reservation goes for decorators, which the blog also mentions in conjunction with descriptors. But I can check if there is a solution that involves decorators and/or descriptors that allows for said flexibility.

What I like about both the decorator and descriptor approach(es) is that they make the constraints on the attributes more visible (in the head of the class definition) than vanilla validation methods.

**Comment by joshuagl** [comment]
> The blog also mentions a Python built-in feature, i.e. `Descriptors`, that [as per official docs seems well-suited for attribute validators](https://docs.python.org/3/howto/descriptor.html#custom-validators). Although it looks interesting, I'm unsure if it gives us the flexibility of e.g. initializing empty objects, assigning values, and only then calling validate, which might be a desirable usage pattern (see snippet 2 in [#1223 (comment)](https://github.com/theupdateframework/tuf/pull/1223#issuecomment-737188686)).

Descriptors look nice, and I'm all for avoid additional dependencies. I believe the pattern of: initialising empty objects, assigning values, and then validating should still work – so long as our empty objects have sane defaults. Based on 5mins experimentation in the Python interpreter:

```
>>> class MetadataType:
...     def __get__(self, obj, objtype=None):
...         return self.value
...     def __set__(self, obj, value):
...         if value not in ['root', 'timestamp', 'snapshot', 'targets']:
...             raise ValueError('Invalid _type field')
...         self.value = value
...
>>> class Metadata:
...     type = MetadataType()
...     def __init__(self, type):
...         self.type = type
...
>>> class Targets(Metadata):
...     def __init__(self):
...       super().__init__('targets')
...
>>> md = Metadata('badger')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in __init__
  File "<stdin>", line 6, in __set__
ValueError: Invalid _type field
>>> md = Metadata('root')
>>> md.type = 'badger'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in __set__
ValueError: Invalid _type field
>>> t = Targets()
>>> t.type
'targets'
```

**Comment by joshuagl** [comment]
The [`__slots__` mechanism](https://docs.python.org/3/howto/descriptor.html#member-objects-and-slots), described in the Descriptor HowTo, could be something worth including in our new classes also. hat-tip @sechkova

**Comment by lukpueh** [comment]
I wonder if sane defaults will always be possible, e.g. when thinking of the newly added `MetadataInfo` or `TargetInfo` in https://github.com/theupdateframework/tuf/pull/1223.

But maybe the usage pattern that requires initialization of empty objects is suboptimal. I must say that it would be quite nice to always have certainty about the validity of tuf objects.

**Comment by joshuagl** [comment]
In https://github.com/theupdateframework/tuf/pull/1223/commits/7cfd100eeb37a7878741722a1b766b5313022287#r541018751 we discussed whether `JsonDict` is the right name for our generic `Dict[str, Any]` type, and agreed to handle that type's name with this issue instead.

**Comment by MVrachev** [comment]
In a discussion with @jku, we noticed that our tests for the metadata classes don't test instantiating metadata objects without their required fields.
We should add tests for that.

**Comment by MVrachev** [comment]
I think we can lose this issue as we discussed that each of the cases has to be discussed separately.
We don't need a common strategy to do this.

We had discussions validation for all cases separately:

- Signed attributes: #1418, #1430, #1420
- Key attributes: #1438
- Role attributes: https://github.com/theupdateframework/python-tuf/pull/1360/commits/0c3131b4a2b2f9abb6c35d271e38db7ffa7ea18b, #1439 
- Root: #1630 
- MetaFile: #1451
- DelegatedRole: https://github.com/theupdateframework/python-tuf/commit/76d46336007ef9a6974b5ef3e6bac7e3a62924f6, https://github.com/theupdateframework/python-tuf/commit/aa480b1280f38741155b8d065952db86115b9750, #1558, #1527 (still open)
- TargetFile: #1451 
- Targets: we didn't find need to validate it
- Additional: #1356,

**Comment by MVrachev** [comment]
@lukpueh and/or @joshuagl do you agree with me?

**Comment by joshuagl** [comment]
Agreed, thanks Martin. Closing because we have implemented validation on a case-by-case basis.
