### ISSUE TITLE
Keep track of procedural and architectural decision

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1141]
In the course of the imminent TUF refactor we are submitting many [discussion issues](https://github.com/theupdateframework/tuf/projects/2?card_filter_query=label%3Adiscussion) under an additional [*decision record* label](https://github.com/theupdateframework/tuf/projects/2?card_filter_query=label%3A%22decision+record%22). These discussions are intended to inform both procedural and architectural decision that are worthy of being tracked.

For this purpose we should keep a (low-maintenance) list where we can append decisions as we make them, together with pointers to background discussions and rationale, e.g. in the corresponding issue pages.

@joshuagl suggests (and I agree) to keep the lists in markdown documents as part of the TUF repo, which seem less likely to get abondoned/lost than e.g. external wiki pages or Google docs, and also make collaboration easier.

**Comment by aaaaalbert** [comment]
Try [Markdown Architectural Decision Records](https://adr.github.io/madr/), looks like this could suit your needs.

**Comment by joshuagl** [comment]
Thanks for the suggestion @aaaaalbert, MADR does look like a good fit for us. It has enough structure to encourage us to capture the relevant details while remaining relatively lightweight.
