### ISSUE TITLE
repository_lib.py lists signatures in an non-deterministic order

### ISSUE THREAD

**Issue by erickt** [theupdateframework/tuf#1154]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:

When some metadata is signed with multiple keys, `tuf/repository_lib.py` doesn't write the signatures in a deterministic order. This occurs because of this [line](https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L121). If this line was changed to `signing_keyids = sorted(set(roleinfo['signing_keyids']))`. I hacked this in and it worked, but I wasn't sure how to write a test for it, and ran out of time.

 doesn't sign the metadata in a consistent order, and so it's not guaranteed to generate the same file if metadata is resigned with the same keys. This came up in the [go-tuf interoperability test suite](https://github.com/theupdateframework/go-tuf/pull/122), where each time I regenerated the metadata I might get different file hashes.

**Current behavior**:

It's not guaranteed what order signatures are written in.

**Expected behavior**:

Signatures to be sorted in some order. My proposal is we just do alphabetical order.

**Comment by trishankatdatadog** [comment]
Yes, we might as well do this, but are we also fixing entropy during the tests? Because signatures themselves are not necessarily deterministic...
