### ISSUE TITLE
Modernise and rationalise packaging

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1161]
**Description of issue or feature request**:

Python packaging has changed significantly since the tuf packaging was created. There's been a move to declarative files, the formalisation of build system independent source tree layout in [PEP 517](https://www.python.org/dev/peps/pep-0517/), and the addition of new metadata to specify the build system dependencies in [PEP 518](https://www.python.org/dev/peps/pep-0518/).

Furthermore our current packaging is somewhat ad-hoc, with some expected files like LICENSE missing from the sdist (see #1160) and some unexpected files like tuf/ATTACKS.md included.

For reference see:
https://packaging.python.org/
https://snarky.ca/what-the-heck-is-pyproject-toml/

**Current behavior**:

Packaging isn't up-to-date with PyPA recommendations and our sdist includes files which don't match conventions.

**Expected behavior**:

Packaging is in line with current PyPA best practices and generated distributions match ecosystem conventions.

**Comment by joshuagl** [comment]
We should add some CI steps to ensure our packaging metadata is sane, for example our current `MANIFEST.in` fails a [check-manifest](https://github.com/mgedmin/check-manifest) test with:

> lists of files in version control and sdist do not match!

**Comment by jku** [comment]
A gotcha that we may care about with regards to setup.py/setup.cfg/pyproject.toml: I just tried to do `pip install -e <directory>` to a project that only has a pyproject.toml and:
```
pip install -e ../vendoring
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/jku/src/vendoring
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```
Which would mean current requirements-dev.txt in tuf would fail to install in this case.

**Comment by sechkova** [comment]
> A gotcha that we may care about with regards to setup.py/setup.cfg/pyproject.toml: I just tried to do `pip install -e <directory>` to a project that only has a pyproject.toml and:
> 
> ```
> pip install -e ../vendoring
> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/jku/src/vendoring
> (A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
> ```
> 
> Which would mean current requirements-dev.txt in tuf would fail to install in this case.

Yep, it is a known limitation, it can be circumvented by:

```
import setuptools

if __name__ == "__main__":
    setuptools.setup()
```

but needs to be kept in mind ([link](https://snarky.ca/what-the-heck-is-pyproject-toml/)).

**Comment by sechkova** [comment]
I am sharing, after of a brief research on the topic, a list of the current issues with suggestions on how to move forward. 
_Please (dis)agree, add missing information, correct me if I am wrong._


 **1. Lagging behind from the latest PyPA recommendations and PEPs ([517](https://www.python.org/dev/peps/pep-0517/), [518](https://www.python.org/dev/peps/pep-0518/))**

The obvious proposal here is to just follow the [PyPA guideline](https://packaging.python.org/tutorials/packaging-projects/#creating-pyproject-toml) which recommends:
- adopting a `pyproject.toml` (PEP 518) which describes the project's build dependencies
- keeping `setuptools` as the packaging tool given this is already in use and nothing strongly enforces its replacement
- switching to a static `setuptools` config, `setup.cfg`
- using [build](https://pypa-build.readthedocs.io/en/latest/)

\* keep in mind the two [comments](https://github.com/theupdateframework/tuf/issues/1161#issuecomment-763463201) above related to an issue when installing in editable mode.

This should make the project PEP 517, PEP 518 compliant which also gives the opportunity to easily migrate to another packaging tool if such need arrives in the future. Just listing some popular names here:  [flit](https://github.com/takluyver/flit), [poetry](https://python-poetry.org), [bento](https://cournape.github.io/Bento/)

 **2. File gathering: MANIFEST.in is too fine grained, misses needed files while adding irrelevant ones**
 - Use [setuptools_scm](https://github.com/pypa/setuptools_scm) extension and list only files that need to be excluded in `MANIDEST.in` 
 - If still relevant, add tools like `check-manifest` to the GitHub Actions
 
 **3. Semi-manual `requirements*.txt ` generation for different Python versions**
 - Hopefully this will be resolved, at least the manual part should be greatly reduced, by dropping Python 2.7. support
 - Nothing seems to be changed on the topic of "why pin dependencies" so I won't raise it here but I am adding some links for a historical background: https://github.com/theupdateframework/tuf/commit/730e4d8b97c5d8f24eaffb3b637fe4d64f50ec32, https://github.com/in-toto/in-toto/pull/294

Adding some blogposts to Joshua's list of references:
https://snarky.ca/clarifying-pep-518/
https://snarky.ca/what-the-heck-is-pyproject-toml/
https://blog.ionelmc.ro/presentations/packaging/
https://caremad.io/posts/2013/07/setup-vs-requirement/

**Comment by joshuagl** [comment]
Thank you for doing the research Teodora! 
1. seems very reasonable. `build` gives us build isolation, which in my opinion warrants the switch. What else do we gain by switching to build? Is it just a simpler/more consistent interface for building than invoking setup.py?
2. seems reasonable also
3. Python 2.7 is gone 🎉 

It would be great to handle the things you listed in 1. and the setuptools_scm change suggested in 2 to address this issue.
The items in 3 can reasonably handled separately as a fix for https://github.com/theupdateframework/tuf/issues/1249.

**Comment by lukpueh** [comment]
Thanks for the great summary, @sechkova! I second @joshuagl's comment, plus:

> 1.  ... gives the opportunity to easily migrate to another packaging tool if such need arrives in the future. Just listing some popular names ...

Any recommendations on tools?

> 3. ... Nothing seems to be changed on the topic of "why pin dependencies"...

Did you see how other projects do this? in-toto/in-toto#294  -- i.e. un-pinned direct deps for user installs vs. pinned + auto-updated direct and transitive deps for CI/CD -- felt like a good but very custom solution. I'd be curious if there are better or more common practices. Also in regards to pinning direct and transitive deps for different Python versions. Although the latter might really just not be relevant without Python 2.7. IIRC TUF has no dependency case-handling for different Python 3 versions.

**Comment by sechkova** [comment]
> Any recommendations on tools?

I am wary of recommending tools that I haven't used, especially with no experience in the packaging world. However, @joshuagl may be interested in `flit` which has some support for [reproducible builds ](https://flit.readthedocs.io/en/latest/reproducible.html). 
I will share if I come across something promising.

On the second part of the problem, dependencies resolution, I couldn't find any different practices (than what we do) besides suggestions to totally switch to `Poetry` (+ `Pipenv`). I suggest we revise such necessity after removing py2-related dependencies.

**Comment by sechkova** [comment]
> 1. seems very reasonable. `build` gives us build isolation, which in my opinion warrants the switch. What else do we gain by switching to build? Is it just a simpler/more consistent interface for building than invoking setup.py?

My understanding at this point is that `build` simply "invokes the correct PEP 517 hooks to build a distribution package".  Maybe the end result will be the same as with `setup.py` since we use `setuptools` anyway or maybe some config may misbehave ... I can only speculate before trying it.

**Comment by joshuagl** [comment]
> > Any recommendations on tools?
> 
> I am wary of recommending tools that I haven't used, especially with no experience in the packaging world. However, @joshuagl may be interested in `flit` which has some support for [reproducible builds ](https://flit.readthedocs.io/en/latest/reproducible.html).

Ah, interesting. flit might be a good stop-gap for achieving #1269. I'll mention it in that issue, thanks @sechkova !

**Comment by joshuagl** [comment]
PyPA are [recommending `build`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#packaging-your-project) now, we should switch to that (ensuring that docs/RELEASE.md is updated too).

**Comment by joshuagl** [comment]
Not only are PyPA recommending build, but direct invocations of setup.py are considered deprecated for a number of years!? 😱

https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
