### ISSUE TITLE
Revise pylint configuration (and linter choice)

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1178]
**Description of issue or feature request**:
TUF uses a `pylint` config file that seems to have been copied in verbatim from [PyCQA/pylint](https://github.com/PyCQA/pylint/blob/master/pylintrc), listing all defaults explicitly, and adding only a few customizations, which neither fully encode our [current style guidelines](https://github.com/secure-systems-lab/code-style-guidelines/blob/532c8347402822b0b0a70d4cf93e6690795ebf13/README.md), nor the [style guidelines we plan to adopt (~TBD)](https://github.com/secure-systems-lab/code-style-guidelines/issues/20) for new code.

Note: The same issue [exists in `securesystemslib`](https://github.com/secure-systems-lab/securesystemslib/issues/243), and existed but was [fixed in `in-toto`](https://github.com/in-toto/in-toto/pull/296).

**Current behavior**:
- `pylintrc` unnecessarily lists defaults making it hard to read/maintain 
- `pylintrc` does not encode our code style guidelines
- (travis/tox automated testing does not run `pylint` over test code)

**Expected behavior**:

1. Decide on style guidelines (https://github.com/theupdateframework/tuf/issues/1128)
2. Encode chosen guidelines in a new `pylintrc`-file  (see https://github.com/theupdateframework/tuf/pull/1177 for WIP preparatory work)
3. Use new `pylintrc` for new code  including tests
   Note: It is probably not worth fixing the potentially many linter issues in code that might not survive the [upcoming refactor](https://github.com/theupdateframework/tuf/projects/2).
4. (orthogonal) review and adopt other [code quality](https://realpython.com/python-code-quality/) tools (e.g. @trishankatdatadog has positively mentioned `black` and `lgtm`).

**Comment by joshuagl** [comment]
#1294 suggests our current Tox configuration is not correctly linting the new code (in tuf/api/), even though we have a Pylint statement in Tox and a minimal configuration file for the new style.

**Comment by rzr** [comment]
tox is linting the code but I noticed that different pylint versions produce different warnings with current rc file.
Maybe some params can be added to prevent this kind of ambiguity.

I'll comment https://github.com/theupdateframework/tuf/pull/1294

now back to this ticket, It made sense to align to default configuration, now if there is a need to enforce custom ones , may I suggest that we progressively pick and adapt relevant lines from generated template:
    pylint --generate-rcfile > tuf/api/pylintrc

**Comment by lukpueh** [comment]
Thanks for chiming in, @rzr!

> may I suggest that we progressively pick and adapt relevant lines from generated template:
pylint --generate-rcfile > tuf/api/pylintrc

Yes, that's a great idea! Same should go for adopting the rules in the code. See e.g. https://github.com/in-toto/in-toto/pull/296/commits, where I grouped changes by rule and commit, which IMO makes review a lot easier.

Regarding  https://github.com/theupdateframework/tuf/pull/1294#issuecomment-789728670 ...
> Any objection to use black for formatting ?:

No, not at all! :) I have planned to work on this in the near future, but I'd definitely appreciate help. 

(cc @fepitre + https://github.com/in-toto/apt-transport-in-toto/pull/36#issuecomment-792913995)


Please note that both revised linter and auto-formatter config should align with our new [python style guide](https://github.com/secure-systems-lab/code-style-guidelines/blob/master/python.md).

**Comment by lukpueh** [comment]
Fixed in #1314 and follow up PRs, we now use a minimally configured `pytlint`, `black` and `isort` for the whole repo (including tests).
