### ISSUE TITLE
Review integration tests

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#118]
Thanks for the hard work of our graduate assistants, we have been able to advance our integration tests to a very respectable place. Suffice it to say that I can sleep much more safely and soundly now.

However, there is still some work left to polish those tests. For example, the integration tests need to be more complete:
- Mix-and match attacks:
  - Needs testing of all the possibilities from the "metadata inconsistency" column of [Table 5 in CCS'10 paper](https://isis.poly.edu/~jcappos/papers/samuel_tuf_ccs_2010.pdf).
- Replay attacks:
  - Needs testing of replayed data (without replayed metadata).
- Extraneous dependencies attacks:
  - Needs testing of attacker tampering with signed targets metadata, and without access to the offline targets key (will raise BadSignatureError).

**Comment by trishankatdatadog** [comment]
Tests exist now
