### ISSUE TITLE
develop branch fails 'with-sslib-master' build

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1184]
`tox -e with-sslib-master` fails after eb00d1434: 

> ERROR: Double requirement given: securesystemslib[crypto,pynacl]==0.16.0 (from -r /home/jku/src/tuf/requirements-pinned.txt (line 12)) (already in securesystemslib[crypto,pynacl] from git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib[crypto,pynacl], name='securesystemslib')

I have no idea how that colorama removal could do this but it seems to be the reason.

The tox config is
```
    --editable git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib[crypto,pynacl]
    -r{toxinidir}/requirements-test.txt
    --editable {toxinidir}
```
and requirements-test.txt does include "-r requirements-pinned.txt" which includes "securesystemslib[crypto,pynacl]==0.16.0"

Note that reproducing the issue might sometimes fail if you've installed specific things in tox envs already: wipe ".tox/" to make sure that does not happen.

**Comment by jku** [comment]
I think this should have failed all along but pip has a bug and did not notice that we have a double requirement (because the specifiers did not match before: [crypto,pynacl]  vs [crypto,pynacl,colors]). Now the specifiers are identical so pip realizes the situation and errors out.

It would be good to solve this without adding another requirements file... This is a bit of a hack but Works On My Machine:
```
[testenv:with-sslib-master]
deps =
    -r{toxinidir}/requirements-test.txt
    --editable {toxinidir}

commands_pre =
    pip install --editable "git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib[crypto,pynacl]"

commands =
    coverage run aggregate_tests.py
    coverage report -m
```
It first installs the pinned sslib version but then in commands_pre replaces it with the git version

**Comment by jku** [comment]
Alternative:
```
[testenv:with-sslib-master]
deps =
    --editable git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib
    -r{toxinidir}/requirements-test.txt
    --editable {toxinidir}

commands =
    coverage run aggregate_tests.py
    coverage report -m
```
here we abuse the same pip bug that we previously did: the lack of specifiers means there's no error -- the sslib dependencies should still get installed because of requirements-pinned.txt

I think  I like this one

**Comment by lukpueh** [comment]
I also like the second one better. As a matter of fact, I don't understand how the first one even works. Shouldn't pip noop on the second securesystemslib install in `command_pre` because it has already been installed  in `deps`?
