### ISSUE TITLE
Tests failure when using generate_and_write_ed25519_keypair() on develop branch

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1204]
**Description of issue or feature request**:
When running the tests on the latest commit on the `develop` branch 201e07ddca02c599e9dd221833730b444d96d685
I receive this error: 

```
======================================================================
ERROR: test_import_ed25519_privatekey_from_file (test_repository_lib.TestRepositoryToolFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mvrachev/src/tuf/tests/test_repository_lib.py", line 146, in test_import_ed25519_privatekey_from_file
    ed25519_keypath, password='pw')
TypeError: generate_and_write_ed25519_keypair() got multiple values for argument 'password'

======================================================================
ERROR: test_tutorial (test_tutorial.TestTutorial)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mvrachev/src/tuf/tests/test_tutorial.py", line 78, in test_tutorial
    generate_and_write_rsa_keypair('root_key', bits=2048, password='password')
TypeError: generate_and_write_rsa_keypair() got multiple values for argument 'password'

----------------------------------------------------------------------
```

Interestingly those tests fail on python 3.6+, but not on Python 2.7.
I don't have python 3.5 locally.

**Current behavior**:
Two unit tests are failing.

**Expected behavior**:
No unit tests failures on the `develop` branch.

**Comment by MVrachev** [comment]
The AppVeyor run on my latest pr looks likes it shows the same issue:
https://ci.appveyor.com/project/theupdateframework/tuf/builds/36234615

**Comment by jku** [comment]
appveyor build uses `pip install -e .` which installs newest securesystemslib (currently 0.18 which changed API) instead of the pinned version

**Comment by MVrachev** [comment]
Well, I have the same issue locally and I have the latest version of `securesystemlib`
I even recreated my venv just to try if that was the reason
Here is what I get with `pip list` in my latest venv:
![image](https://user-images.githubusercontent.com/16246778/98791235-69045b00-240d-11eb-8aa3-d59f0ea911e1.png)

Here are the results when testing `test_repository_lib.py` and `test_tutorial`:
![image](https://user-images.githubusercontent.com/16246778/98791147-4a9e5f80-240d-11eb-8a16-3476d403e715.png)
![image](https://user-images.githubusercontent.com/16246778/98791129-45411500-240d-11eb-8729-a14f6d8dcda7.png)

**Comment by lukpueh** [comment]
0.18.0 had some breaking changes. I'm in the process of adopting them in: https://github.com/theupdateframework/tuf/pull/1191

**Comment by jku** [comment]
> Well, I have the same issue locally and I have the latest version of `securesystemlib`
> I even recreated my venv just to try if that was the reason

Sure, that's what I'm saying: pinned requirements work (as shown by travis), newest securesystemslib does not.

> 0.18.0 had some breaking changes. I'm in the process of adopting them in: #1191

The issue still seems valid: the appveyor build result is unexpected -- especially compared to travis that is explicitly setup to be green in this situation.

Maybe it's not worth spending time on if we're moving CI to github though.

**Comment by lukpueh** [comment]
> Maybe it's not worth spending time on if we're moving CI to github though.

I agree. I think the AppVeyor config has been somewhat neglected compared to Travis Ci. Which is one more argument for unifying CI/CD for all platforms (#1195).

**Comment by lukpueh** [comment]
> Interestingly those tests fail on python 3.6+, but not on Python 2.7.

@MVrachev, have you figured out why tests don't fail on 2.7? That seems odd to me.

**Comment by MVrachev** [comment]
Now, after I have updated to the latest `securesystemslib` it seems python2.7 fails too.
It seems I hadn't updated `securesystemslib` to the latest version on my python2.7 venv.

**Comment by lukpueh** [comment]
Just merged https://github.com/theupdateframework/tuf/issues/1204. @MVrachev, if you rebase on the latest `develop` your tests should pass.

**Comment by lukpueh** [comment]
I also referenced the comment about non-matching Travis/Appveyor test setup in https://github.com/theupdateframework/tuf/issues/1195#issuecomment-725345413. I think we can close here. @jku, @MVrachev, you agree?

**Comment by MVrachev** [comment]
Yes, checked on python 3.8 and python 2.7 and this issue is solved for me and we can continue the discussion about the CI systems on the issue you have already opened about it.
