### ISSUE TITLE
Failing CI due to import path

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1227]
**Description of issue or feature request**:
After merging my pr https://github.com/theupdateframework/tuf/pull/1216 @jku noticed that one of the latest CI builds 
https://travis-ci.com/github/theupdateframework/tuf/jobs/449593878
is failing. 
The reason it seems that Travis CI is importing the wrong test package - the one from `securesystemlib` instead of the one from TUF.
**Current behavior**:
Wrong import.

**Expected behavior**:
Import the tuf test package and the `utils` module in it.

**Comment by joshuagl** [comment]
Because the 'tests' directory is on `sys.path` we should be able to get away with a relative import
`from tests import utils` -> `import utils`

**Comment by lukpueh** [comment]
> Because the 'tests' directory is on `sys.path` we should be able to get away with a relative import
> `from tests import utils` -> `import utils`

This further ties us to running tests from within the tests directory. But it seems like a reasonable quick fix.

**Comment by joshuagl** [comment]
An alternative would be to not install securesystemslib in editable mode. 

```
diff --git a/tox.ini b/tox.ini
index 221aefa5..eab774bd 100644
--- a/tox.ini
+++ b/tox.ini
@@ -30,7 +30,7 @@ install_command = pip install --pre {opts} {packages}
 # Must to be invoked explicitly with, e.g. `tox -e with-sslib-master`
 [testenv:with-sslib-master]
 deps =
-    --editable git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib
+    git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib
     -r{toxinidir}/requirements-test.txt
     --editable {toxinidir}
```

I'm not sure why the decision was originally made to install securesystemslib as an editable, can you comment on that @lukpueh ?

**Comment by lukpueh** [comment]
Good question! I might have adopted my local (non-tox) setup for a tuf environment that tests against a (moving) local securesystemslib. But in a short-lived tox env that doesn't make sense.

**Comment by MVrachev** [comment]
> An alternative would be to not install securesystemslib in editable mode.
> 
> ```
> diff --git a/tox.ini b/tox.ini
> index 221aefa5..eab774bd 100644
> --- a/tox.ini
> +++ b/tox.ini
> @@ -30,7 +30,7 @@ install_command = pip install --pre {opts} {packages}
>  # Must to be invoked explicitly with, e.g. `tox -e with-sslib-master`
>  [testenv:with-sslib-master]
>  deps =
> -    --editable git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib
> +    git+http://github.com/secure-systems-lab/securesystemslib.git@master#egg=securesystemslib
>      -r{toxinidir}/requirements-test.txt
>      --editable {toxinidir}
> ```
> 
> I'm not sure why the decision was originally made to install securesystemslib as an editable, can you comment on that @lukpueh ?

So, should I push a quick fix by returning the import from this `from tests import utils`
to this `import utils` or we want to discuss furthermore what Joshua had said above?

**Comment by joshuagl** [comment]
For me the better fix is to not install securesystemslib as editable. I would welcome a patch for that @MVrachev
