### ISSUE TITLE
Expiration check does not follow the spec

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#1231]
**Description of issue or feature request**:

The metadata expiry check [code](https://github.com/theupdateframework/tuf/blob/fc4b77f92ce3ffc492ea2f1e630a4217c2646f3e/tuf/client/updater.py#L2269) does not follow the [specification](https://github.com/theupdateframework/specification/blob/56ef9545ea244d9c5397bce72278eb01483888d2/tuf-spec.md):

`Check for a freeze attack. The expiration timestamp in the trusted $ROLE metadata file MUST be higher than the fixed update expiration time.`

**Current behavior**:

`expires < now`

**Expected behavior**:

`expires <= now`

**Comment by trishankatdatadog** [comment]
Cc the in-toto team @lukpueh @adityasaky @SantiagoTorres, where the [code](https://github.com/in-toto/in-toto/blob/78a162f96b6f5f2eceaac2943e52336fd9e1b65b/in_toto/verifylib.py#L252) is `expires < now`

The [spec](https://github.com/in-toto/docs/blob/c2251b3db89d9c06e07918022b58b70079c77b10/in-toto-spec.md) seems underspecified:

`EXPIRES determines when layout metadata should be considered expired and no longer trusted by clients. Clients MUST NOT trust an expired file.`

We should discuss whether both projects should consider whether a metadata file has expired in the same manner.

**Comment by mnm678** [comment]
I think this is actually a problem with the specification. I understand an expiration time as metadata that expires `at` a certain time, rather than `after` a certain time.

**Comment by SantiagoTorres** [comment]
> I think this is actually a problem with the specification. I understand an expiration time as metadata that expires at a certain time, rather than after a certain time.

+1. Although I think just having agreement is more important than either option winning imvho

**Comment by trishankatdatadog** [comment]
Yes, this was a recent change to the spec, and a second of difference is not going to break any significant security guarantee.

Personally, I think `<=` makes (slightly) more sense than `<`.

**Comment by trishankatdatadog** [comment]
Now that I look at other implementations, such as [ProtonMail/Crypto](https://github.com/ProtonMail/crypto/blob/b4bfec6bba36f063fc4218dcf7a12c577de64096/openpgp/packet/public_key.go#L824), they use `<`.

Does anyone have other implementations/interpretations elsewhere?

**Comment by trishankatdatadog** [comment]
Now that I look at other implementations, such as [ProtonMail/Crypto](https://github.com/ProtonMail/crypto/blob/b4bfec6bba36f063fc4218dcf7a12c577de64096/openpgp/packet/public_key.go#L824), they use `<`. Can someone double-check me here? It's getting late (4am) and I'm tired.

Also, does anyone have other implementations/interpretations elsewhere?

**Comment by joshuagl** [comment]
> I think this is actually a problem with the specification. I understand an expiration time as metadata that expires `at` a certain time, rather than `after` a certain time.

I think this sounds sensible. However,

> does anyone have other implementations/interpretations elsewhere?

x509 certificates are not a perfect comparison, but they are valid for a [date range (notBefore through notAfter)](https://tools.ietf.org/html/rfc5280#section-4.1.2.5), with the certificate only classing as expired, with:
> validity period for a certificate is the period of time from notBefore through notAfter, inclusive.

Which results in comparisons as `<=` such as in [openssl](https://github.com/openssl/openssl/blob/master/crypto/x509/x509_vfy.c#L1917).


GnuPG has expiration checks that look like `sig->expiredate <= make_timestamp ()` i.e. in [`parse_signature`](https://github.com/gpg/gnupg/blob/357ad9ae29677c1676b56d2b81282e2f78ec8040/g10/parse-packet.c#L2249) and [`build_sig_subpkt`](https://github.com/gpg/gnupg/blob/357ad9ae29677c1676b56d2b81282e2f78ec8040/g10/build-packet.c#L1241).


I agree with Santiago. The important thing is that we agree on an interpretation, and are consistent.

**Comment by trishankatdatadog** [comment]
Thanks for checking against independent implementations, Joshua, great work!

Agreed with consensus (luckily that doesn't need meta-voting). By sheer precedent, as in legal cases, I'm personally voting for `<=`. Are we using threshold signatures for voting here; how does this work?

**Comment by trishankatdatadog** [comment]
OTOH, to play devil's advocate, reference and independent implementations of TUF and in-toto are probably all using `<` for some time already, and using `<=` requires all of them to update. Probably something that requires a community meeting in (of?) both.

**Comment by joshuagl** [comment]
Looking at known open source tuf implementations:
* rust-tuf: `<=` i.e. https://github.com/heartsucker/rust-tuf/blob/373cf2216c3ec38b64629675ccbd96979e4bede8/src/client.rs#L543
* go-tuf: `<=` i.e. https://github.com/theupdateframework/go-tuf/blob/1353a38b9741511d20a627df516f0737f657007a/verify/verify.go#L40
* tough: `<` i.e. https://github.com/awslabs/tough/blob/e63ee71f4fdb08c3c877686061e16ae9dd4a555a/tough/src/lib.rs#L395

(I would appreciate it if people who are fluent in Go and Rust would double-check my interpretations)

**Comment by trishankatdatadog** [comment]
> (I would appreciate it if people who are fluent in Go and Rust would double-check my interpretations)

Cc @titanous @erickt @iliana

**Comment by lukpueh** [comment]
> The [spec](https://github.com/in-toto/docs/blob/c2251b3db89d9c06e07918022b58b70079c77b10/in-toto-spec.md) seems underspecified:
...

I beg to differ, the [final product verification workflow section](https://github.com/in-toto/docs/blame/c2251b3db89d9c06e07918022b58b70079c77b10/in-toto-spec.md#L1101-L1103) clearly mandates `expires < now` (as is implemented in python-in-toto):
>  If the system's date is newer than the expiration date on the layout's expiration field, verification should fail.

Although, we might want to `s/newer/higher` and `s/date/datetime`.

**Comment by erickt** [comment]
@joshuagl - you are correct, we are using `<=` in rust-tuf and go-tuf.

**Comment by joshuagl** [comment]
Thank you for confirming @erickt

**Comment by mnm678** [comment]
Thanks for doing some research @trishankatdatadog and @joshuagl. It looks like there is a general consensus for `<=`, so I agree that it makes sense to change our implementation.

**Comment by lukpueh** [comment]
>  It looks like there is a general consensus for `<=`

Is there though?  Here are some more data points:


python-tuf: `<`
tough: `<`
in-toto spec: `<`
python-in-toto: `<`
[in-toto-golang](https://github.com/in-toto/in-toto-golang/blob/f3f615b900aa4798e9f0558f2f90c37884d0345f/in_toto/verifylib.go#L555): `<=`
tuf spec: `<=`
rust-tuf: `<=`
go-tuf: `<=`

**Comment by trishankatdatadog** [comment]
> Is there though? Here are some more data points:

Don't forget GPG and OpenSSL...

**Comment by lukpueh** [comment]
Maybe not a consensus but at least a majority for `<=`?

I'm happy to review PRs that update `python-tuf`, in-toto spec and `python-in-toto`. :)

**Comment by iliana** [comment]
>  tough: `<`

Hard to remember but I imagine this was a literal reading of the detailed workflows, which were followed very literally to develop tough initially.

We haven't gone through spec changes in a while. Is the current revision internally inconsistent on this right now, and does it need clarified?

**Comment by lukpueh** [comment]
Thanks for chiming in, @iliana. The spec is not inconsistent in itself. There are only inconsistencies between tuf and in-toto (i.e. tuf's sister project) specs and the corresponding implementations. And there seems an agreement to consolidate all of these, which will require either some implementations and/or specifications to change.

**Comment by joshuagl** [comment]
I've created a PR against python-tuf (#1235) and filed issues against the in-toto specification (in-toto/docs#42) and reference implementation (in-toto/in-toto#417). That just leaves Tough that doesn't follow the rough consensus here, @iliana would you like me to file an issue there?

**Comment by iliana** [comment]
> That just leaves Tough that doesn't follow the rough consensus here, @iliana would you like me to file an issue there?

Sure, thanks!

**Comment by joshuagl** [comment]
> > That just leaves Tough that doesn't follow the rough consensus here, @iliana would you like me to file an issue there?
> 
> Sure, thanks!

[Done](https://github.com/awslabs/tough/issues/287)
