### ISSUE TITLE
New API: Add a constants module

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1241]
**Description of issue or feature request**:
I think it will be useful to have a constant module in the new API.
This will help us to minimize the errors when writing hardcoded strings.
For example, the "snapshot.json" string is used often in the `Timestamp` class in `tuf/api/metadata.py`.

@joshuagl raised awareness for that in this comment:
https://github.com/theupdateframework/tuf/pull/1223#discussion_r541023911

**Current behavior**:
Harcoded strings.

**Expected behavior**:
Use constant containing the string.

**Comment by jku** [comment]
For the specific case mentioned, could it not be `Snapshot.filename` in metadata.py as the filename seems to be a specified feature of snapshot metadata? That Snapshot.filename could be a "getter-only" property to underline how it's not supposed to be changed...

EDIT: actually the property might not be a good idea as you can't have _class_ properties... `Snapshot.filename` (not instantiating Snapshot) only works if filename is a plain class variable. But that's Python: could make it  `Snapshot.FILENAME` to make it look more constant

**Comment by MVrachev** [comment]
Do we need a separate module other than the one added in https://github.com/theupdateframework/tuf/pull/1470?

**Comment by MVrachev** [comment]
@jku any opinions?

**Comment by MVrachev** [comment]
The Metadata API and the updater implementation have evolved sufficiently that we don't need one central place for constants.
Currently, we write the constants directly in the [metadata API module itself](https://github.com/theupdateframework/python-tuf/blob/develop/tuf/api/metadata.py) and we have a separate one inside the updater [here](https://github.com/theupdateframework/python-tuf/blob/develop/tuf/ngclient/config.py).
If in the future we decide we need one central place or to minimize the length of Metadata API we will create other issues for that.
