### ISSUE TITLE
GitHub Actions: Find and implement fail-fast strategy

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1248]
**Description of issue or feature request**:

#1242 added a GitHub Actions based CI workflow, which runs all configured builds in parallel, ignoring each others build results. However, GitHub Actions provides an option (i.e. `fail-fast`), to abort all builds if any build fails. This option might be useful for specific build relationships, where one failing build is likely to entail other failing builds.

**Current behavior**:
`fail-fast: false`

**Expected behavior**:
Consider `fail-fast: true` (default) but with specific conditions, e.g. prioritize `lint` build and abort any other build if that one fails.

**Comment by lukpueh** [comment]
Another way to do this would be to make lint and test builds different jobs and configure `needs: [<lint job>]` on the test job.

**Comment by shabeebk** [comment]
I have made some changes in the GitHub actions file to achieve the below intentions.
1. Run the lint job as the first job in the matrix.
2. Fail all of the follow-up jobs if lint fails.
3. Allow failure of other jobs is lint passed.

Please review the PR. Thanks.
