### ISSUE TITLE
Fix simple typo: excepion -> exception

### ISSUE THREAD

**Issue by timgates42** [theupdateframework/tuf#1262]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine tests/test_roledb.py.
2. Search for `excepion`.

# Expected Behaviour

1. Should read `exception`.

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR.

https://github.com/timgates42/tuf/pull/new/bugfix_typo_exception

Thanks.

**Comment by rzr** [comment]
your change looks good, 
I've checked it applies well to current develop branch,
feel free to open a pull request to get it merged.

**Comment by rzr** [comment]
ok perfect then please verify and check that the pull request fulfills the following
requirements:

https://github.com/theupdateframework/tuf/pull/1298

you only need to tick boxes, this is a way to prevent to get untested code in.
