### ISSUE TITLE
Go-tuf (TUF 0.9) backwards compatibility 

### ISSUE THREAD

**Issue by houdini91** [theupdateframework/tuf#1267]
**Description of issue or feature request**:
Go-tuf cannot use a repository created by python repository_lib.
It seems go-tuf  currently support TUF 0.9 spec with some exceptions.

**Current behavior**:
Go-tuf client fails because the snapshot metadata does not include the 'root.json' field.
if i understand correctly it is the result of [TAP 5](https://github.com/theupdateframework/taps/blob/master/tap5.md)

**Expected behavior**:
It will be useful to be able to create a repository with the python library and validate it by the latest  Go-tuf client.

**Suggestion**:
I have added the fallowing changes locally and they seem to work for me.
I not sure what what are all the repercussions are, but it may be enough to include it with some kind of flag.

```
 def generate_snapshot_metadata(metadata_directory, version, expiration_date,
     storage_backend, consistent_snapshot=False,
-    repository_name='default', use_length=False, use_hashes=False):
+    repository_name='default', use_length=False, use_hashes=False, backward_capability=False):
   """
   <Purpose>
     Create the snapshot metadata.  The minimum metadata must exist (i.e.,
@@ -1667,7 +1667,7 @@ def generate_snapshot_metadata(metadata_directory, version, expiration_date,
       # snapshot and timestamp roles are not listed in snapshot.json, do not
       # list these roles found in the metadata directory.
       if tuf.roledb.role_exists(rolename, repository_name) and \
-          rolename not in tuf.roledb.TOP_LEVEL_ROLES:
+          (rolename not in tuf.roledb.TOP_LEVEL_ROLES  or(backward_capability and rolename=='root') ):
 
         length, hashes = _get_hashes_and_length_if_needed(use_length, use_hashes,
             os.path.join(metadata_directory, metadata_filename), storage_backend)
```
As far i understand it should't be a security issue - [analysis](https://github.com/theupdateframework/taps/blob/master/tap5.md#backwards-compatibility)

thanks, i am a fan of your good work, keep it up.
hope this helps someone.
best regards
mikey.

**Comment by trishankatdatadog** [comment]
@houdini91 thanks for your time and attention on this issue, but the change should be in go-tuf rather than here. Would you please help us send a patch there? Thanks!

**Comment by houdini91** [comment]
@trishankatdatadog
Hi, Thanks for the reply.
Can you please elaborate a bit what changes you had in mind that can be done in go-tuf library to mitigate the problem?

My understanding is that go-tuf library support the 0.9 Spec - Changes to its own metadata structure or order will brake the library and standard.

While a patch to the python version will add a more complete backwards compatibility support for 0.9 spec.
It also seems that this issue was recognized and analysis by TAP5.

Best regards.

**Comment by trishankatdatadog** [comment]
Change go-tuf so that it doesn't fail on not seeing root.json inside snapshot.json, as per the current spec.
