### ISSUE TITLE
Permanent Takedown Threat

### ISSUE THREAD

**Issue by adrelanos** [theupdateframework/tuf#127]
This is maybe a feature request.

**Permanent Takedown Threat** (PTT for now), defined as:
An attacker takes down a mirror by taking over the domain or by taking down the server using DoS attack, cracking down the server with malware or by pressuring humans (the server administrator).

It would be great if you could add PTT to the [TUF threat model](https://www.updateframework.com/projects/project/wiki/Docs/Security).

Defense:
- possible when having multiple mirrors
- allow still existing, trusted mirrors to announce that specific mirrors should be no longer used or that new mirrors should be trusted as well

**Comment by mnm678** [comment]
The [TUF specification](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md) has been updated to include a description of malicious mirror attacks and denial of service attacks. I believe the combination of these attacks describes how TUF handles PTT. See [specification#84](https://github.com/theupdateframework/specification/pull/84#issuecomment-573148485) for more discussion.
