### ISSUE TITLE
Remove use of six

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1296]
**Description of issue or feature request**:

Following the release of tuf 0.17.0 (see https://github.com/theupdateframework/tuf/pull/1284) we are no longer supporting Python2, and have started to remove uses of Python2 in #1293 (see also #1276).

[Six](https://six.readthedocs.io) is a Python 2 and 3 compatibility library, which is clearly no longer required.

**Current behavior**:

Six is marked as a dependency in setup.py and our requirements files.
Six is imported and used in multiple modules, tests, and scripts.

**Expected behavior**:

six is no longer a dependency and is not imported, or used, in any modules, tests, or scripts.

**Comment by avelichka** [comment]
Hi folks,

I'd like to work on this issue if it's OK :)
