### ISSUE TITLE
Add 'expired' method to Signed class

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1305]
**Description of issue or feature request**:
Add a method of `Signed` metadata class returning information about metadata expiration given a reference time.

**Current behavior**:
`Signed` class already contains expires, a metadata expiration datetime object. 

**Expected behavior**:
A method exists that checks the 'expires' attribute against a reference time.
`def is_expired(self, reference_time: float) -> bool`

**Comment by sechkova** [comment]
`tuf.formats` already provides some convertion functions:
https://github.com/theupdateframework/tuf/blob/2c360d0538f73a59854add867234f48a47f7d9a3/tuf/formats.py#L616
https://github.com/theupdateframework/tuf/blob/2c360d0538f73a59854add867234f48a47f7d9a3/tuf/formats.py#L646

**Comment by joshuagl** [comment]
Is a UNIX timestamp the preferred type for `reference_time`? Rather than a raw expiration string or a Python datetime object?

**Comment by lukpueh** [comment]
What's the intended use case? Would any of the datatypes be more convenient for the caller, that is which datatype would require the least preliminary conversion?

I lean towards making `reference_time` a datetime object, for consistency with the type of the Metadata `expires` field. And I'd also make `reference_time` optional and default to `datetime.now()`.

**Comment by joshuagl** [comment]
Fully agreed with both comments. I have a WIP patch that takes a datetime object for `reference_time` and defaults to `datetime.now()` when no `reference_time` is passed.

I believe the motivating use-case is expiration checks in the experimental client, so I'll wait for @sechkova to comment on whether a `datetime` object is useful.

**Comment by sechkova** [comment]
No strong preferences, the client will use whatever  we choose :) 
I agree with using `datetime` objects plus the `datetime` module seems to be less platform dependent than `time` (which can be used to return UNIX time).

Let's make sure we enforce UTC times everywhere.
