### ISSUE TITLE
Split Updater into logical components: bundle metadata

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1308]
I think this the right time to try splitting the Updater functionality into meaningful components -- the Metadata API does a good bit of that already but I think Updater is still going to be too large and should be split if possible  (and I think it is possible, also tuf-on-a-plane has some useful ideas). Listing some Updater functionality below for inspiration:
* implement the TUF update process in a way that is easy to follow and verify
* keep track of currently valid set of metadata, verify new metadata
* read/write local metadata files
* traverse target delegation tree
* download metadata/target files, while handling mirrors

To me tracking the _currently valid set of metadata_ is one potentially separate thing here: an object could hold the currently valid set of metadata (and verify new metadata and maybe handle reading/writing the local metadata cache) without knowing about all the steps that the TUF spec requires or about the API that Updater wants to provide. Maybe this leads to most code being in the metadata handler but this might be worth testing -- it's also something a bit like what @trishankatdatadog did in tuf-on-a-plane (Repository vs models,writers,readers).

_Originally posted by @jku in https://github.com/theupdateframework/tuf/issues/1291#issuecomment-792612877_

**Comment by sechkova** [comment]
To be fixed by #1355

**Comment by jku** [comment]
Closing:
* MetadataBundle is merged (if not quite in use yet)
* download handling is a lot better separated now that mirrors are gone

Further changes in components can be done incrementally:
* maybe we want to separate Updater and target caching
* maybe we want to separate graph traversal and the Updater
