### ISSUE TITLE
Add/rewrite tests for the refactored client

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1309]
**Description of issue or feature request**:

A placeholder to mark the need of reviewing the existing tests once the client refactor has progressed enough. 

Sync with #1129

**Comment by sechkova** [comment]
Sync with #1129

**Comment by jku** [comment]
The coverage situation is dire:
```
/home/jku/src/tuf/tuf/client_rework/download.py
113->114, 114-119, 215->216, 216-243, 252->253, 253
/home/jku/src/tuf/tuf/client_rework/metadata_bundle.py
94->101, 95->103, 99->exit, 101, 103->104, 104, 115-117, 157, 161, 198->199, 199, 209->210, 210, 214->216, 216-222, 243->244, 244, 282->283, 283, 289->294, 294, 300->301, 301, 320->321, 321, 338-339, 341->342, 342, 346->347, 347, 351->355, 355, 361->362, 362-373, 378->379, 379, 421->422, 422, 427->428, 428-433, 451->452, 452, 457->458, 458
/home/jku/src/tuf/tuf/client_rework/requests_fetcher.py
102->103, 103, 136-137, 152->153, 153
/home/jku/src/tuf/tuf/client_rework/updater_rework.py
65->66, 66, 74->77, 77, 147->148, 148, 167->168, 168-170, 195->196, 196, 200->203, 203, 253->268, 258-259, 262->263, 263, 299->300, 300, 319->320, 320, 353->354, 354-356, 375->378, 388->389, 389-398, 400->401, 401-402, 421->426, 426-430, 479->480, 480-485, 487->523, 489->529, 499->511, 511-529, 540->541, 541, 556->557, 557, 571-576
```

I think it makes sense to start with the bundle and figure out how to efficiently and readably test every branch in the `update_*()` functions. A major task is probably figuring out how to define a "changing set of metadata" in the tests: we want to test not only loading a specific metadata, but then test loading new metadata that gets validated by the old one -- and do this many times while keeping it all readable.

**Comment by jku** [comment]
We're omitting the new client from coverage limit for now:
`python -m coverage report -m --fail-under 97 --omit "{toxinidir}/tuf/client_rework/*`
this should be fixed once we get back to reasonable coverage

**Comment by jku** [comment]
oh now I've filed this twice... I'm closing this one as #1462 has a little more details
