### ISSUE TITLE
client refactor: review _get_*_meta_name() usage

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1319]
Simplify and remove duplication from metadata filename handling (_get_relative_meta_name(),_get_full_meta_name())

* remove duplication
* probably no need to make the extension modifiable: .json is fine
* there are cases of _get_full_meta_name('timestamp.json') -- this seems like a bug?

**Comment by sechkova** [comment]
To be resolved with #1396

**Comment by sechkova** [comment]
Closed with #1396.
