### ISSUE TITLE
Secure NTP protocol

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#132]
According to @JustinCappos: 

> A secure NTP solution is a solution [to address highly skewed or adrift client clocks]. However, what about mirrors and proxies? We need to think about that case in general.

**Comment by trishankkarthik** [comment]
Need to look at [roughtime](https://www.imperialviolet.org/2016/09/19/roughtime.html) at some point

**Comment by adrelanos** [comment]
Also have a look https://www.whonix.org/wiki/Sdwdate

**Comment by trishankkarthik** [comment]
Thanks for the tip!

**Comment by trishankatdatadog** [comment]
Out of the scope of TUF
