### ISSUE TITLE
Incorrect target URL encoding and decoding

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#133]
The TUF library inconsistently handles the way target paths are encoded in the targets metadata and the way URLs are used to resolve a target.

More concretely speaking, a target may be encoded one way in the targets metadata, and a URL for the target may be encoded in another way; so a request for the target may be incorrectly reported as being missing.

Example: suppose the targets metadata described a target with the path "Foo Bar.exe". The URL request for this target will be encoded as "http://.../Foo%20Bar.exe". The updater code does not decode the URL to remove [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding). Therefore, the updater will incorrectly report that the target "Foo%20Bar.exe" is missing even though the intended target "Foo Bar.exe" exists.

**Comment by lukpueh** [comment]
This was fixed with https://github.com/theupdateframework/tuf/pull/734
