### ISSUE TITLE
Revise the disabling of broad-except pylint warning (W0703)

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1332]
**Description of issue or feature request**:
An (anti)pattern starts to appear in the newer code (where stricter `pylint` checks are applied), a tendency to disable [broad-except ](https://pycodequ.al/docs/pylint-messages/w0703-broad-except.html) warnings.

Even though each case has its arguments, we should as a minimum make sure we [log the exception](https://realpython.com/the-most-diabolical-python-antipattern/) and not silently bury it.

**Current behavior**:
`# pylint: disable=broad-except` throughout the code 

**Expected behavior**:
At least log the exception before ignoring it:
```
try:
    do_something()
except Exception as e:
    logger.exception("An exception occurred")
```
Sync with #1178

**Comment by sechkova** [comment]
This issue is directly related to the newer parts of code (`api/*`) where the new `api/pylintrc `config applies:
```
tuf/api/serialization/json.py:        except Exception as e:  # pylint: disable=broad-except
tuf/api/serialization/json.py:        except Exception as e:  # pylint: disable=broad-except
tuf/api/serialization/json.py:        except Exception as e:  # pylint: disable=broad-except
```
In the top-level `pylintrc` used by the rest of the code the `broad-except ` warning is disabled globally.

**Comment by sechkova** [comment]
Sync with #1178

**Comment by jku** [comment]
It's possible that the deserialization cases are actually appropriate (I'm not sure if we can figure out all the ways that deserialization can fail, and the callers certainly won't care too much) but you are right we should review this.

**Comment by sechkova** [comment]
I tested this with the intention to close the issue since the disable is well justified in `serialisation/json.py` and another exception is re-raised from the broad one ... but surprisingly `pylint` agrees with us! 
`Pylint` does not emit the error anymore and the disabling is not needed ... it was needed when python 2.x was supported and `six` was used (see https://github.com/theupdateframework/tuf/commit/bd94f6d8d140f117f7e5f79af5c892423d70e18e).

Assigning this to myself to fix it (remove the disabling of the warning).
