### ISSUE TITLE
Implement from_object/from_string method in Metadata class

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1336]
**Description of feature request**:
Implement a class method in `Metadata` class, similar to the existing `from_file` method but taking a file object as an argument.

See #1304 for context.

**Comment by jku** [comment]
I assume this is useful because client does not write new metadata to disk before it's verified so at that point there's only a file-like object but we want to instantiate the Metadata to verify it is correct?

I guess the other alternative to `from_object()` is `from_string()` (and client would then call `from_string(tmp_file.read())`). I don't think it's clearly better just thinking out loud.

**Comment by sechkova** [comment]
> I assume this is useful because client does not write new metadata to disk before it's verified so at that point there's only a file-like object but we want to instantiate the Metadata to verify it is correct?
> 

Yes, exactly.

> I guess the other alternative to `from_object()` is `from_string()` (and client would then call `from_string(tmp_file.read())`). I don't think it's clearly better just thinking out loud.

You don't like a function signature with the vague definition of a file object? :) 
String would be ok, raw bytes too, no need to be a file object with its associated methods.
 
Now that a separate serialisation was implemented, all we need is basically a method that calls  [deserialize](https://github.com/theupdateframework/tuf/blob/cd39bff1e5712f6ca9ebfd579ae8a52752159241/tuf/api/serialization/json.py#L33).

**Comment by sechkova** [comment]
Something like the existing `from_file` but without the actual file read from the file system:

 ```python
   @classmethod
    def from_string/from_bytes/from_raw(
        cls,
        raw_data: str/bytes,
        deserializer: Optional[MetadataDeserializer] = None
    ) -> "Metadata":

        if deserializer is None:
            deserializer = JSONDeserializer()

        return deserializer.deserialize(raw_data)
```

**Comment by jku** [comment]
looks good to me -- `str` seems to make sense as type to me
