### ISSUE TITLE
Update python commands in documentation

### ISSUE THREAD

**Issue by KainaatSingh** [theupdateframework/tuf#1349]
**Description of issue or feature request**:
With the release of tuf 0.17.0 python2 support was removed. Parts of the documentations contain commands that state the usage of python instead of python3 and pip instead of pip3. The commands with "python" will not work outside the virtualenv. It would help to explicitly state "python3" and "pip3" here.

It would be helpful to agree on as to where and what changes might be appropriate.

**Current behavior**:
`pip install -r requirement-dev.txt`
`python aggregate_tests.py`

**Expected behavior**:
`pip3 install -r requirements-dev.txt`
`python3 aggregate_tests.py`

**Comment by jku** [comment]
> The commands with "python" will not work outside the virtualenv

This depends, it does work in some OSes / install methods... but consistency is good so I think this is a good idea.

`python3 aggregate_tests.py` looks obviously correct to me. https://docs.python.org/3/installing/index.html seems to suggest following would be best for pip calls: `python3 -m pip install -r requirements-dev.txt`.

**Comment by samuelgregorovic** [comment]
i can solve this if you would assign this to me

**Comment by samuelgregorovic** [comment]
i can update the docs to exclude old python2 commands and update them to python3, if you would assign it to me

**Comment by jku** [comment]
Thank you, assigning

**Comment by samuelgregorovic** [comment]
@jku i updated everything relevant i could find + removed some doc-lines where you could find Python2 command alternative. I also updated the `pip install` commands to be consistent to -> `python3 -m pip install`

**Comment by samuelgregorovic** [comment]
@jku i updated everything relevant i could find + removed some doc-lines where you could find Python2 command alternative. I also updated the pip install commands to be consistent to -> python3 -m pip install

**Comment by jku** [comment]
Fixed in #1493, thanks!
