### ISSUE TITLE
Let's not use pre-release versions of tools in tox environments

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1350]
We do `pip install --pre ...` in tox.ini. This means our testing tools like coverage, black, isort etc (and I suppose their dependencies) may be pre-releases.

This has been the case since 2015 but it sounds like a bad idea. Should we drop the `--pre`?

**Comment by joshuagl** [comment]
If we don't have a good reason to keep it, or don't know what the good reason was, I vote we drop use of `--pre`
