### ISSUE TITLE
Metadata API: Root.consistent_snapshot should be optional

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1374]
Spec:
> Finally, the root metadata should write the Boolean "consistent_snapshot" attribute at the root level of its keys of attributes. If consistent snapshots are not written by the repository, then the attribute may either be left unspecified or be set to the False value. Otherwise, it must be set to the True value.

Metadata API (tuf/api/metadata.py) seems like it would fail to read json that does not contain "consistent_snapshot"

**Comment by MVrachev** [comment]
Doesn't that mean that `consistent_snapshot` should be an optional attribute in the spec?
It is not at the minute.

Also, I am not sure what the last sentence means `Otherwise, it must be set to the True value`.
"Otherwise" what? If `consistent_snapshot` is found or?

**Comment by jku** [comment]
Yes you're right I think, although it should probably be phrased so that new implementations should include it in new versions of metadata but that old metadata may exist without it
