### ISSUE TITLE
Metadata API: stop using formats.py

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1384]
Currently we have one use of tuf/formats.py in tuf/api/metadata.py. I think we should try to keep the two implementations separate.

**Current behavior**:
`formats.expiry_string_to_datetime()` is used in metadata.py

**Expected behavior**:
We should do the conversion in metadata.py (and I think we should not raise securesystemslib errors like current implementation does).

**Comment by avelichka** [comment]
I'd like to work on that :)
