### ISSUE TITLE
ngclient: Proper public module documentation

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1385]
New client should have good public module/class documentation for Updater: currently it's a bit patchy.

_Plan is to get the new client merged to develop (as alternative client, not replacing the current one): this issue can be solved after merge._

**Comment by jku** [comment]
A specific improvement is reviewing and documenting what target_path really is and how it works (that it's target identifier but also a relative local filesystem path and a url fragment).

**Comment by joshuagl** [comment]
It would be great if this documentation was publishable/published on readthedocs.io, like the in-toto docs https://in-toto.readthedocs.io/en/latest/

Note: There's some previous discussion on TARGETPATH here https://github.com/theupdateframework/tuf/issues/462

**Comment by jku** [comment]
Documenting also my recent realization on target_path: the spec does not require target_path to be a usable relative local filesystem path (and it can't really -- this requires assumptions on the filesystem). Using target_path as a relative local filesystem path  is just how both the reference repository tools and the reference client have decided to implement it.
