### ISSUE TITLE
Document Metadata API: MetaFile hash matching issue with serialization

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1392]
So far I've been assuming we can build the client and use the Metadata API to
* deserialize what we get from the remote repo, and then
* serialize the data to disk once we know it's valid

The issue here is "meta" in timestamp (and I suppose snapshot) can contain file hashes. If we only store on local disk what has been deserialized and then serialized these hashes will fail to match when they are next read from disk (because white space etc).

Fixing this in the client is easy but I wonder if there's something that needs to be done in metadata API to make this more obvious or a harder mistake to make.

**Comment by sechkova** [comment]
We can extend the metadata api to store/write the raw data.
Something like:

```
Metadata.from_bytes(data, raw_bytes=True) # this stores the same data twice, with and without serialization 
Metadata.to_file(deserialize=False) # writes the stored raw data 
```

But is it worth doubling the size of the object just for convenience ... is it even a convenience? I am not really suggesting it without having a good use case.

I hope someone comes up with a good suggestion of documentation instead :)

**Comment by MVrachev** [comment]
I agree with the sentiment that you wouldn't expect to change the file just by deserializing and serializing.
I would even consider this as a bug because it's sure not what you would expect.

My opinion is that we should change the default behavior of `Metadata.to_bytes()` and consequently to
`Metadata.to_file()` so that it doesn't use `serializer = JSONSerializer(compact=True)` by default, but
instead use `serializer = JSONSerializer(compact=False)`.
I would expect that the human-readable JSON format with spaces will be the default for metadata files and
if I want to preserve space I will intentionally pass a serializer.

When and where did we end up deciding that we want to use compact by default?

**Comment by jku** [comment]
I'm changing the title so this is not about the client (as the client can just avoid serializing).

> I agree with the sentiment that you wouldn't expect to change the file just by deserializing and serializing.
> I would even consider this as a bug because it's sure not what you would expect.

I don't fully agree with that: deserialize/serialize is logically a destructive operation: there are infinite json files that deserialize to same Metadata but a single Metadata should always reproducibly serialize to a single json file. The idea of preserving the original file content and writing that instead _in some cases_ ... feels like it might not be the job for Metadata itself.

The "destructive" property of deserialize/serialize is not documented well enough though. Especially when it is done via from_file()/to_file() the effect is unexpected.

The only design improvement to Metadata I can think of would be "change tracking" -- that Metadata would somehow know if it has changed since deserialization or not (so users of the API could check if Metadata has changed or not). I'm not sure that's something Metadata itself should handle though: client doesn't really need this functionality and I'm not sure what the the "server-side" really wants to know/do...

> My opinion is that we should change the default behavior of `Metadata.to_bytes()` and consequently to
> `Metadata.to_file()` so that it doesn't use `serializer = JSONSerializer(compact=True)` by default, but
> instead use `serializer = JSONSerializer(compact=False)`.

I'd say that's a different issue though

**Comment by jku** [comment]
I think we should solve this issue with documentation: explain in the reference that deserialize-serialize cycle is not guaranteed to be byte-for-byte exact, even though signatures are guaranteed to stay valid. Maybe even specifically state that e.g. client should not serialize metadata to disk but should use the format it downloads.

**Comment by jku** [comment]
I think I intended to take this but did not ... taking it now
