### ISSUE TITLE
Interposition should allow streaming

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#140]
Presently, the interposition module does not allow for streaming of web documents. This causes problems such as applications not being able to determine the length of the document until the whole file has been downloaded and verified by TUF, and not being able to see the original HTTP headers (#141).

We should think about how to stream the requested file while preserving security.

**Comment by lukpueh** [comment]
`tuf.interposition` was removed in https://github.com/theupdateframework/tuf/pull/537. Closing.
