### ISSUE TITLE
ngclient: Use %-style formatting in logging

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1400]
(this is about code currently in experimental-client/ngclient branch, hopefully soon in develop)

We currently have some f-strings in logging:

```
                        msg = (
                            f"Adding child role {child_role_name}.\n",
                            "Not backtracking to other roles.",
                        )
                        logger.debug(msg)
```

Let's use %-style instead in logging (even if f-strings are great for other string formatting, see the google python style guide)

**Comment by avelichka** [comment]
I'd like to give it a try, please?

**Comment by trishankatdatadog** [comment]
Curious: why does Google recommend % over f-strings? I think the latter is far more readable, no?

**Comment by jku** [comment]
I agree, it's just that f-strings get greedily evaluated before logger can check if they are needed: with %-style the logger can check if the string is needed (and usually it isn't) before building the string. Obviously 99% of our logging is nowhere near a critical path where this would matter ... but I'd still like to be able to log inside e.g. a download loop without thinking about it.

The other reason would be that our linters complain :) We could of course modify our linter config (and document the style guide difference) but that feels like work too...

**Comment by trishankatdatadog** [comment]
My 0.02 BTC is that we should keep developers not Google/linters/speedtests happy, but that's just me. I will let you guys decide 🙂
