### ISSUE TITLE
ngclient: client-level constants

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1402]
The constants could use some thought: We definitely don't want to keep using tuf.settings, but I guess the question is, should these be instance variables in Updater instead of module level ones:

```
MAX_ROOT_ROTATIONS = 32
MAX_DELEGATIONS = 32
DEFAULT_ROOT_MAX_LENGTH = 512000  # bytes
DEFAULT_TIMESTAMP_MAX_LENGTH = 16384  # bytes
DEFAULT_SNAPSHOT_MAX_LENGTH = 2000000  # bytes
DEFAULT_TARGETS_MAX_LENGTH = 5000000  # bytes
```
Maybe it does not hurt if they were instance variables instead. They don't even need to be optional constructor arguments (as initialization does not use any of them: caller can initialize the Updater and then modify the values).
I guess the fanciest option is that constructor takes an optional argument dataclass UpdaterOptions with those attributes ...

_Originally posted by @jku in https://github.com/theupdateframework/tuf/issues/1396#issuecomment-842985740_

**Comment by sechkova** [comment]
I am in favour of the dataclass option because it groups all the configuration at one place and I drafted a proposal based on it:  #1470.
There is also `RequestsFetcher` which needs to be configured on init so I added the configuration as an optional parameter to `Updater`.  However I am not totally sure if this solution makes it convenient enough to customise the configuration and I will be happy to hear some opinions about it.

**Comment by trishankatdatadog** [comment]
> I am in favour of the dataclass option because it groups all the configuration at one place and I drafted a proposal based on it: #1470.

[Me too](https://github.com/trishankatdatadog/tuf-on-a-plane/blob/ee8049a63ea439d72509f6e876eef08fb50c6ab1/src/tuf_on_a_plane/config.py) 🙂
