### ISSUE TITLE
Metadata API: Consider including filename in TargetFile/MetaFile

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1411]
Currently TargetFile and Metafile do not contain the filename of the file they represent. The API itself does not need it but it could be useful for users of the api.

As an example the current client returns a dict for get_one_valid_targetinfo(): that dict contains a filepath field and and a targetinfo field (essentially TargetFile). I would like to keep a similar API but avoid hand-crafted dicts. It would be much nicer to return a TargetFile that would contain the full "metadata" of the targetfile.

I'm not 100% sure if there are similar advantages to MetaFile

**Comment by jku** [comment]
relates to #1317

**Comment by MVrachev** [comment]
I think it makes sense to implement this for the use case that we are sure about - add a path in `TargetFile` and then
if one day we see a benefit for adding the name in `MetaFile` then we should add it.
Do you agree @jku?
I can propose a pr for this.

**Comment by MVrachev** [comment]
I am working on this one already.

**Comment by MVrachev** [comment]
I decided to propose a pr adding target name in `TargetFile`, so that the use case we are sure about is addressed and after that, we can discuss if we want to do the same thing for `MetaFile`.

**Comment by MVrachev** [comment]
I had a look in our code at how we are using `MetaFile` and I can't find a place where adding `filename` to the `MetaFile` class will make the code cleaner or easier to understand.
I think we can close this issue for now and if we see the need in the future, then we can reopen this issue or open another one.
What do you think @jku?

**Comment by jku** [comment]
Sounds good.
