### ISSUE TITLE
Metadata API: enforce signature uniqueness by keyid

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1422]
I don't want to test in verify_signature() that only one signature exists for keyid: this should be enforced by Metadata class.

This requirement is not in the spec but I think it makes sense: if there are multiple signatures for the same keyid, something is wrong and failing early seems reasonable.

this should work:
* store signatures internally in `Dict[str, Signature]`: this enforces uniqueness for API users
* in from_dict(), error out if duplicate keyids are found: this enforces uniqueness in serialization
* when serializing (or otherwise returning the signatures as list), remember to make the output deterministic. Alternatively use OrderedDict in the first place to get determinism

**Comment by jku** [comment]
As trishank mentioned on slack: from python 3.7 Dict itself guarantees insert order so is deterministic -- for our uses OrderedDict still makes sense (and also informs the reader that the order matters)

**Comment by joshuagl** [comment]
> _Changed in version 3.7_: Dictionary order is guaranteed to be insertion order. This behavior was an implementation detail of CPython from 3.6.

from [here](https://docs.python.org/3/library/stdtypes.html#dict). That final part is notable because Python 3.6 is our baseline Python version, per [ADR-0001](https://github.com/theupdateframework/tuf/blob/develop/docs/adr/0001-python-version-3-6-plus.md).

**Comment by jku** [comment]
This is the same issue for the spec btw: https://github.com/theupdateframework/specification/issues/155 (only found it now :) )

**Comment by MVrachev** [comment]
> * in from_dict(), error out if duplicate keyids are found: this enforces uniqueness in serialization

In the `Role` class we are storing `keyids` as a list. Maybe we should store them in a set or it's better to loudly warn about this?
