### ISSUE TITLE
Provide a way to generate test data with invalid content but valid signatures

### ISSUE THREAD

**Issue by davidstrauss** [theupdateframework/tuf#1431]
**Description of issue or feature request**:

As part of PHP-TUF, we've been building out our own conformance suite of test fixtures. (I've posted before about how we've continued to improve the determinism of the design.) Unfortunately, there's a conflict between easy fixture generation, good security design, and comprehensive testing. It's making it hard for us to test scenarios where the signatures are valid but the signed data is broken in some way:

- The current library is mostly (and understandably) designed to provide correctly structured, signed data.
- As is best practice for our design, we minimize parsing and usage until after signature validation.
- We want to test our robustness against incorrect but signed data.

So, we're looking for advice or features -- we're not completely sure. Advice could be in the form of how to leverage `securesystemslib` or the TUF API to generate a signature over invalid metadata. Features could be in the form of a well-defined way to force the high-level TUF library to re-sign invalid data.

We've also considered adding a bypass to PHP-TUF to allow a fixture to be used in a way that skips signature validation before usage, but this seems undesirable in terms of making our fixtures maximally re-usable by other implementations.

**Comment by jku** [comment]
The new Metadata API has the same "problem" I think: being able to sign the payload requires the payload to be valid (not all validation is written yet but that's the intention)... 

I think something like this could work (intentionally not using TUF APIs to avoid any validation, present or future):
* use any tool to produce python dict representation of the payload. Something like
  ```
  md = json.load("filename")
  payload = md["signed"]
   ```
* modify/recreate the payload as test case demands
* `securesystemslib.formats.encode_canonical()` takes any python object (like "payload") and outputs canonical json
* create a signature using e.g. securesystemslib signer: `sig = securesystemslib.signer.SSLibSigner(privkey).sign(canonical_json)`
* insert/modify signature in `md["signatures"]`, write md to file

I'm sure there are more details to it but it feels like writing this into a small tool would not be too hard. Parts of the above could be handled by a higher-level library but then there's the danger of hitting some new validation that interacts with the invalid data you want to create...

**Comment by phenaproxima** [comment]
Thanks, @jku! I'll give that a try.

**Comment by lukpueh** [comment]
https://github.com/theupdateframework/python-tuf/issues/1431#issuecomment-852792092 provides a simple recipe to achieve this with Python standard library features and `securesystemslib`. 

I suggest to close now and re-open if there is a need to implement this recipe as part of `python-tuf`...
