### ISSUE TITLE
Metadata API: Tests (de)serialization with invalid arguments

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1434]
**Description of issue or feature request**:
I started creating issues documenting some research I do for how we use our metadata attributes.
For example #1418, #1419 and #1420. 
The end goal of this research is to decide how we are going to validate each of them, make the necessary changes and add tests ensuring the validation works.

Together with @jku we discussed that to achieve the last step - adding tests ensuring the validation works
it will be better if we wait for #1391 to be resolved.
That way we would come up with a better-refined approach of running a test case against multiple inputs. 

Also, I wanted to point out that there was a suggestion to use a fuzzing tool for this.
Maybe it's worth exploring.

We will want to test cases when our attributes are:

- [ ] empty values
- [ ] values from the wrong type
- [ ] non existent - they don't appear in the input dictionary when calling `from_dict()`

**Comment by MVrachev** [comment]
I created a prototype of how those tests could look like in this branch: https://github.com/MVrachev/tuf/tree/invalid-attributes.
@jku what do you think?

**Comment by jku** [comment]
I don't think you get any value from introducing the dict-in-dict structure for the data?

You could have these in the same file as the valid test cases, using the same DataSet data structure, using the same decorator. I think having the valid and invalid data for a class (like Key) near each other has value: if the file becomes too big then lets e.g. start splitting Signed-derivates to another file (but I don't think we're there yet).
