### ISSUE TITLE
New Metadata API: Should we add logging?

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1440]
**Description of issue or feature request**:
I was wondering should we add logging in the new metadata API we are using in `tuf/api/metadata.py`? 

For example when we have loaded successfully a top-level metadata class and we can print its attributes.
We can do something like:
```python
attr = vars(self)
msg = ', '.join("%s: %s" % item for item in attrs.items())
logger.debug("Created successfully a metadata class with attributes: ", msg)
```
Maybe we can add a log line printing which specification version we are supporting on import of `tuf/api/metadata.py`.

I imagine the logs will write messages using `debug` log levels so that only during debugging they will be seen.

**Current behavior**:
No logging in `tuf/api/metadata.py`.

**Expected behavior**:
Add minimal logging for debugging purposes.

**Comment by jku** [comment]
I don't think there is a way to answer a generic question like this. If debugging a specific case is difficult because of lack of logs, let's file a specific issue and then fix that specific issue

**Comment by MVrachev** [comment]
Agreed. Debugging can be added after we have more case studies and we realize the need for it in specific places.
