### ISSUE TITLE
Metadata API: Add TargetFile.from_data()

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1447]
This is a repository tooling use case but also useful for testing (#1444).

There should be a way to create TargetFile from a file object or bytes, so something like:

    TargetFile.from_data(data: Union[bytes, BinaryIO])
    # if needed could also have a helper:
    TargetFile.from_file(filepath: str)

Here the function would look at the data and calculate length and hashes for me, and would be useful when I want to update my targets object:

    # in tests
    targets.signed.targets["targetname"] = TargetFile.from_data(b"inline test content")

    # in production repository tools when new target is being added:
    targets.signed.targets["targetname"] = TargetFile.from_data(target_fileobject)

This is already clearly functionality that client will never need... but I think it's fine to add into metadata.py: let's just keep an eye on this and avoid adding too much repository-only functionality in files that will be shared by both

**Comment by jku** [comment]
We should have the same thing for MetaFile but: 
* there's version argument which requires access to the parsed Metadata object
* length and hashes are optional so we need to be able to not include them
* this means we might not need the `Union[bytes, BinaryIO]` argument at all

However we might want to see how this MetaFile API would really be used in the repository side before committing to a design here: there seem to be a balancing act between "making sure our MetaFile matches the metadata files we write" and "making the code not read/parse/write the same files multiple times" -- also currently a lot of metafiles only have a version and this case is already well covered by the constructor.

**Comment by avelichka** [comment]
I'd like to give it a try, pls :)
