### ISSUE TITLE
libtuf.py:  Staged metadata directory names with user-set suffixes

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#145]
libtuf.py supports staged metadata directories so that repository maintainers may work on the next release, or multiple, without affecting the "live" repository's metadata.  The new repository tool currently fixes the staged metadata directory to "metadata.staged", however, any suffix should be allowed and set by the repository maintainer(s) (e.g., "metadata.new_release", "metadata.next", etc.)

libtuf.py should allow user-set suffixes of staged metadata directories.

**Comment by trishankatdatadog** [comment]
Closing because stale
