### ISSUE TITLE
Metadata API: Missing key helper functions in Targets/Delegations

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1469]
Root class has functionality to add and remove keys for delegated metadata (`add_key()/remove_key()`) but the other delegator Targets does not. It should provide same/similar functionality.

Some options:
* Add `Targets.add_key(self, role: str, key: Key)` and `Targets.remove_key(self, role: str, keyid: str)`
* Handle the same in Delegations object

I think the former option makes sense so that the Targets API matches Root as well as possible (and Delegations remains mostly a Targets implementation detail).

**Comment by jku** [comment]
This could be fixed along with #1426 but also independently. In the latter case the implementation will be inefficient (as delegations.roles is just an array and lookups by rolename are not possible) but that's fine

**Comment by MVrachev** [comment]
I want to work on this and will assign myself.
I proposed a solution in the above pr #1537.
