### ISSUE TITLE
Refactor idea: type hinting

### ISSUE THREAD

**Issue by samuelgregorovic** [theupdateframework/tuf#1476]
While i was going through the project files, i took notice that there is literally no use of type annotations in definitions of methods/functions. Therefore, i want to discuss your opinion on refactoring the codebase -> adding type hinting (no changes to existing docstrings, just adding type hints).
What is your opinion on this? If you would approve this i could do it myself.

**Comment by trishankatdatadog** [comment]
The VMware team is hard at work on this! See some of the new ngclient PRs in particular 🙂 I'm sure they could use some help in this area.

**Comment by samuelgregorovic** [comment]
i will check that out. thanks

**Comment by jku** [comment]
@samuelgregorovic  I know the current work and plans are not visible as well as they should be -- sorry about that, we're trying to be better. We're very keen on static typing improvements and such (but with some caveats, see below).

In short:
* There's a refactoring/rewrite effort: see the tuf/api/ directory (and tuf/ngclient/ once #1408 merges). We're hoping to make this code "the TUF source code" and deprecate the old tools over time.
* the rest of the code is in what I'd describe as maintenance only mode -- nobody is against e.g. adding types there but the value is also a bit limited if no-one is working on that code...
* there's a lot to do with the new code base though -- especially on making it more visible and accessible: tutorials, publishing docs on readthedocs, example code. But also  development like implementing various repository side tools and improving the client

If you want to discuss ideas  and happen to use slack, we're on CNCF slack: https://cloud-native.slack.com/archives/C01GT17AC5D

**Comment by samuelgregorovic** [comment]
@jku thanks! will do
