### ISSUE TITLE
Docs: Enable continuous documentation build

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1482]
We want to be able to build and publish documentation (API docs for Metadata API and ngclient at least) as part of our continuous integration.

This bug is about choosing the tools, integrating with the TUF build system and filing any remaining issues as bugs.

Some notes:
* Sphinx seems the "obvious" choice as the docs build tool
* Using a service like ReadTheDocs also seems like a good choice (but integrating that can be a different issue)
* the default sphinx setup generates a lot of files/directories -- we might not want all of it (examples include Makefile and make.bat in root dir: these are not really required. Even the configuration file probably does not need to be in root dir)
* Need to decide what to do with the existing .rst and .md documentation in docs/ -- do we want to include some/all of that? We could start with just the API docs

I've done a quick test and sphinx mostly works:
* `pip install sphinx` (also `sphinx-rtd-theme` to see default RTD style)
* create a configuration file (see `sphinx-quickstart`)
* Add `extensions = ['sphinx.ext.napoleon']` to conf.py to get support for google style docstrings and `html_theme = 'sphinx_rtd_theme'` if using RTD theme
* `make html`

The only major issue I've seen is that `__init__()` docstring is not included (this seems to be a sphinx peculiarity: `autoclass_content = 'both'` might work)

**Comment by joshuagl** [comment]
I think we should start fresh with API docs for new code. As a separate item we can do a review of the material in docs/ to determine what's worth keeping and translating to the new docs format.

Some items in docs are out of date and some of them duplicate better maintained documentation elsewhere, I'm happy to own reviewing those and making recommendations.

**Comment by joshuagl** [comment]
See this in-toto PR for prior art https://github.com/in-toto/in-toto/pull/341 which publishes here https://in-toto.readthedocs.io/en/latest/
