### ISSUE TITLE
ngclient: remove URL normalization

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1483]
**Description of issue or feature request**:

Document that URL is expected to be is a percent encoded URL throughout the client code and remove URL string normalization _in lower level methods_ like the one in: 
https://github.com/theupdateframework/tuf/blob/745a8f7680c69ea290d48bc5a2066dd4ad9781d3/tuf/ngclient/_internal/download.py#L88

**Comment by joshuagl** [comment]
See also https://github.com/theupdateframework/tuf/issues/1077

**Comment by jku** [comment]
this is part of the "forming URLs from target paths" issue: My understanding after thinking about this a bit too much is that target paths are meant to be URL-encoded (percent encoded) to begin with -- or at least the client library cannot know what to encode/decode. The library should not encode or unencode but client (caller) can do that if they know what they are doing.

So:
* client library code should not unquote: it cannot know what is an intended encoding and what is not
* client library code should not replace any slashes with other slashes:  it cannot know which slashes are intended and which are not
* only exception to this would be a method that explicitly takes a local path and tries to turn that into a target path: My opinion is that we don't need a method like that: client (caller) can implement one if they think they do

**Comment by ivanayov** [comment]
Can I take this, please?
