### ISSUE TITLE
Test [de]serialization of metadata with more than one item in each container and zero items (where valid)

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1485]
**Description of issue or feature request**:

Testing, particularly [de]serialisation, should cover metadata containers with more than one item and, where it makes sense (per the specification), zero items.

**Current behavior**:

Testing only covers one item per container.

Ref https://github.com/theupdateframework/tuf/issues/1478

**Comment by MVrachev** [comment]
I started working on this and adding tests.
