### ISSUE TITLE
licensing issues with code from Thandy

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1491]
When TUF was created some Thandy (Tor project udpater) source code was used -- often not directly copied but there are clearly places that are derivative. TUF itself does not seem to have any derivative code left anymore but Securesystemslib clearly does. The cases I found in my review are:
* JSON functions in https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/formats.py#L618 (derivative of https://gitweb.torproject.org/thandy.git/tree/lib/thandy/formats.py)
* Many schemas implementations and documentation in https://github.com/secure-systemslab/securesystemslib/blob/master/securesystemslib/schema.py (derivative of https://gitweb.torproject.org/thandy.git/tree/lib/thandy/checkJson.py)

This is an issue because the BSD 3-clause used by Thandy is not quite compatible with the TUF/securesystemslib licenses (and because the copyright notices are not correct). I'm filing this issue in TUF because of the shared git history of TUF/securesystemslib.

I've contacted the original author who was kind enough to work within the Tor project (Thandy copyright owner) on this: they've agreed to do us a favor and relicense Thandy source code to also MIT + Apache 2.0 (as defined in [LICENSE](https://github.com/theupdateframework/tuf/blob/develop/LICENSE) and [LICENSE-MIT]( https://github.com/theupdateframework/tuf/blob/develop/LICENSE-MIT)). This should solve any licensing issues with Thandy code   as long as we make sure we make sure the appropriate copyright notices are included.

So plan is:
* summon @nmathewson  (original author of the code in question and Tor project contributor) to confirm that they are releasing Thandy source code (as in https://gitweb.torproject.org/thandy.git) under MIT and Apache-2.0 licenses
* File an issue in securesystemslib to fix copyright notices to mention The Tor Project, Inc. as a copyright holder ([link](https://github.com/secure-systems-lab/securesystemslib/issues/365))

Nick: Again many thanks for your help with this issue. If you can confirm the relicensing here, that would be great!

**Comment by nmathewson** [comment]
Hello. I hereby confirm that we at the Tor Project are okay with dual-licensing Thandy under "MIT OR Apache 2.0".  Cheers!

**Comment by joshuagl** [comment]
Much obliged to you and the Tor project, thanks @nmathewson !

**Comment by trishankatdatadog** [comment]
Fantastic work, thanks everyone 🙏🏽

**Comment by joshuagl** [comment]
We've merged a PR to securesystemslib which adds the Tor copyright to the relevant files: https://github.com/secure-systems-lab/securesystemslib/pull/366

Thank you everyone for the resolution here.
