### ISSUE TITLE
tests: reconsider encrypted private keys

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1492]
On my machine ~40% of the tests runtime (11seconds out of 27 seconds) seems to be spent on decrypting private keys. This seems unproductive.

We should not encrypt the keys except for cases that may be actually testing key en/decryption

**Comment by jku** [comment]
This is not critical to fix, but would make tests a lot snappier.

Steps, roughly:
* Make the "generic" test keys (in tests/repository_data/keystore/) that are used in all tests **not** encrypted
* make sure all test code that loads those private keys doesn't try to decrypt them (I think dropping the password argument will do that in all cases?)
* there is specific functionality in at least repository_lib.py that supports passwords: we should still have tests for en/decryption there: `test_import_ed25519_privatekey_from_file()` is a good example of a test that already works but e.g. `test_import_rsa_privatekey_from_file()` currently uses the generic keys for the same and would need to be modified so it e.g. creates an encrypted key during the test. 

Results should be easily visible in aggregate_tests.py total runtime -- I'd expect a 30% reduction should be possible. Currently the tests call `decrypt_key()` 258 times: I think we should be able to get that down to a handful of calls.

**Comment by NabeelShahid7** [comment]
I would like to work on this enhancement.. Can I please get some kind of an approval from any contributor of this repository?
About Me:
I am a student currently pursuing his Post Graduate in Computer Science. I have been assigned a course component which involves contributing to any open source project. I am liking this repository and would like to start from scratch to try getting this issue fixed. @joshuagl @jku

**Comment by jku** [comment]
welcome! I think the tests have changed quite a bit since I filed this: they're definitely much faster now, we probably don't use encrypted keys in as many tests any more... 

Feel free to investigate and check how much that still happens though. Let me now if you need help.

**Comment by NabeelShahid7** [comment]
Thank you. @jku

**Comment by jku** [comment]
I think this might not be massively useful in this project anymore -- with all of the test improvements in the past 18 months we're now down to < 2 seconds per test suite run on a linux laptop. This is acceptable.

If you have test improvements coming up, they are still very welcome but I'll close this issue: the described problem does not seem to be a major problem anymore.

https://github.com/secure-systems-lab/securesystemslib test suite however probably still has this issue: the suite runtime there is 42seconds. Any improvements there would be useful.
