### ISSUE TITLE
ngclient Updater: write tests to handling coverage report 

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1499]
**Description of issue or feature request**:
This is the minimal amount of testing we should have to enable coverage for the ngclient updater and the first step of resolving #1462 for the Updater.
When resolving the missing lines reported by `coverage` we will decide if we want to handle all of them
or there is a sense of leaving some of them.

**Comment by MVrachev** [comment]
We should remember to test downloading files with filenames `HASH.FILENAME.EXT` or when consistent_snapshot is True.

**Comment by MVrachev** [comment]
The current coverage all percentage reported for `tuf/api/ngclient/updater.py` is 77 %.

**Comment by joshuagl** [comment]
From @MVrachev in https://github.com/theupdateframework/tuf/pull/1463#pullrequestreview-715850729

> there are a couple of code paths not tested yet (according to coverage all):
> 
> delegation role with `terminating` option turn on
> test when a target is not found
> reaching the max limit of visiting delegations, but there are more delegations left
> Additionally, we never test `DelegatedRole.is_in_trusted_paths()` when `path_hash_prefixes` is set and thus never actually test calculating the hashes.

**Comment by jku** [comment]
also 
* we're probably not testing cycle prevention in _preorder_depth_first_walk(): this is the `if (role_name, parent_role) in visited_role_names` branch
* test that terminating actually prevents backtracking to other roles (but does not prevent e.g. finding an earlier sibling role)

**Comment by sechkova** [comment]
Up to now the coverage has been/will be improved by: 
- https://github.com/theupdateframework/tuf/pull/1477
- https://github.com/theupdateframework/tuf/pull/1553
-  https://github.com/theupdateframework/tuf/pull/1522 
- https://github.com/theupdateframework/tuf/pull/1519

I am assigning this to myself to finish the work and include ngclient to the coverage report.
