### ISSUE TITLE
improve "generic" Metadata module documentation

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1504]
We should improve the Metadata module documentation just a bit so that it explains what the API is. 
I don’t think it needs a lot. But something like:
* Defines an interface to single metadata role/file
* does not have concepts like “repository” or “trusted collection of metadata”
* Aims to provide safe de/serialization, **and** a safe API for accessing/modifying the data
* Does not implement client update workflows or repository-side logic, but offers a solid base for components that do

**Comment by MVrachev** [comment]
I can work on this one and will self-assign myself.
If somebody else is already working on this issue please let me know.
