### ISSUE TITLE
ngclient: return loaded metadata from Updater._load_targets

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1507]
**Description of issue or feature request**:
During the traversal of the delegations tree, each targets metadata file is first loaded/downloaded and then "visited".
It would be convenient if `Updater._load_targets` directly returns the loaded metadata to avoid lookup on the next line.

**Current behavior:**
```python
            # The metadata for 'role_name' must be downloaded/updated before
            # its targets, delegations, and child roles can be inspected.
            self._load_targets(role_name, parent_role)
            role_metadata: Targets = self._trusted_set[role_name].signed
```

**Expected behavior:**
```python
role_metadata = self._load_targets(role_name, parent_role)
```

**Comment by jku** [comment]
This should go one level deeper. right? TrustedMetadataSet should return the new trusted Metadata on successful calls to all `update_*()` functions?

This doesn't make the task any more complex but means it could be done in two bits: first add the TrustedMetadataSet changes, then use them in `Updater._load_targets()`

**Comment by ivanayov** [comment]
Can I take this, please?
