### ISSUE TITLE
docs: remove docs/ROADMAP.md (or update it)

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1525]
I'm updating some documentation and noticed our installation document refers to ROADMAP.md.

This file is not updated and does not seem to have a lot of useful information: I suggest we remove it and links to it.

**Comment by trishankatdatadog** [comment]
No, I think we should keep it. Let's make a process to update the roadmap once a quarter/year? We can talk about it in the next community meeting. @mnm678

**Comment by jku** [comment]
I'm going to push back on this on principle. We have too much documentation (in comparison to maintenance resources). 

In this case, there are many ways to document future plans, a text file is one possibility. Someone should show that ROADMAP.md is useful for the project and is being maintained, then I'm all for keeping it.

**Comment by trishankatdatadog** [comment]
Let's discuss this at the next meeting.
