### ISSUE TITLE
ngclient: persist metadata in a safer way

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1526]
tuf/ngclient/updater.py: `Updater._persist_metadata()`:

        with open(os.path.join(self._dir, f"{rolename}.json"), "wb") as f:
            f.write(data)

this is not as safe as it should be (as file could be corrupted midway through). This should work:
* write content to tempfile
* use `sslib_util.persist_temp_file()` to move tempfile to correct filepath

**Comment by suvadityamuk** [comment]
Hey. I have prepared a fix to this. Should I put up a pull request on this? It's my first open-source contribution, so any inputs will be much appreciated.

**Comment by jku** [comment]
After Suvaditya did the PR I decided to double check the persist_temp_file() implementation: turns out it does not make sure the write is atomic.

So I believe we need to handle this a bit more manually: http://stupidpythonideas.blogspot.com/2014/07/getting-atomic-writes-right.html ("The Solution" chapter) documents a correct way to do this in python:
* use NamedTemporaryFile to generate a safe temp file name (the method in current PR is unsafe because it might overwrite an existing file)
* use the dir argument to make sure the temp file is in same filesystem as the final file (otherwise replace can't be atomic)
* use delete=False argument so NamedTemporaryFile doesn't try to delete the temp file (because we want to move it)
* no need to write one line at a time like the blog example though: single write call is fine

That implementation will leave the temp file in place if the final replace fails. I think that's an acceptable side effect for something that should not really happen -- so IMO it's not necessary to handle that case

**Comment by suvadityamuk** [comment]
Understood, I'll make the changes accordingly. Could you possibly assign this task to me?

**Comment by suvadityamuk** [comment]
Okay, so the changes are done and I have tested it, all seems correct. What do I do about that commit problem now? Do I copy that email-address that it is expecting and make the commit message accordingly or what?

**Comment by suvadityamuk** [comment]
Sorry for the PR mess here.

**Comment by suvadityamuk** [comment]
Okay, I do not understand what is going wrong. All tests were passing on my local computer using `python3 aggregate_tests.py` as well as `python3 test_updater_ng.py`.
Could you please let me know?

**Comment by suvadityamuk** [comment]
I closed the last PR I made because it failed the new tests you added. I am so 
embarrassed and sorry for the mess of PRs made, but I'll make sure that the next PR passes all the tests, along with the new ones as well.
