### ISSUE TITLE
root version does not increase when top-level keys are updated

### ISSUE THREAD

**Issue by hosseinsia** [theupdateframework/tuf#1538]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
I followed the steps described here https://github.com/theupdateframework/tuf/blob/develop/docs/CLI.md#correcting-a-key  to revoke a root key and add a new key. Upon completion, the keys update but the version for root.json stays the same. 

**Current behavior**:

The [increment_version_number](https://github.com/theupdateframework/tuf/blob/e242a750d4d17e7649b65333ce8e073c7d7ae839/tuf/scripts/repo.py#L534) is always set to False when we add a key. 

**Expected behavior**:

For root key update, the version of the root.json should be increased. Therefore, the `increment_version_number` should be set to True.

For change in the non-root top-level keys, this behavior is expected:
* change in the shanpshot -> increase version of the root.json and shanshot.json
* change in the timestamp -> increase version of the root.json, shanshot.json, and timestamp.
* change in the target -> increase version of the root.json, shanshot.json, timestamp, and target.

**Comment by jku** [comment]
Closing this as the referenced docs and the tool are no longer included in python-tuf.

Some repository tooling work is planned but there are no replacements as of now (except for what's shown in the repo examples)
