### ISSUE TITLE
Rename to python-tuf

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1555]
I'd like to rename the repository from tuf to python-tuf, fortunately GitHub will redirect all existing users (git and web URLs): https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/renaming-a-repository

We're increasingly referring to this implementation as python-tuf, we also have its sibling project go-tuf. TUF itself is a [specification](https://github.com/theupdateframework/specification), plus [standardisation process](https://github.com/theupdateframework/taps), plus [reference implementation](https://github.com/theupdateframework/tuf)([s](https://github.com/theupdateframework/go-tuf)?) – let's make it clearer what _this_ repository is.

If I can get an ACK from active maintainers and the consensus builder, I'll do the rename on GitHub.
cc @JustinCappos @mnm678 @trishankatdatadog @jku @sechkova 

We should figure out what, if anything, does a rename mean for our Python packaging.

**Comment by JustinCappos** [comment]
I support this change.

**Comment by mnm678** [comment]
+1

On the git side the re-name is usually pretty seamless, but we may have to update some of the hard-coded instances in the packaging, for example [here](https://github.com/theupdateframework/tuf/blob/develop/setup.py#L80)

**Comment by trishankatdatadog** [comment]
+100

**Comment by jku** [comment]
+1.

The redirects should work, but obviously lets try to fix all the links we can after we do the rename -- the PR for the changes in this repo could get reviewed even before the project rename so it's ready to go.

> We should figure out what, if anything, does a rename mean for our Python packaging.

I would hope 'tuf' is still a good name for the package. Package name changes are just a pain and 'tuf' seems like a great name there -- no chance of confusion.

**Comment by sechkova** [comment]
+1 for the rename and +1 for keeping the package name.

**Comment by joshuagl** [comment]
Thanks all, I have prepared for the rename by creating PRs against the website (https://github.com/theupdateframework/theupdateframework.io/pull/25), TAPs (https://github.com/theupdateframework/taps/pull/142), and python-tuf (https://github.com/theupdateframework/tuf/pull/1557) repositories.
