### ISSUE TITLE
Improve error messages and adjust logger messages/levels

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#156]
@JustinCappos reports:

Our errors / output of TUF is our most visible interface to the end user.   Be sure that you think hard about presenting information in the clearest possible way.

This should be a point of emphasis for code review within the project moving forward.   Remember to think about "shoulder-surfing" what our users will see!

**Comment by lukpueh** [comment]
Closing as too broad. Will revise, if we get more concrete complaints about specific error/log messages.
