### ISSUE TITLE
Scope of Metadata Management (MM) and Third Party MM projects

### ISSUE THREAD

**Issue by knowlengr** [theupdateframework/tuf#1560]
I have been only casually following the metadata-related threads. For my education, 
1. Is the metadata here fully extensible; e.g., I can process an substantial (but not limitless) amount of metadata that is domain-specific associated with the software component?  Or we talking about a narrower version of metadata, such as timestamps or last-user-update?
2. Are there any issues (as in Github "issues") discussing possible connections to metadata management / server projects in CNCF (or perhaps Apache, e.g., Apache Hop)?  The existing use cases do not appear to be extensible enough to cover flow of domain metadata.  As an example, consider the code/data lineage approach [discussed here](https://www.youtube.com/watch?v=qieBr3Qj1yA). 

**Description of issue or feature request**:
Feature request, or discussion? I think.  Unclear how extensible is the current metadata semantics

**Current behavior**:
Unsure; appears to implement an OS / version control notion of metadata.

**Expected behavior**:
N/A

**Comment by trishankatdatadog** [comment]
Hi Mark,

On Wed, Sep 1, 2021 at 11:55 AM Mark Underwood ***@***.***>
wrote:

>
>    1. Is the metadata here fully extensible; e.g., I can process an
>    substantial (but not limitless) amount of metadata that is domain-specific
>    associated with the software component? Or we talking about a narrower
>    version of metadata, such as timestamps or last-user-update?
>
>
Yes, see the custom
<https://theupdateframework.github.io/specification/v1.0.20/index.html#custom>
targets metadata, which is used
<https://uptane.github.io/deployment-considerations/customizations.html> in
Uptane (a multi-repo variant of TUF used in automotive/cloud
dependency-resolver contexts) to associate arbitrary metadata with
artifacts.

>
>    1. Are there any issues (as in Github "issues") discussing possible
>    connections to metadata management / server projects in CNCF (or perhaps
>    Apache, e.g., Apache Hop)? The existing use cases do not appear to be
>    extensible enough to cover flow of domain metadata. As an example, consider
>    the code/data lineage approach discussed here
>    <https://www.youtube.com/watch?v=qieBr3Qj1yA>.
>
>
I don't have sufficient background to comment here, sorry.

>

**Comment by jku** [comment]
The TUF metadata design is extensible as trishank said. Whether it makes sense to include substantial amounts of metadata is another question: The alternative design for specific update systems is to consider the extended metadata as just another form of target data. In practice:
* store the extended metadata in whatever form is best for your application
* insert the extended metadata files as targets into your TUF repository
* when client is interested in a target, it first uses TUF to download the (small) extended metadata file
* based on the extended metadata, client can decide if it wants to download the actual target

This leads to a few extra connections but means you don't have to entangle your extended metadata design with TUF design. it's quite possible that the client does not even know which actual target it needs before downloading some extended metadata: This is the design that pypi.org and Warehouse are going with: the extended metadata is not for a specific target but for a whole project, and is used by the client to choose which release of the project it is interested in.

Now, I think _extended metadata_ is a discussion worth having and possibly there is a document worth writing here... but I'm trying to think if there is a better place than python-tuf issue tracker to do that in?

The one issue that I think might belong in the python-tuf issue tracker is _documenting access to extended metadata (that is embedded in TUF metadata) using e.g. the  ngclient updater implementation_:  `get_one_valid_targetinfo()` returns a `TargetFile` which corresponds to elements in https://theupdateframework.github.io/specification/latest/#targets-obj-targets, so accessing extended metadata is as easy:

```python
info = updater.get_one_valid_targetinfo("mytargetname")
my_custom_metadata_handler(info.custom)
``` 

We seem to lack proper documentation for TargetFile.custom: https://theupdateframework.readthedocs.io/en/latest/api/tuf.api.metadata.html#tuf.api.metadata.TargetFile.custom

(note that "custom" is a special case of extended metadata the spec authors have _named_: extended metadata can have any attribute name it wants ... but then it runs the risk of clashing with future changes in the TUF spec: `TargetFile.custom` is uniquely safe from that risk)

**Comment by jku** [comment]
The docs issue with "TargetFile.custom" is fixed in that it's at least mentioned in the docs.

I'll close this issue:
* metadata is extensible in TUF and in python-tuf Metadata API
* the full extensibility is not exposed via ngclient (as it's a simple API) but `TargetFile.custom` as a special case is
* As I mentioned in the comment, large extensions likely make sense as targetfiles
