### ISSUE TITLE
ngclient: should clean temp file if write fails

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1575]
This is assuming #1574 is merged: We should clean temp file in `Updater._persist_metadata()` manually if
* write fails but file was still created (disk could be full?)
* write succeeds but replace fails (can't imagine what could lead to this but probably something can...)

To re-iterate, we don't use Tempfiles automatic cleaning because in the normal case we want to move that file (and we can't both move it and let tempfile clean it).

I think something like this (completely untested code):
```python
try:
    # all current code  (tempfile creation, write, os.replace) here
except OSError as e:
    # delete tempfile if we managed to create one, then let the exception happen
    if tempfile:
        try:
            os.remove(tempfile.name)
        except FileNotFoundError:
            pass
    raise e
```
no idea how to easily test this code though

**Comment by jku** [comment]
> no idea how to easily test this code though

Would be nice if there was a way to test without mocks but mocking os.replace() would definitely work and be fairly easy

**Comment by MVrachev** [comment]
I can take this one.

**Comment by MVrachev** [comment]
I think it's not obvious how can we test the case when `os.write` fails.
How can we simulate full storage or other situation that could cause an exception?

**Comment by jku** [comment]
> I think it's not obvious how can we test the case when os.write fails.

You can't test this properly/comprehensively in an OS generic way (on many linuxes you could use "/dev/full" as the filename to trigger OSError with ENOSPC... but that's just one failure on one OS)

I'd say just figure out a single mock (either os.write or or.replace) that raises an OSError so we at least run the exception code once in the tests.
