### ISSUE TITLE
tests: Start linting tests

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1582]
I believe we should enable linting (`tox -e lint`) for new test files (maybe even for some recent additions). Possibly some exceptions are needed but in general I think the tests would be better if they were linted.

Good start for this would be test_updater_with_simulator.py and repository_simulator.py: it's new code and files are small so the changes are easy -- the real job is figuring out how to select what to lint... Possible options:
* separate directory for legacy (unlinted) tests?
* define list of linted files in tox.ini / setup.cfg ? (I don't like this one as it means default for new files is no lint)
* define list of files excluded from lint in tox.ini & setup.cfg ?
* some other strategy?

**Comment by joshuagl** [comment]
Splitting tests across multiple directories _may_ make sense, but I think the right combination of simple and not prone to error is a list of files excluded from lint? That way, new test files are linted and there's no ambiguity about where to place new tests.

Also, the no-lint list gets shorter as we replace/remove existing tests.

**Comment by jku** [comment]
I notice I did not explicitly state this: we currently have lint files/directories listed in multiple places in tox.ini and then in setup.cfg for static type checking with mypy

**Comment by MVrachev** [comment]
I think I will experiment by renaming all old test files with `<name>_old.py` and experiment with exclusion rules.

**Comment by sechkova** [comment]
> I think I will experiment by renaming all old test files with `<name>_old.py` and experiment with exclusion rules.

Can we use a prefix instead of a suffix so the files appear sorted in a way?

**Comment by MVrachev** [comment]
> > I think I will experiment by renaming all old test files with `<name>_old.py` and experiment with exclusion rules.
> 
> Can we use a prefix instead of a suffix so the files appear sorted in a way?

I thought about adding a suffix instead of a prefix as the filenames will be easier to read.
Although as they are test files for the old legacy code maybe we want to see them grouped and that will make the other files more visible.
Do the others have an opinion?

**Comment by jku** [comment]
I expect prefixes would make more sense, if files need to be mass-renamed

**Comment by MVrachev** [comment]
Another reasonable solution seems to move the old files in a separate folder, but if we move them won't we lose the git history?

**Comment by MVrachev** [comment]
I read the GIT FAQ on this matter https://git.wiki.kernel.org/index.php/GitFaq#Why_does_Git_not_.22track.22_renames.3F and found out that both renames and file relocations will cause the git history to be lost.
That's why I researched for another option that won't change the titles or move the test files.
I think I have some progress with `isort` and `black`, but they require to hardcode each of the test files we are going to exclude. This makes sense when we consider they don't have a distinguished regex we can exclude.
Even though it's a big list of around 30 files, I think this solution is fine as this list will only contain files testing the old code meaning the list will have a static content.

**Comment by MVrachev** [comment]
I will remove this issue from Sprint 11 for now as it contains multiple action items each of which requires a review.

**Comment by MVrachev** [comment]
TODO items left to close this issue:
- [x] address `pylint` and `mypy` warnings | #1657
- [x] add configuration to actually start linting the tests
