### ISSUE TITLE
Develop a process for keeping `metadata.SPECIFICATION_VERSION` up-to-date

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1598]
**Description of issue or feature request**:

`tuf.api.metadata.SPECIFICATION_VERSION` is currently 1.0.19, latest TUF spec is 1.0.25. The larger these differences become, the more of a chore it is to ensure we are fully compliant with new specification versions.

Let's develop a process for ensuring we frequently assess new spec versions, make changes to python-tuf where appropriate, and keep `tuf.api.metadata.SPECIFICATION_VERSION` up-to-date.

I think the ideal would be some GitHub Actions automation that monitors the specification releases and files issues to trigger a manual comparison, but in the short-term we could simply add a step to the release checklist?

**Current behavior**:

* Updating `tuf.api.metadata.SPECIFICATION_VERSION` requires remembering to check spec releases and reviewing all changes in bulk
* `tuf.api.metadata.SPECIFICATION_VERSION` is several releases behind the specification

**Expected behavior**:

* Monitoring the spec and making appropriate changes to python-tuf is a standard part of the development process
* `tuf.api.metadata.SPECIFICATION_VERSION` is up-to-date with the specification

**Comment by jku** [comment]
rough code to compare latest spec release tag to metadata api supported version number:

https://github.com/jku/python-tuf/blob/ci-check-spec-version/.github/workflows/spec-version.yml

something like this combined with code for "open new issue" from securesystemslib check-upstream-ed25519.yml should work

I'm not working on this right now: if someone wants to push this forward be my guest
