### ISSUE TITLE
read(size) method in tuf.util.TempFile does not read anything

### ISSUE THREAD

**Issue by pawanrao** [theupdateframework/tuf#160]
We found the following issue with the example code below: 

``` python
from tuf import download

doc = download.safe_download("http://0install.net/2006/interfaces/0publish",11769)
data = doc.read(256)
print(data)
```

data is empty but if `data=doc.read()` it gets the entire file correctly.

**Comment by joshuagl** [comment]
`tuf.util.Tempfile` moved to `securesystemslib.util.TempFile` so I opened a similar issue there:
secure-systems-lab/securesystemslib#180

Should probably close this issue.

**Comment by SantiagoTorres** [comment]
Thanks for the help @joshuagl !

**Comment by trishankatdatadog** [comment]
Unrelated, but could someone make me a maintainer of TUF, if everyone agrees? Kinda hard to help out with issues if I can otherwise. Thanks in advance!

**Comment by lukpueh** [comment]
I'm all for it @trishankatdatadog.  Please make a PR against [MAINTAINERS.txt](https://github.com/theupdateframework/tuf/blob/develop/docs/MAINTAINERS.txt). I'll merge, assuming that the consensus builder (@JustinCappos) agrees... ;)

**Comment by JustinCappos** [comment]
Yes, absolutely!
