### ISSUE TITLE
Metadata API: Improve docstrings language

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1600]
Let's fix some docstrings in metadata.py: some of them document internal details or just repeat the name of the attribute/argument in a way that's not useful for reader:
* Assume reader is not going to read the source code 
* If it's not obvious, explain what argument/attribute is for -- why is it exposed in API?

I'd like to get at least this common line fixed:

> **unrecognized fields**: Dictionary of all unrecognized fields.

This does not explain what they are or why they are exposed in the API.

**Comment by lukpueh** [comment]
Some related thoughts with regards to consistency of docs that might be addressed here:
- Don't use different aliases for the same docs section, e.g. "Args" vs. "Arguments"
- Quote (`'` vs. `"` vs. ``` `` ```) or don't quote all proper names, e.g. args, return values, class names, etc.
- Start all args/raises/returns oneliners with definite, indefinite or no article.
- As @jku says, don't state the obvious, more specifically reduce redundancy in variable names, typing information, method summary and args/raises/returns descriptions.

**Comment by lukpueh** [comment]
> Quote (' vs. " vs. ``) or don't quote all proper names, e.g. args, return values, class names, etc.

Just saw that @jku already has a ticket for this. I say we try standardise to double backtick and see if it looks good in source code and on RTD.

**Comment by ivanayov** [comment]
Arguments left to explain after #1815:
```
signer: ``securesystemslib.signer.Signer`` implementation
```
and some still questionable:
```
data: Metadata content.
...
filename: Path to write the file to.
etc.
```
plus clarify `json/dict representation`

**Comment by jku** [comment]
Further improvements are a good idea but I think I'd like to close this issue -- or alternatively remove the blocker label: I think the docs look good enough for a release :shrug: ?
