### ISSUE TITLE
repository design: survey existing implementation

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1612]
Let's starts #1136 with a "competitor analysis": survey existing TUF repository implementations from a adopter/integrator perspective:
* Take a look at existing implementations, document the APIs they provide and use cases they seem to cater for:
  * python-tuf repository_tool / repository_lib
  * current Warehouse integration branch
  * [go-tuf](https://github.com/theupdateframework/go-tuf/)
  * [tough](https://github.com/awslabs/tough/)
  * [repository-editor-for-tuf](https://github.com/vmware-labs/repository-editor-for-tuf/)
  * others?

As bonus tasks:
* Try to define the spectrum of potential downstreams (integration into a webservice vs stand-alone tool, files vs postgres, etc)
* Maybe start defining the potential supported use cases (snapshot update, repository initialization, etc)

**Comment by joshuagl** [comment]
The current warehouse integration branch is, I believe, https://github.com/pypa/warehouse/pull/7488

Some potential use cases / areas:

- initial repository setup
- key management (e.g. safe key rotations)
- delegation management
- developer actions: adding targets at least (anything else?)
- snapshot update
- timestamp update
- ensuring repository validity (this comes up in several other use cases)

**Comment by jku** [comment]
Documenting a few items from first discussion:
* Jussi: a lot of the code we will look at may be designed with command line interfaces in mind: this probably won't prevent the components from being useful in e.g. Warehouse-like integrations but let's keep the possible bias in mind
* Lukas: a lot of the design in repository_lib/tool is sound, it's just the implementation that is the issue
* Let's try to look at a few code bases, document
  * roughly what API (or tools) are provided for repository side
  * what kind of components are used to do that
* Lukas documents python-tuf, Jussi looks at tough and also writes something about repository-editor-for-tuf
* Meet again in a week, compare notes: see if it makes sense to write a document that collects the info in same style and form in one place

**Comment by joshuagl** [comment]
This diagram _may_ be useful for the repository_lib/tool survey [repository_tool-diagram.png](https://github.com/theupdateframework/python-tuf/blob/develop/docs/images/repository_tool-diagram.png)

**Comment by lukpueh** [comment]
*Updated on 2021-10-28 to add link to warehouse review*

-----

Just discussed existing implementations with @jku and @rdimitrov (*thanks!*).

Here are links to our reviews:
- [python-tuf](https://docs.google.com/document/d/1zk41LSC_wsEEOq9TQSPR4h_0w2dnz0f9Zx_FjESm1qQ)
- [repository-editor-for-tuf](https://docs.google.com/document/d/1IIvr6_54NC02mcfpkzKYA_Zwt-06jW4fkjHVhVrYZf8/edit#heading=h.yjb9nkwgv5op)
- [go-tuf and php-tuf](https://docs.google.com/document/d/1vqB-KDG8GGBQUkwX8VHlS4FOmKjgDYGfzMDfcGLtQXE/edit)
- [AWS Tough](https://docs.google.com/document/d/1zFl4em6PZUrgnjiy4VnpOh918x_BCPozoc8d4KuVcYo/edit)
- [Warehouse](https://docs.google.com/document/d/16kM9SruqTcHXrTHeQDf-F6-qz3xwBzRJIVTqdudCEu0)


And here are some randomly ordered reoccurring issues from our discussion:
- state keeping in memory and on disk
- (fail late) validation of repository consistency
- library vs. REPL vs. CLI use
- metdata update interdependencies (see e.g. [#958](https://github.com/theupdateframework/python-tuf/issues/958#issuecomment-553830755))
- being able to work on parts of a repository without (read/write/sign) access to all metadata or target files or keys
- TUF spec has little instructions for repository side activities

The repository tool re-design will be tracked in #1136 and further brain storming may take place in  [this TUF (Re-)Design Document](https://docs.google.com/document/d/13cY0MD3uzwFYGnj_GkPS_rwvDEzzNpDu6cteyeYP6fY/edit#heading=h.tkzy2v7sozns).

**Comment by jku** [comment]
WRT review: the big missing part is Warehouse review, no-one's yet had a good look at it.

**Comment by lukpueh** [comment]
Just updated my [comment above](https://github.com/theupdateframework/python-tuf/issues/1612#issuecomment-950744368) to add a link to the Warehouse review.

**Comment by lukpueh** [comment]
Closing with https://github.com/theupdateframework/python-tuf/issues/1136#issuecomment-953758281
