### ISSUE TITLE
New implementation: do we need a separate DEFAULT_HASH_ALGORITHM config option in TUF?

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1613]
**Description of issue or feature request**:
In Securesystemslib there is the `securesystemslib.hash. DEFAULT_HASH_ALGORITHM`  configuration option which now is set to "sha256".
The question is whether we need an option like this in TUF rather than relying on Securesystemslib?
If `securesystemslib.hash. DEFAULT_HASH_ALGORITHM` is changed tomorrow how would this affect us? 

**Current behavior**:
Relly on `securesystemslib.hash. DEFAULT_HASH_ALGORITHM` config option.

**Expected behavior**:
To be decided.

_Based on Joshua Lock's comment https://github.com/theupdateframework/python-tuf/pull/1605#discussion_r727103580._

**Comment by jku** [comment]
I see no need for this. Either we remove the one use of DEFAULT_HASH_ALGORITHM (and force repository implementation to specify algorithms when creating a new TargetFile) or we continue  trusting Securesystemslib to handle our crypto stuff.

**Comment by jku** [comment]
I'm closing: if there are differing opinions (vs the previous comment) feel free to re-open
