### ISSUE TITLE
Test utils fail on every OS when using Python version 3.10

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1614]
**Description of issue or feature request**:
I tried adding support for Python version 3.10 in pr #1610, but there were CI problems with our test utilities when using every platform we are testing against - Windows, Ubuntu and MacOS: 
https://github.com/theupdateframework/python-tuf/pull/1610/checks?check_run_id=3861875262

**Current behavior**:
CI fails when using our test utilities with Python version 3.10.

**Expected behavior**:
Resolve the above issue and add support for Python version 3.10.

**Comment by joshuagl** [comment]
Note to whomever merges this, when we add new Python versions to the test matrix we need to choose whether to update our branch protection rules.

**Comment by jku** [comment]
> Note to whomever merges this, when we add new Python versions to the test matrix we need to choose whether to update our branch protection rules.

What was this about? Can't quite connect the two...

**Comment by joshuagl** [comment]
Apologies for the drive-by comment.

- Our [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches) prevent us merging unless certain checks have passed. 
- When we add a new Python version to the Actions workflow, that creates a new set of checks of the form "Tests ($PY_VER, $HOST_OS-latest, py)". 
- Currently required checks includes checks of the form "Tests ($PY_VER, $HOST_OS-latest, py)" for each of PY_VER=[3.6, 3.7, 3.8, 3.9].
- New checks introduced by adding a new Python version are not automatically included in our branch protection rules and must be added to the list of required checks manually.

Therefore, when we add a new Python version to the workflow we need to decide whether we want to require checks pass before merging and, if so, update branch protection rules to make that happen.
