### ISSUE TITLE
RepositorySimulator: add support for serving invalid metadata

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1615]
**Description of issue or feature request**:

_update: One scenario of invalid metadata remains, serving a snapshot whose version does not match the one in timestamp.snapshot_meta and targets whose version does not match the one in snapshot.meta respectively (see discussion below)._

In many test scenarios there is a need of serving various forms of invalid metadata: 
- unsigned metadata: missing signatures, threshold of signatures is not met, signed with incorrect keys
- tampered metadata: snapshot/targets hash not matching
- expired metadata

**Current behavior**:
All metadata is served signed, hard to tweak signatures, hard to tweak hashes.

**Expected behavior**:
Add options and/or methods to RepositorySimulator facilitating serving invalid metadata.

**Comment by jku** [comment]
> * unsigned metadata: missing signatures, threshold of signatures is not met, signed with incorrect keys
> * tampered metadata: snapshot/targets hash not matching
> * expired metadata

let's talk about these: I think these are mostly already doable -- but it's true the methods to do so might not be very accessible.

* unsigned metadata: changing signers without changing metadata keys will lead to signature issues
* invalid metadata (meta dict): this should be easy, just modify meta dict manually after update_snapshot()
* invalid metadata (target hashes): this might require adding the target, then modifying the metadata...
* expired metadata: modifying expiry should be easy

**Comment by sechkova** [comment]
Thanks for expanding on the bullets, I managed to apply all these successfully in #1636.

Only one issue remained, partially related to consistent snapshot. Since `RepositorySimulator` works always with consistent snapshot enabled this forces the client to look for the snapshot version written in timestamp, which leads to "Unknown snapshot version" when trying to serve a snapshot with a version mismatching the one in `timestamp.snapshot_meta.`
Here is an example:
https://github.com/theupdateframework/python-tuf/blob/6565365aab563f5662cba05ea34fba14184d00ab/tests/test_updater_top_level_update.py#L280

The only idea I got is to test this when `RepositorySimulator` supports consistent_snapshot turned off. Any better ideas?

I plan to close this issue and open another one for implementing the above.

**Comment by jku** [comment]
> The only idea I got is to test this when `RepositorySimulator` supports consistent_snapshot turned off. Any better ideas?

yeah I see. The simulator does not in any way "publish" non-root metadata so when a request is made it just checks if the requested version matches current metadata... 

I guess one option is to just not check for the version match in the simulator: instead always return the current metadata, whatever version is requested. I have no idea if this would complicate some other tests, but I remember originally adding the check only to test that the simulator works... maybe it isn't needed?

**Comment by sechkova** [comment]
I will add these notes to #1637 to test if removing the check causes any problems with consistent/non-consistent snapshot. I did actually run my tests with commenting out the check you mention and nothing wrong happened ...

**Comment by jku** [comment]
Is this still an issue with the changes in #1636?

**Comment by sechkova** [comment]
> Is this still an issue with the changes in #1636?

No, the last item from this issue was fixed with d66c3baf2753523c600ee7f6aca6371e671d0c12. Closing.
