### ISSUE TITLE
TUF interposition maintains state of available roles

### ISSUE THREAD

**Issue by pawanrao** [theupdateframework/tuf#162]
if url.endswith("xml"):
            if sys.version_info[0] > 2:
                #Python 2
                try:
                    doc = urllib3.urlopen(url)
                except Exception,e:
                    #raise e
                    try:
                        sleep(60)
                        doc = urllib3.urlopen(url)
                    except Exception, e:
                        raise(e)

If the targets.txt file is unavailable during the first call to urlopen() TUF returns 'unknown' role error. However if the targets.txt is restored before the second call to urlopen(),TUF still returns 'unknown' role error.
This is not expected behavior.

**Comment by lukpueh** [comment]
`tuf.interposition` was removed in https://github.com/theupdateframework/tuf/pull/537. Closing.
