### ISSUE TITLE
Metadata API: Consider removing 'update()' methods

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1627]
*[edited on 12/20/2021: Mention ".json" bias]*
*[edited on 11/10/2021: Point to #1230]*

**Description of issue or feature request**:

The Metadata API classes for top-level roles Targets, Timestamp and Snapshot each have an `update` method. They have been criticised in several places (https://github.com/theupdateframework/python-tuf/pull/1193#discussion_r514572393 pp, https://github.com/theupdateframework/python-tuf/pull/1223#discussion_r532537746 pp, https://github.com/theupdateframework/python-tuf/pull/1620#issuecomment-947556006).

More specifically the following doubts have been expressed:

- `update` is an ambiguous name, e.g. does it stand for *"__update__ some attributes of object"*  or for *"update object in the course of a repository __update__"*? - https://github.com/theupdateframework/python-tuf/pull/1223#discussion_r532665409

- `update` is unspecific about which attributes are updated - #1230 

- Is `update` a repository action only and should thus be in a repository controller and not on the Metadata API, which is also used by the client? - https://github.com/theupdateframework/python-tuf/issues/1134

- [e.g. `Targets.update()`] is literally a one-liner that modifies a public dict attribute: we could document doing that instead and have a smaller API surface. - https://github.com/theupdateframework/python-tuf/pull/1620#issuecomment-947556006

-  [e.g. `Targets.update()`]   inserts or replaces the TargetFile... but a Targets handles both TargetFiles and delegations: what if I wanted to modify delegations instead? is it obvious that TargetFile needs a function but delegations do not? - https://github.com/theupdateframework/python-tuf/pull/1620#issuecomment-947556006

- [e.g. `Snapshot.update()`] is opinionated in regards to the file extension of the targets metadata to be updated with, i.e. it assumes that it is `.json`. The rest of the metadata API also often defaults to json, but allows a caller to override, which is not the case here.

**Current behavior**:

- purpose of method is unclear
- method name is ambiguous

**Expected behavior**:

- Make a better case for the purpose and names of methods and document it, or replace/remove.

**Comment by jku** [comment]
The case for (better named) update methods is that they do allow us to do validation on user input, while inserting things directly to a dictionary does not.

This is a major advantage in an untyped language but, I think, made slightly less important with good static typing support: calling code is still free to insert nonsense into our Metadata data structures, but static typing checks will inform them that they are doing bad things (at least it will once we fix #1633). We may still want to do the input validation but I would argue it's not as critical as it would be otherwise.

**Comment by MVrachev** [comment]
Issue https://github.com/theupdateframework/python-tuf/issues/1230 and this one are almost the same.
Maybe we can close https://github.com/theupdateframework/python-tuf/issues/1230?

**Comment by lukpueh** [comment]
Added one concern from #1230 to the issue description above. Will close there.
