### ISSUE TITLE
update branch protection rules?

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1629]
https://github.com/theupdateframework/python-tuf/issues/1614#issuecomment-943383529:
> * Our branch protection rules prevent us merging unless certain checks have passed.
> * When we add a new Python version to the Actions workflow, that creates a new set of checks of the form "Tests ($PY_VER, $HOST_OS-latest, py)".
> * Currently required checks includes checks of the form "Tests ($PY_VER, $HOST_OS-latest, py)" for each of PY_VER=[3.6, 3.7, 3.8, 3.9].
> * New checks introduced by adding a new Python version are not automatically included in our branch protection rules and must be added to the list of required checks manually.
> Therefore, when we add a new Python version to the workflow we need to decide whether we want to require checks pass before merging and, if so, update branch protection rules to make that happen.

Python 3.10 was just added to matrix

**Comment by joshuagl** [comment]
Updated branch protection rules for `develop` and `0.17-branch`
