### ISSUE TITLE
RepositorySimulator: add support for delegated hash bins

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1639]
**Description of issue or feature request**:

Currently `repository_tool.py` provides an easy way to distribute a large number of target files over multiple delegated roles (hashed bins).  A feature described in PEP458 that would be used in warehouse.  https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_tool.py#L2494

Having such functionality in `RepositorySimulator` that uses `metadata api` will be useful for testing the newer code.

**Comment by lukpueh** [comment]
IMO this feature should not be implemented in test code but rather be part of repository tooling (#1136).

**Comment by jku** [comment]
> IMO this feature should not be implemented in test code but rather be part of repository tooling (#1136).

absolutely true as the mid/long term goal but it might still make sense to implement in RepositorySimulator _first_:
* no need to wait for the library module to be able to test ngclient
* gives us data about the complexity and what a good API (implemented on top of Metadata API) might look like

**Comment by joshuagl** [comment]
The hashed bin delegation code in repository_tool was cleaned up and simplified when the Warehouse work kicked off. See, for example, https://github.com/theupdateframework/python-tuf/pull/1007 and https://github.com/theupdateframework/python-tuf/pull/1012. Specifically:
- [`delegate_hashed_bins()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_tool.py#L2494)
- [`add_target_to_bin()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_tool.py#L2657)
- [`remove_target_from_bin()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_tool.py#L2723)

As a follow-on we refactored some of the helper functions to be public API (see https://github.com/theupdateframework/python-tuf/pull/1058) in repository_lib for use with an early iteration of the metadata API:
- [`create_bin_name()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_lib.py#L1043)
- [`get_bin_numbers()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_lib.py#L1073)
- [`find_bin_for_target_hash()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_lib.py#L1120)
- [`get_target_hash()`](https://github.com/theupdateframework/python-tuf/blob/2206fc917e46ff584dcae75e640e1144c8b9f078/tuf/repository_lib.py#L1151)

**Comment by ivanayov** [comment]
Can I take this?

**Comment by sechkova** [comment]
Seems like the latest tendency is towards implementing the delegated hash bins functionality in a repository-side and test code at a later stage. For this reason the issue can be re-scoped to include only the needed tests from a client point of view.

Let's use the newly added delegated hash bins example as a reference #1700.

An `Updater` test needs to include:
- on the repository side:
    - creating one (or a couple of) delegated role(s). Naming does not matter for the client but in order to provide a good example, the rolename should represent the _range_ of hash prefixes it delegates.
    -  setting `DelegatedRole.path_hash_prefixes` to the list of path hash prefixes the role delegates. 
    -  adding a target file by choosing a target path whose hash digest prefix fits in the delegated role range.
 
Following the chosen prefix length and number of bins in the [example](https://github.com/theupdateframework/python-tuf/blob/b8cf1c0e379bc3d864f4314edefd51b8ebb38f27/examples/repo_example/hashed_bin_delegation.py#L169):

```python
rolename = "f8-ff"
path_hash_prefixes = ["f8", "f9", "fa", "fb", "fc", "fd", "fe", "ff"]
`test_hashed_bins.ext` -> fff0838676c1dacb8827b02511e89f85b43814a74dd2c3ffb31d952a1db94311
```

- on the client side:
   - perform the usual search for target file metadata `Updater.get_targetinfo("test_hashed_bins.ext")`
   - verify that the target info was successfully found and the correct delegated metadata file was downloaded
   - add any other error cases that can come to mind

Currently two PRs add tests for delegated roles and it would be nice if the hashed bins test is included after them in `test_delegation_graphs.py` #1689, #1711
