### ISSUE TITLE
ngtests: Add tests for delegated roles metadata update

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1641]
**Description of issue or feature request**:

Add tests for updating delegated roles metadata following [5.6.7](https://theupdateframework.github.io/specification/v1.0.25/index.html#update-targets) from the specification. A preliminary list of expected test cases:

- Successful update finds target's metadata
- Successful update does not find target's metadata
- Not loading targets metadata twice when looking for a target file
- TargetInfo is what was expected
- Visited max number of roles
- Terminating delegations

The tests should:
- Use `RepositorySimulator` for serving test files in-memory.
- "black-box" Updater, don't look at its internals, check if files are downloaded as expected (or not downloaded as expected).

**Comment by jku** [comment]
Leaving a note here: once #1654 merges, let's mostly use the implicit refresh in this tests: it makes the code one line shorter and makes sure everything gets tested (as the explicit refresh is tested plenty in `test_updater_top_level_update.py` already)
