### ISSUE TITLE
ngtests: add tests for fetching targets

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1642]
**Description of issue or feature request**:
Add tests for updating delegated roles metadata following [5.7](https://theupdateframework.github.io/specification/v1.0.25/index.html#fetch-target) from the specification. A preliminary list of expected test cases:

Fetch target with consistent targets on/off	
    - local target file exists
    - target hashes/length match
Failure to fetch target	
    - Download errors
    - Hashes and length mismatch
Caching

The tests should:

  - Use RepositorySimulator for serving test files in-memory.
  - If possible avoid duplicating test cases when toggling consistent targets
  - "black-box" Updater, don't look at its internals, check if files are downloaded as expected (or not downloaded as expected).

**Comment by ivanayov** [comment]
Can I work on this, please?
