### ISSUE TITLE
ngtests: add input validation tests for Updater API

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1644]
**Description of issue or feature request**:

Test all interesting variations of user input for Updater API. Potentially these tests may already be covered, it is still worth checking.
Table testing (see https://github.com/theupdateframework/python-tuf/blob/develop/tests/test_metadata_serialization.py) seems like the way to go.

**Comment by ivanayov** [comment]
Can I work on this, please?

**Comment by MVrachev** [comment]
Please have a look at https://github.com/theupdateframework/python-tuf/issues/1594 when you work on this as the research, it's relevant to this issue.

**Comment by ivanayov** [comment]
Can I work on this, please?
