### ISSUE TITLE
metadata API: avoid raising securesystemslib exceptions

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1646]
I think Metadata API should not require its users to import securesystemlib exceptions to be able to call Metadata API methods, it just seems weird -- as a user of TUF I am not necessarily directly using securesystemslib at all, yet I need to handle exceptions from it

**Current behavior**:

sign(), from_file() and to_file() are documented to raise these exceptions

**Expected behavior**:

I should only need to import modules from tuf to be able to handle tuf exceptions. This could mean either 
* re-exporting the securesystemslib exceptions in tuf metadata or exceptions module or
* handling the securesystemslib exceptions and raising something in python-tuf: this is what I think `verify_delegate()` does

**Comment by MVrachev** [comment]
I agree with the objective of the issue. 
I think each of the cases should be solved separately as a securesystemslib exception can describe exactly what we want to tell the user in an eventual problem and other times the securesystemslib exception will be an implementational detail.

**Comment by jku** [comment]
After some discussion last week and looking at this again: I think at least sign() should operate like the verify functions: handle the sslib exceptions and raise just a single exception (UnsignedMetadataError seems appropriate). I've been trying to imagine a scenario where a repository would like to handle the individual errors... and I cannot think of any, they don't seem useful.
