### ISSUE TITLE
metadata API: Constants for top-level rolenames

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1648]
**Description of issue or feature request**:

Top-level role names - "root", "timestamp", "snapshot" and "targets" - are hardcoded throughout the code base. Good coding practice suggests to create constants for these and use them instead.

See
```bash
grep -rE  [\"\']\(root\|targets\|snapshot\|timestamp\)[\"\'] tuf/api/ tuf/ngclient/
```

**Current behavior**:
- Top-level role names are hardcoded

**Expected behavior**:
- Constants for top-level role names are defined in `tuf/api/metadata.py` and
- Constants are used in TUF 1.0-bound code, that is at least in `tuf/api/*` and `tuf/ngclient/*` and probably any new test modules.

**Comment by ivanayov** [comment]
I'd like to work on that, please.
