### ISSUE TITLE
RepositorySimulator: inconsistent behaviour of compute_metafile_hashes_length 

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1651]
**Description of issue or feature request**:

`RepositorySimulator.compute_metafile_hashes_length` is documented as a boolean deciding " Whether to compute hashes and length for meta in snapshot/timestamp".

- When calculating snapshot metafile's hashes in `update_timestamp` and `compute_metafile_hashes_length` is switched to `False`, the old hashes and length  still remain.
- When calculating targets metafile's hashes in `update_snapshot` and `compute_metafile_hashes_length` is switched to `False`, the old hashes and length are cleaned up and the new values are set to None.

**Expected behavior**:
The correct behaviour should be the one in `update_snapshot` (clean up the hashes and length) and  it needs to be replicated in `update_timestamp`.

**Comment by ivanayov** [comment]
Can I take this?
