### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [theupdateframework/tuf#1653]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
[Markus_Elfring@fedora lokal]$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/python-tuf/lokal -name '*.py')
```

How do you think about to improve ten source code places? :thinking:

**Comment by jku** [comment]
If there are places in the newer codebase (tuf/api/ and tuf/ngclient/) where augmented assignment is not used (and could be used), I'd be interested in a patch... but I think there aren't any. 

Other locations we might not care as much -- most of it is code we'd like to deprecate sooner or later.

**Comment by elfring** [comment]
* :thought_balloon: How do you think about to try a variant of the shown transformation command example out?
* How many update candidates would be still relevant? :thinking:

**Comment by jku** [comment]
My opinion is that there are currently no cases where changing the assignment would be worth a PR.

**Comment by elfring** [comment]
:thought_balloon: Can it be that adjustments according to the mentioned transformation pattern would trigger desirable effects on the software run time characteristics?

**Comment by jku** [comment]
Theoretical perf improvement may be possible but it would be such a tiny one we'd be unable to measure it. Readability would be a better selling point... but as I said the code bases that matter seem to be good already.

Thanks for bringing this up, but I think I'll close it: there does not seem to be anything that needs fixing.
