### ISSUE TITLE
New style guidelines: should we ban the usage of assertRaises in testing?

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1660]
**Description of issue or feature request**:

Currently our [code style guidelines](https://github.com/secure-systems-lab/code-style-guidelines/blob/master/python.md) doesn't specify anything about the usage of `self.assertRaises` vs the usage of `with self.assertRaises():`

Using `self.assertRaises` can lead to long statements separated to multiline expressions as pointed out by @jku here: https://github.com/theupdateframework/python-tuf/pull/1658#discussion_r741725382.
On another hand `with self.assertRaises():` looks better in my opinion:
https://github.com/theupdateframework/python-tuf/blob/589ed9e0d48aad9acaea912f409e1445d5913416/tests/test_api.py#L131
Long expressions look a lot better https://github.com/theupdateframework/python-tuf/blob/589ed9e0d48aad9acaea912f409e1445d5913416/tests/test_api.py#L210 when using `with self.assertRaises():` than using `self.assertRaises():` as pointed out in Jussi's comment.

**Current behavior**:

No guidelines about `self.assertRaises`  vs `with self.assertRaises():`.

**Expected behavior**:

The question is should we specify something more concrete? 

**_EDIT: We decided we would remove all instances of `self.assertRaises` and replace them with `with self.assertRaises`._**

**Comment by lukpueh** [comment]
I like the recommendation but I'd also like to keep our general code style guide as short as possible.  

Maybe this would be a good fit for a test guideline document --> https://github.com/theupdateframework/python-tuf/issues/1129.

**Comment by MVrachev** [comment]
There was a discussion with the maintainers and we decided that we would remove all instances of `self.assertRaises` and replace them with `with self.assertRaises` and that if we are going to specify that in the documentation somewhere it will be when solving #1129.
