### ISSUE TITLE
re-enable fossa integration (or remove .fossa.yml)

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1661]
We had fossa integration in CI back in 2020 but do not have it now: the config file .foss.yml is still there in the repo though.

There does not seem to be anything preventing enabling FOSSA now: GH actions is directly supported via an OAuth GitHub App.

Maybe it makes sense to evaluate the need for FOSSA before we enable it though:
* dependency updates are handled by dependabot
* dependabot also does vulnerability alerts (based on CVEs and advisories) for the pip ecosystem

That leaves ... license compliance checks? is there something else that fossa provides? 

@lukpueh maybe has opinions?

**Comment by lukpueh** [comment]
This is a duplicate of https://github.com/theupdateframework/python-tuf/issues/1244

**Comment by lukpueh** [comment]
IIRC fossa is or at least was a requirement for the https://bestpractices.coreinfrastructure.org gold badge.

**Comment by jku** [comment]
cheers, it is indeed a duplicate
