### ISSUE TITLE
RepositorySimulator: add trackers/counters for downloaded files

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1682]
**Description of issue or feature request**:
There is a need in some test cases to check whether Updater requested the correct files from the repository.
For a concrete use case see #1666.

One option used in #1666 is to use `unittest.mock` and "wrap" `RepositorySimulator._fetch_*` methods which does the job but does make the tests less readable.
Therefore as an alternative,  proposed by @jku https://github.com/theupdateframework/python-tuf/pull/1666#pullrequestreview-807253797,  checking that the expected files are downloaded from remote can be done by adding some download counters into `RepositorySimulator` which would  be cleaner and more maintainable

**Comment by kairoaraujo** [comment]
I will work on it.

**Comment by jku** [comment]
basically my idea was that 
* repositorysimulator keeps lists of requests (I guess one for metadata, one for targets makes sense). It adds an item to list every time a request is made
* tests can at any time check that the list is what they expect
* tests can also clear the list when they want
* the format of the lists should be whatever makes most sense for the test code (urls? metadata role names? :shrug:)
