### ISSUE TITLE
Implement native support from GHA for pip caching with python-setup.

### ISSUE THREAD

**Issue by kairoaraujo** [theupdateframework/tuf#1692]
**Description of issue or feature request**:
The Github Actions now supports [dependency caching](https://github.com/actions/setup-python#caching-packages-dependencies). We can remove approximately ten lines from our [CI.yml](https://github.com/theupdateframework/python-tuf/blob/acb201d6cc685c2560f1000faf47e75db73df7fb/.github/workflows/ci.yml#L51-L63)

Thanks, @joshuagl, for sharing the news.

**Current behavior**:
A specific caching for pip is implemented in our CI.ym to implement and use pip cache.
[We find and store the pip-cache and use the ``actions/cache@v2`` to use it.](https://github.com/actions/setup-python#caching-packages-dependencies)

**Expected behavior**:
Use the ``python-setup`` with [``cache:pip``](https://github.com/actions/setup-python#caching-packages-dependencies)

**Comment by jku** [comment]
nice.

the only tricky bit might be  `cache-dependency-path` -- we use essentially "requirements*.txt" currently but the new format likely wants specific files: need to check which requirements file(s) are actually used when CI runs.
