### ISSUE TITLE
examples: run mypy on repo example

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1697]
repository example is not completely annotated. mypy config (currently in setup.cfg) does not cover the example: it should cover the whole `examples/` directory. 

It looks like this means some minor annotation fixes in the example (mostly to deal with `roles` dictionary items).

**Comment by lukpueh** [comment]
Quick question, is there a consensus ([#1130](https://github.com/theupdateframework/python-tuf/issues/1130), [#1301](https://github.com/theupdateframework/python-tuf/pull/1301)..?) to use type annotations everywhere?

**Comment by jku** [comment]
I ... don't know. I like them so much now that I just kind of assumed.

To be clear, I do think that 
* we should aim to cover most of our code with static typing
* we should document this as the safest way to use the APIs: if applications check types statically that means our validation code can concentrate on validating deserialized json (instead of concentrating on validating application provided input)

**Comment by MVrachev** [comment]
I can take this one as I already added `examples` locally when addressing comments for #1699.
