### ISSUE TITLE
doc: misc enhancements to contributors

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1709]
**Description of issue or feature request**:
Here are a few suggestions to enhance our [Instructions for Contributors](https://theupdateframework.readthedocs.io/en/latest/CONTRIBUTORS.html) on RTD.

**Current behavior**:
- No mention of Secure Systems Lab development guidelines
- Too extensive (and prominent) section about DCO
- Too extensive (and outdated/opinionated?) virtualenv description
- Very extensive description of test logging/verbosity config 

**Expected behavior**:
- Link to SSLab [development guidelines](https://github.com/secure-systems-lab/lab-guidelines/blob/master/dev-workflow.md)
- Shorten DCO section (and optionally move down in doc) (see e.g. [in-toto Instructions for Contributors](https://github.com/in-toto/in-toto#instructions-for-contributors) for inspiration)
- Just recommend usage of and link to existing virtualenv documentation
- Shorten description of test logging/verbosity config

**Comment by jku** [comment]
> * Shorten description of test logging/verbosity config

#1724 is going to make `tox` run a reasonable approximation of CI tests so we should suggest that as the way to run tests.

Then after that we can include a _short_ mention on how to run specific tests and the options (`-v` for logs, `--dump` for repository dumps when available)
