### ISSUE TITLE
ngclient: test fast-forward recovery

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1713]
I think we do not currently test successful rollback (aka fast-forward recovery) for timestamp, snapshot and targets:
  * simulate a fast-forward attack: create repository with valid timestamp/snapshot/targets with version=MAX_VERSION (or something large anyway)
  * update client so it sees the large versions 
  * rotate the affected key (timestamp or snapshot) and set metadata version=1
  * update client, assert that new metadata is accepted by ngclient (even though the version number is lower than the local version)

**Comment by kairoaraujo** [comment]
Please, can you sign this issue for me?

**Comment by jku** [comment]
> create repository with valid timestamp/snapshot/targets with version=MAX_VERSION

I'm not sure if there even is a practical MAX_VERSION in our implementation -- python seems to seamlessly upgrade from an int to some big int implementation... I _think_ this is not relevant anyway: the point is that version is something large that we want to reinitialize to 1.

**Comment by jku** [comment]
I think we're done here! Thanks Kairo
