### ISSUE TITLE
Add the examples/client_example to RTD

### ISSUE THREAD

**Issue by kairoaraujo** [theupdateframework/tuf#1716]
**Description of issue or feature request**:
An example can be a good start point for those reading the RTD Updater.
We could add the [client_example](https://github.com/theupdateframework/python-tuf/tree/develop/examples/client_example) in a way it can be explored by who wants to implement a client.

**Current behavior**:
The `ngclient.Updater` RTD does not have an example or point to the examples folder. The event folder is available only in the source code.

**Expected behavior**:
Easy landing or example demonstration to who wants to implement a client.

**Comment by lukpueh** [comment]
I think a sensible quick fix would be to just add a phrase or paragraph on RTD that links to the directories `examples/client_example` and `examples/repo_example`, akin to how it's done in the [repo main readme](https://github.com/theupdateframework/python-tuf/blame/f172972f721aa7b2fd844302e0f3046bca2614f3/README.md#L69).

This could be part of the [RTD API reference](https://github.com/theupdateframework/python-tuf/blob/f172972f721aa7b2fd844302e0f3046bca2614f3/docs/api/api-reference.rst) and/or in a [new top-level RTD "examples" page](https://github.com/theupdateframework/python-tuf/blame/f172972f721aa7b2fd844302e0f3046bca2614f3/docs/index.rst#L17-L19).
