### ISSUE TITLE
Missing from spec: PKCS?

### ISSUE THREAD

**Issue by nyarly** [theupdateframework/tuf#172]
On the one hand, why doesn't TUF simply employ standard PKCS tools where applicable, like CSRs and CRLs? Granted, there are UX problems, but similar problems have been solved by browsers, largely. Issued certificates seem like they could stand in for the delegations, at least.

But I assume this is a conversation that's been had before - diverging from existing established cryptography is a decision that's still surprising to a newcomer, and documenting the reasons for it would be really helpful.

**Comment by trishankatdatadog** [comment]
Closing because we do not support revocation lists, and we support rotation of keys w/o in-band mechanisms
