### ISSUE TITLE
What to do with tuf/exceptions before 1.0.0?

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1729]
**Description of issue or feature request**:

Currently, we are using `tuf/exceptions.py` to store client and repository exceptions both for the new and old implementation.
After we drop the old code we will have to keep the exceptions from `tuf/exceptions.py` or move them to somewhere else.
Some of the options I and @jku come up with are the following:
1. create a new exceptions file in `tuf/api/exceptions.py` storing all exceptions needed from the client, metadata API, and future repository code (see #17256). Then when the old code is dropped the `tuf/exceptons.py` will be removed as well.
2. keep `tuf/exceptions.py` and just remove the old exceptions.py after we remove the old code. This will require linting the file and changing the docstrinsg (see https://github.com/theupdateframework/python-tuf/pull/1721)
3. create new exceptions files: one in `tuf/api/` with repository side and metadata API exceptions and one in `tuf/ngclient/` where we will store the exceptions for the ngclient. Remove `tuf/exceptions.py` together with the rest of the old code.

Option `1` or `2` seem easier to change with less code, but option `3` will provide better encapsulation

**Comment by MVrachev** [comment]
@lukpueh, @jku  do you have an opinion?

**Comment by lukpueh** [comment]
I don't have a strong opinion here, but I tend towards option 3. Also, I wonder if we still want to keep the `api` directory once we've removed legacy code. IIRC `api` was a bit of a crutch so we don't mix up new and legacy code.

**Comment by lukpueh** [comment]
I think it is more important to figure out which (custom or built-in) exceptions we raise where (see #1131, #1312, #967) than where we define custom exceptions.

**Comment by jku** [comment]
(changing title, I assume this was intended)

**Comment by MVrachev** [comment]
In #1725 I have tried implementing option `1`.
I don't like option `2` as we will have to wait to drop the old code before we can actually work on it freely.
Option `3` is not bad, but the only problem is that in `tuf/metadata/api.py` there is code used both in ngclient
and most likely will be used in the future repository code - for example `Metadata.from_file()`.

> Also, I wonder if we still want to keep the api directory once we've removed legacy code. IIRC api was a bit of a crutch so we don't mix up new and legacy code.

My personal feelings are against moving the code anywhere for the following reasons:
- the path `tuf/api` or `tuf/ngclient` is not long, so at least I wasn't bothered by it
- the bigger reason is that we will lose the git history. I went through that when researching how to rename the old test files. See https://github.com/theupdateframework/python-tuf/issues/1582#issuecomment-940436906

@lukpueh and @jku can you see #1725 and #1734 which seem related to the current discussion.

**Comment by MVrachev** [comment]
We have decided in #1725 that we would place the new exception file in `tuf/api/exceptions.py`, so this issue is solved.
