### ISSUE TITLE
ngclient: test data length limits

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1730]
target length mismatch does have tests but I believe we don't test metadata length limits (the maximum values configured for the client). I suppose we should.

This should be easy to do by modifying the UpdaterConfig max length values to something small and verifying failure.

**Comment by sechkova** [comment]
The remaining Updater configurations that are not explicitly tested are the ones related to metadata length:

    root_max_length: int = 512000  # bytes
    timestamp_max_length: int = 16384  # bytes
    snapshot_max_length: int = 2000000  # bytes
    targets_max_length: int = 5000000  # bytes
