### ISSUE TITLE
spec version incompatibility

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1751]
datadogs metadata contains 
`"spec_version": "1.0",`

This is currently not compatible with Metadata API (deserializating the data fails). 

"1.0" seems to not be a strictly compliant spec_version (the specification says _format follows semantic versioning_) but we could potentially support this for backwards compat?

EDIT: also metadata generated with go-tuf (so for example sigstore metadata) looks like this.

**Comment by jku** [comment]
hmm looks like their newer metadata has
`"spec_version": "1.0.0",`
so maybe we don't need to support the other format after all...

**Comment by trishankatdatadog** [comment]
> datadogs metadata contains `"spec_version": "1.0",`

Thanks for filing the issue. Can you point to the metadata files?
 
> "1.0" seems to not be a strictly compliant spec_version (the specification says _format follows semantic versioning_) but we could potentially support this for backwards compat?

I would say so, yes, although I'm not sure how many people actually use the original python-tuf implementation.

**Comment by jku** [comment]
here is an example: https://dd-integrations-core-wheels-build-stable.datadoghq.com/metadata.staged/4.root.json

**Comment by jku** [comment]
metadata generated with go-tuf (so for example sigstore metadata) uses "1.0" as well.
