### ISSUE TITLE
doc: Is it okay to remove spec "forwarders"?

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1770]
I'm in the process of cleaning up the repository (#1745, #1767, #1768, #1769) and was wondering if it's okay to remove the old [`doc/tuf-spec*`](https://github.com/theupdateframework/python-tuf/tree/v0.20.0/docs) documents, which are merely pointers to the [`theupdateframework/specification`](https://github.com/theupdateframework/specification) repo (created in late 2017).

I can see how these were kept in place to avoid 404s of old links, but I think the up-to-date TUF specification location is discoverable enough to get rid of these pointers.

What do others think?

**Comment by lukpueh** [comment]
cc @mnm678, @trishankatdatadog, @joshuagl

**Comment by jku** [comment]
Agreed, it's been 4+ years and finding the spec is easy.

**Comment by joshuagl** [comment]
I'm in favour of removing.

**Comment by trishankatdatadog** [comment]
+1

**Comment by mnm678** [comment]
I agree. We can replace old links as we find them.

**Comment by lukpueh** [comment]
Cheers for weighing in, everyone!
