### ISSUE TITLE
Do we need a new MissingInformationError/MissingMetadataError?

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1778]
**Description of issue or feature request**:

We want to use a shortlist of exceptions that will be thrown from our APIs, so that our users can handle them easily.
On another hand that doesn't stop us from creating other more specific exceptions that derive from those main exceptions.
This allows us to easily test that specific errors were thrown when we expected them.
For example we are using `BadVersionError` and `LengthOrHashMismatchError` which derive from `RepositoryError`.

There is the possibility to add a new exception which can be called `MissingInformationError` or `MissingMetadataError`.
It will replace `RepositoryError` which we threw inside the TrustedMetadataSet when:
- information for a target is missing inside a new snapshot version compared to an older snapshot version- not sure we need a new one here
- updating a delegated target, but snapshot doesn’t contain information for it - not sure we need a new one here

For context see comments: https://github.com/theupdateframework/python-tuf/pull/1725#issuecomment-1012254130, https://github.com/theupdateframework/python-tuf/pull/1725#issuecomment-1014336394, and https://github.com/theupdateframework/python-tuf/pull/1725#issuecomment-1014431059

**Comment by lukpueh** [comment]
I reviewed all exceptions and I no longer think we currently need to add a custom MissingInformationError/MissingMetadataError. Shall we close here?
