### ISSUE TITLE
File system limitations

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#178]
There are some practical limitations that we must consider for hard links and consistent snapshots.

For example, [ext4 limits the number of hard links to a file to 65K](https://en.wikipedia.org/wiki/Hard_link#Limitations_of_hard_links). This will not have immediate impact, except when enough consistent snapshots have been produced, so our code must be able to handle this.

The other limit that I ran into the other day was filename size: [most modern filesystems limit file paths to 255 characters](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). If a package name is sufficiently long, then prepending its digest can induce this problem. One way to work around the problem is to simply rename the hard link to simply its hash value; there will be no mimetype problem if we correctly rename the downloaded file.

**Comment by trishankatdatadog** [comment]
Not a problem on modern OSes. Will reopen if someone sees this in production.
