### ISSUE TITLE
Generic exceptions vs Specific exceptions

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1784]
**Description of issue or feature request**:
We want to use a shortlist of exceptions that will be thrown from our APIs, so that our users can handle them easily.
On another hand that doesn't stop us from creating other more specific exceptions that derive from those main exceptions.
This allows us to easily test that specific errors were thrown when we expected them.
For example, we are using `BadVersionError` and `LengthOrHashMismatchError` which derive from `RepositoryError`.

Still, there are two use cases that are worth discussing:

1. There are multiple places inside `TrustedMetadataSet` where in one API call we are throwing generic and specific exceptions.
That's happening inside each of the functions `update*` inside `TrustedMetadataSet` we throw `RepositoryError`, `ReplayedMetadataError`, `ExpiredMetadataError` and `UnsignedMetadataError` (from `verify_delegate()`) at the same time.
One idea could be to define new specific exceptions (which derive from `RepositoryError` and replace the instances of `RepositoryError` with them. 

Read and synchronize with issues:
- #1778 
- #1779 
- #1714
- #1312 

2. Inside the `TrustedMetadataSet` `update*` function docstrings we only document that we are throwing `RepositoryError` without specifying the specific exceptions. If none of them are documented in the Raises section of the method docstrings (they only mention the broad RepositoryError), do we expect anyone to handle them? If we do, we should probably document them?

_Inspired by https://github.com/theupdateframework/python-tuf/pull/1725#discussion_r787713776._

3. Inside `_get_session` in module `tuf/ngclient/_internal/request_fetcher.py` we currently throw `URLParsingError`: https://github.com/theupdateframework/python-tuf/blob/0e26364dfcb54bc7c0eee9f7d2ef7a67b9b53868/tuf/ngclient/_internal/requests_fetcher.py#L135
In my commit https://github.com/theupdateframework/python-tuf/pull/1725/commits/e8f26ebb1e7c68fc9c0ddd5b3a268c0a56a7a304 inside pr #1725 I am replacing it with `DownloadError`.
The question is do we want to keep the specific exception - `URLParsingError` and make it derive from `DownloadError`?
Does my change in this commit make sense?

**Comment by jku** [comment]
> The question is do we want to keep the specific exception - URLParsingError and make it derive from DownloadError?
Does my change in this commit make sense?

I believe no-one is ever going to handle a URLParsingError so there should be no need for it. If that statement turns out wrong and a need arises later, adding a derived error is easy. The commit is good.

**Comment by jku** [comment]
> Inside the TrustedMetadataSet update* function docstrings we only document that we are throwing RepositoryError without specifying the specific exceptions. If none of them are documented in the Raises section of the method docstrings (they only mention the broad RepositoryError), do we expect anyone to handle them? If we do, we should probably document them?

Updater does use some of the specific exceptions. I would not object to TrustedMetadataSet having better exception documentation, the reason it doesn't is probably the fact that it's currently private (documenting too much does lead to outdated documentation...)

For updater itself I think documenting just RepositoryError (and not the more specific ones) is reasonable: Updater users are not going to care about the details.

**Comment by lukpueh** [comment]
I just did a thorough review of all exceptions we raise in api and ngclient and it all looks good modulo some missing documentation (will post related comments to #1785, where they seem more appropriate).

So I agree with what Jussi says about `TrustedMetadataSet` exceptions and I suggest we remove the following TODO comment?
https://github.com/theupdateframework/python-tuf/blob/cb7bd6aff9be097facecbd27ee5998c48feeb52d/tuf/ngclient/_internal/trusted_metadata_set.py#L62-L65

Let's do that and close this issue?

**Comment by jku** [comment]
Yes: PR #1805
