### ISSUE TITLE
Source not available on coveralls.io

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1789]
**Description of issue or feature request**:
Test coverage for each job in our GitHub Action workflow is [published on coveralls.io](https://coveralls.io/github/theupdateframework/python-tuf).

https://github.com/theupdateframework/python-tuf/blob/b2704a56a8c5023ffd7d377d8a8e72fb26a46a8a/.github/workflows/ci.yml#L62-L97

**Current behavior**:
For some reason it [no longer shows the source code files](https://coveralls.io/builds/45790627/source?filename=tuf%2Fapi%2Fmetadata.py) with marked covered / not covered lines.

![Screen Shot 2022-01-21 at 11 34 31](https://user-images.githubusercontent.com/589324/150512776-c44dd81b-2d37-4579-b5f6-8cd93144f8fa.png)

**Expected behavior**:
 It would be nice to reinstate that feature...

A local workaround:
```bash
$ coverage run aggregate_tests.py
................................................................................................................................
----------------------------------------------------------------------
Ran 128 tests in 5.166s

OK
$ coverage html
Wrote HTML report to htmlcov/index.html
```

**Comment by jku** [comment]
this one is strange: if I log in to coveralls the sources are suddenly available  :shrug: ?

**Comment by lukpueh** [comment]
Great find and it gave me the additional search engine parameter I needed: 
https://github.com/lemurheavy/coveralls-public/issues/1579

Looks like this is by design. Closing here.
