### ISSUE TITLE
doc: remove/reword announcement about upcoming 1.0.0 on release

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1795]
**Description of issue or feature request**:
Once we have released 1.0.0 it no longer makes sense to say that we are about to release 1.0.0. We should remove/reword the corresponding docs parts shortly before we cut the 1.0.0 release.

**Current behavior**:
- Main [README has an "important notice"](https://github.com/theupdateframework/python-tuf/blame/e0736d6d75e344b10ac128e5798cde3136ccc9cf/README.md#L10-L14) about upcoming 1.0.0 release
- [docs/1.0.0-ANNOUNCEMENT.md](https://github.com/theupdateframework/python-tuf/blob/e0736d6d75e344b10ac128e5798cde3136ccc9cf/docs/1.0.0-ANNOUNCEMENT.md) is written in a way that suggest that the 1.0.0 release is in the future

**Expected behavior**:
- Remove important notice about upcoming 1.0.0 release from main readme
- Reword docs/1.0.0-ANNOUNCEMENT.md to not sound outdated after release (or just remove)

**Comment by jku** [comment]
reference doc also still says _"Major API changes are unlikely but these APIs are not yet considered stable..."_

**Comment by lukpueh** [comment]
> reference doc also still says _"Major API changes are unlikely but these APIs are not yet considered stable..."_

Fixed in https://github.com/theupdateframework/python-tuf/pull/1868

**Comment by jku** [comment]
Fixed in #1873
