### ISSUE TITLE
Add get_filepaths_in_directory() flag to ignore 'digest.filename' targets. 

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#181]
It may be convenient for repository maintainers to continually fetch all target files from particular directories and then add them with `repository.targets.add_targets()`, as opposed to only adding new target files explicitly.

One issue with blindly adding all target files in a directory multiple times occurs when a directory contains `digest.filename` target files, which should not be included as targets in metadata.

Support:

``` Python
get_filepaths_in_directory(ignore_digest_filenames=True)
```

**Comment by trishankatdatadog** [comment]
Stale
