### ISSUE TITLE
Metadata API: from_securesystemslib_key() should handle sslib error

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1818]
from #1785

`from_securesystemslib_key()` should raise ValueError if securesystemslib.FormatError happens in format_keyval_to_metadata().

from_securesystemslib_key() is a helper so that repository code does not need to figure out how to safely get a Key from a securesystemslib private key. The securesystemslib call done there is a bit useless (we could just probe the dictionary ourselves) but since we call the function we should make sure to handle FormatError

**Comment by MVrachev** [comment]
I can take this one.
If someone else was planning to work on this, please write a comment.
