### ISSUE TITLE
github: re-enable pip caching

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1822]
**Description of issue or feature request**:
#1821 disables pip caching in "Set up Python"-step in `.github/workflows/ci.yml` as workaround for https://github.com/actions/virtual-environments/issues/5009. Let's re-enable it when this is fixed upstream.

**Current behavior**:
pip caching disabled

**Expected behavior**:
pip caching re-enabled

**Comment by jku** [comment]
Fixed with #1824
