### ISSUE TITLE
Dependabot does not work

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1828]
Several months ago we replaced setup.py with setup.cfg. This seems to have immediately broken dependabot, which has since then been complaining about missing setup.py -- it does not complain in an issue as you might have expected but in the easily discoverable location of _Insights -> Dependency graph -> Dependabot -> "requirements-dev.txt Last checked ..."_ 

I'm sending a PR of manual dependency updates soon but this issue is specifically for either fixing dependabot or jumping through whatever hoops we need to jump through to get dependabot working.

Related: https://github.com/dependabot/dependabot-core/issues/4483

**Comment by jku** [comment]
From setuptools:
> If setup.py is missing from the project directory when a [PEP 517](https://www.python.org/dev/peps/pep-0517) build is invoked, setuptools emulates a dummy setup.py file containing only a setuptools.setup() call.

So I suppose the easiest workaround is to re-add a setup.py with this content:

```python
from setuptools import setup
setup()
```

**Comment by jku** [comment]
> jku closed this in #43 1 hour ago

that happened in a completely different repository!?!

**Comment by lukpueh** [comment]
> that happened in a completely different repository!?!

Interesting, so you can link with keywords across forks.

**Comment by jku** [comment]
seems to be working now: https://github.com/theupdateframework/python-tuf/network/updates/276791557
