### ISSUE TITLE
Write 1.0 changelog / release notes

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1845]
In preparation for release, start working on changelog

**Comment by lukpueh** [comment]
Some open questions: Do we need release notes in addition to the changelog? Should we just add a release note preamble to the 1.0.0 changelog entry? Is it enough if that just links to the existing 1.0.0 release announcement (coordinate with #1795)?

**Comment by jku** [comment]
> Some open questions: Do we need release notes in addition to the changelog? Should we just add a release note preamble to the 1.0.0 changelog entry? Is it enough if that just links to the existing 1.0.0 release announcement (coordinate with #1795)?

Status and some thoughts:
* we'll have blog post(s) for announcement
* I don't think the changelog needs more but it would be nice to include a link to the announcement... but that seems like a tricky cyclical dependancy :) 
* we can add the announcement link to the Github release page afterwards, and could even edit the changelog file afterwards
* We could even link to the announcement from README, at least for a time

Suggestion: let's leave it as is, and after we have the announcement up somewhere (after the release is made), add a link to the github release page and possibly the changelog file?

**Comment by lukpueh** [comment]
Shall we close this issue now, or with #1873?

**Comment by jku** [comment]
linked, thanks
