### ISSUE TITLE
project blog: setup

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1884]
It would be nice to have a place to publish project related things that are not quite documentation but something we want to be able to link to (maybe workflow examples or updates on PyPI work, etc ). This sounds like a blog so let's investigate how to have one.

I think the path of least resistance might be Github Pages right here in the python-tuf repo. Other options include reviving the 
theupdateframework.github.io (currently archived project in theupdateframework organization) or a third party blog platform.

Issues to investigate:
* GitHub Pages have a weird configuration: you can set the Pages root folder... but it looks like the UI only allows `/` and `/docs`: these might not work for us

**Comment by lukpueh** [comment]
I think it's a good idea generally, and doing it in this repo with the URL `theupdateframework.github.io/python-tuf` specifically, similar to how we do it for the spec at [theupdateframework.github.io/specification](https://theupdateframework.github.io/specification).

[theupdateframework.github.io](https://theupdateframework.github.io/) currently just redirects to the project-wide [theupdateframework.io](https://theupdateframework.io/), which also seems fine.

**Comment by jku** [comment]
I suppose enabling Project Wiki might be another option but I think blogs are more what I'd like.


> GitHub Pages have a weird configuration...

There is a workaround for this: github pages can be set to publish from a `gh-pages` branch. So we could have a github action (on push to develop) that takes content from docs/content/, puts it in a place where Pages can find it, pushes a commit to gh-pages branch only. It's pretty hacky but people seem to be using that: this way humans would not need to ever deal with gh-pages branch

**Comment by jku** [comment]
> GitHub Pages have a weird configuration...

Continuing on that, I think we might be able to live with docs/ being the blog root. It does make the docs directory again a little more cluttered (see #1849) but not horribly so. This is what I think the structure looks like:

```
docs/
    index.md # Blog title, description
    _config.yml # Blog config
    _posts/
            2022-02-23-first-post.md
            2022-02-23-second-post.md
```            

I'll still have to test this but if that works I think the simplicity is pretty great (no automation required, everything is in python-tuf repo, GitHub just handles everything)

Still can't understand why they couldn't make the location configurable???
