### ISSUE TITLE
blog: "how we test ngclient compliance"

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1885]
Assuming we find a working blog platform (#1884), we should start publishing things.

On idea I had was _"Testing a tricky edge case in a TUF client"_ (very much a working title)
  - show how cool RepositorySimulator is and what it does
  - document usage of `--dump` to see the "live" test repository state for debugging purposes
  - document a specific edge case in TUF spec so we can refer to it later

Maybe that's too much content for one post already... I ended with that list because I'm specifically thinking of one of the cases in #1707 : these are really tricky corner cases and the tooling we have makes them testable -- but only if you know about the test components and how to work with Metadata

assigning to ivana: it's your PR so maybe you're interested

**Comment by ivanayov** [comment]
The contents are in this [doc](https://docs.google.com/document/d/1xomQOn6Hj6DQvsloHf-eEFA39H9RNkROHzrcEnjQ7Tw/edit?usp=sharing).
