### ISSUE TITLE
Different names for the "roles" field in the root and targets roles

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#190]
@paracycle [wondered](https://groups.google.com/forum/#!topic/rubygems-tuf/bspQces3iYA) why the "roles" field is ordered in any targets role, but not ordered in the root role.

@JustinCappos recommended that we rename the "roles" field in the root role to avoid confusion of the purpose of this field.

We should look at renaming, if necessary, the field in both the root and targets roles to suit their purposes.

**Comment by trishankatdatadog** [comment]
The "roles" field in all targets metadata is a list because it is meant to denote prioritized delegations, whereas in the root metadata, the order doesn't matter because we know exactly what roles they must contain.
