### ISSUE TITLE
Replace manual path construction with "os.path.join"

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1903]
**Description of issue or feature request**:
I found a couple of places in the tests where we have used `f` strings and manually joined paths instead of using `os.path.join()`.
This can lead to a problem where on Linux and Mac OS this behavior will work, but on Windows won't.
Some examples:
- https://github.com/theupdateframework/python-tuf/blob/e7037cf8c42022ea20f3b7891a50aa3ed563521b/tests/test_api.py#L236
- https://github.com/theupdateframework/python-tuf/blob/e7037cf8c42022ea20f3b7891a50aa3ed563521b/tests/test_api.py#L162

When discussing with @jku why don't we get CI failures from this behavior he found out that:
> File I/O in the Windows API converts forward slashes ("/") to backslashes ('\'), before passing the request to the native API

Even though that's the case, it's better if we replace those instances of manual path construction with the preferred `os.path.join`.
We should not forget we are developing `python-tuf` for Windows users as well. :)

**Comment by aribasch** [comment]
Hi! New to open source and looking to contribute. I've been able to follow the development installation instructions and run tests for python-tuf, and am looking to tackle some good first issues and familiarize myself with the codebase. I was wondering if I would be able to claim this issue?

**Comment by lukpueh** [comment]
Hi @aribasch, a pull request would be most welcome. :)

**Comment by dennisvang** [comment]
@MVrachev A question related to this issue: 

Is there a reason `os.path` is used throughout the codebase, instead of `pathlib`? Personally I find `pathlib` often makes for clearer reading, and it is often more convenient to use.  

For example, in the cases above, if `self.repo_dir` were a `pathlib.Path`, you could simply do:

```python
self.repo_dir / "metadata/root.json"
```

Another example: In [client_example.py](https://github.com/theupdateframework/python-tuf/blob/develop/examples/client_example/client_example.py#L18) you could do something like this:

```python
...
DOWNLOAD_DIR = Path("downloads")
METADATA_DIR = Path.home() / ".local/share/python-tuf-client-example"
CLIENT_EXAMPLE_DIR = Path(__file__).resolve().parent


def init() -> None:
    ...
    for dir_path in [DOWNLOAD_DIR, METADATA_DIR]:
        dir_path.mkdir(parents=True, exist_ok=True)
    ...

```

**Comment by jku** [comment]
> Is there a reason `os.path` is used throughout the codebase, instead of `pathlib`?

I believe historical reasons only: pathlib is a fairly new API. I'm ok with using Pathlib, it's definitely convenient. 

I'd argue that it's only clearer to people who already know Pathlib. E.g. from your examples:

    self.repo_dir / "metadata/root.json"

... I admit I would have expected that to create something surprising on windows but maybe it just works?

**Comment by dennisvang** [comment]
> I'd argue that it's only clearer to people who already know Pathlib. E.g. from your examples:
> 
> ```
> self.repo_dir / "metadata/root.json"
> ```
> 
> ... I admit I would have expected that to create something surprising on windows but maybe it just works?

@jku I agree it may take a bit of getting used to. Nevertheless, in my experience, it just works, even on windows. ;-)

To ease the transition, `pathlib` docs provide a useful [table mapping various `os` functions to their corresponding `pathlib` equivalents](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module).

**Comment by MVrachev** [comment]
Honestly, I think I agree with @jku here.
I think `os.path.join` is easier to understand as an interface.
