### ISSUE TITLE
TAP 15 (succinct hashed bin delegations) implementation

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1909]
**Description of issue or feature request**:
[TAP 15](https://github.com/theupdateframework/taps/blob/master/tap15.md) was created on June 23-rd 2020 and was last modified in July 6-th 2020.
Since then the TAP has been put to `draft` status meaning it needs a prototype implementation before it's accepted as a future specification change.
Given that this TAP underlines an efficient way of handling hash bin delegations, meaning it would be really useful when `python-tuf` is integrated into `Warehouse`, it's logical that we should not only create a prototype but directly work to integrate it in `python-tuf`.

The result I am expecting from this issue is:
1. Support reading, updating, and saving target metadata files that are using `succinct hashed bin delegations`.
2. An exemplary document inside `examples/` showcasing how `succinct hashed bin delegations` can be utilized in practice.

I have come up with the following steps:

- [x] Add and update the necessary attributes to support reading and writing from/to a target file with `succinct hashed bin delegations`
- [x] Add simple testing for target files using `succinct hashed bin delegations`.
- [x] Make sure the client parses the succinct hash bin delegated metadata
- [x] Test that the client parses the succinct hash bin delegated metadata and visits the expected bin for a specific target
- [x] Test actually downloading a target
- [x] Add a script inside `examples/`
- [x] Testing the `examples/` script

**Comment by lukpueh** [comment]
This is exactly what I had in mind for this issue! Plus, the client also needs to be able to parse and interpret the new metadata, in order to find the correct bin for a target.

**Comment by MVrachev** [comment]
> This is exactly what I had in mind for this issue! Plus, the client also needs to be able to parse and interpret the new metadata, in order to find the correct bin for a target.

Agree, added it to the TODO list.

**Comment by MVrachev** [comment]
After #2031 and #2038 are merged I think we are ready to close this issue.
I don't see any other todo items left.

**Comment by MVrachev** [comment]
Closing as there is no work left on that issue.
