### ISSUE TITLE
Support HSM signing

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#1912]
Supersedes #569 and #864
Related to #1109 (out-of-band signing)
Groundwork available in https://github.com/secure-systems-lab/securesystemslib/pull/229

**Description of issue or feature request**:

python-tuf (or rather `securesystemslib`) should provide an implementation to sign metadata with hardware security modules, like Yubikey, plus functions for public key export and signature verification.

**Current behavior**:

The [`sign`](https://theupdateframework.readthedocs.io/en/v1.0.0/api/tuf.api.metadata.metadata.html#tuf.api.metadata.Metadata.sign) method in the new Metadata API takes a [`Signer`](https://github.com/secure-systems-lab/securesystemslib/blob/692b14dac4d1f6ae31c2655e21d5fecd86bd2fe5/securesystemslib/signer.py#L91) parameter which generates the actual signature. Currently, `secureystemslib` has one standard `Signer` implementation in [`SSlibSigner`](https://github.com/secure-systems-lab/securesystemslib/blob/692b14dac4d1f6ae31c2655e21d5fecd86bd2fe5/securesystemslib/signer.py#L110), which encapsulates `securesystemslib`-style private keys (rsa, ed25519, ecdsa) and generates a `Signature` that can be verified with a python-tuf [`Key`](https://theupdateframework.readthedocs.io/en/v1.0.0/api/tuf.api.metadata.supporting.html#tuf.api.metadata.Key) using its [`verify_signature`](https://theupdateframework.readthedocs.io/en/v1.0.0/api/tuf.api.metadata.supporting.html#tuf.api.metadata.Key.verify_signature) method.

**Expected behavior**:

- Implement `HSMSigner` that can generate a signature on an HSM 
  -> see [`SSlibSigner`](https://github.com/secure-systems-lab/securesystemslib/blob/692b14dac4d1f6ae31c2655e21d5fecd86bd2fe5/securesystemslib/signer.py#L110) and [`GPGSigner` (WIP)](https://github.com/secure-systems-lab/securesystemslib/pull/341) for inspiration, and [sslib#229](https://github.com/secure-systems-lab/securesystemslib/pull/229) for groundwork
- Provide functionality to export the corresponding public key as [python-tuf `Key`](https://github.com/theupdateframework/python-tuf/blob/f2e80a82cba5bf3cb04241b65c983840cb5036b5/tuf/api/metadata.py#L585) 
  -> see [`from_securesystemslib_key`](https://github.com/theupdateframework/python-tuf/blob/f2e80a82cba5bf3cb04241b65c983840cb5036b5/tuf/api/metadata.py#L671) for inspiration
- If necessary, update [`Key.verify_signature`](https://github.com/theupdateframework/python-tuf/blob/f2e80a82cba5bf3cb04241b65c983840cb5036b5/tuf/api/metadata.py#L700) so that it can verify the corresponding signatures 
  -> with [sslib#229](https://github.com/secure-systems-lab/securesystemslib/pull/229) verification should work out of the box

**Comment by trishankatdatadog** [comment]
@d-niu, you might be interested in this 🙂

**Comment by lukpueh** [comment]
Securesystemslib provides an [`HSMSigner`](https://github.com/secure-systems-lab/securesystemslib/blob/v0.31.0/securesystemslib/signer/_hsm_signer.py#L75-L116), which is compatible with the TUF Metadata API, since [v0.26.0](https://github.com/secure-systems-lab/securesystemslib/blob/main/CHANGELOG.md#securesystemslib-v0260).

It is used e.g. to[ support YubiKeys in TUF-on-CI](https://github.com/theupdateframework/tuf-on-ci/blob/main/docs/SIGNER-SETUP.md#requirements).
