### ISSUE TITLE
Fetcher docs should make it clear what needs to be implemented

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1916]
Should add a sentence in FetcherInterface docstring that explains that the public API of the interface is implemented already: implementations of the interface only need to implement the internal

    def _fetch(self, url: str) -> Iterator[bytes]

**Comment by abs007** [comment]
Hi @jku, could you please send me the file location for the FetcherInterface docstring. Thanks.

**Comment by jku** [comment]
sure.
* Published docs: https://theupdateframework.readthedocs.io/en/latest/api/tuf.ngclient.fetcher.html
* source code: tuf/ngclient/fetcher.py

I suppose there's two things to possibly improve here:
* `_fetch()` is currently not included in documentation (sphinx does not include it because of the "_" prefix). If there is an easy way to get sphinx to include it, that would be nice. This could be as simple as adding `   :private-members: _fetch` in  docs/api/tuf.ngclient.fetcher.rst but that's just a guess
* more importantly, the class docstring should mention that an implementation of FetcherInterface only needs to implement _fetch(): the public API of the class is already implemented.

**Comment by abs007** [comment]
Hi, I was going through a sphinx tutorial and had a question. Would I need to run `make html` after editing the `tuf.ngclient.fetcher.rst` file?

**Comment by lukpueh** [comment]
Yes, if you want to build the html docs locally. The docs hosted on `https://theupdateframework.readthedocs.io`, on the other hand, are built automatically.

**Comment by abs007** [comment]
So, for testing out the changes locally I'd have to run that command but upon pushing the changes, the new html file is created automatically.

**Comment by abs007** [comment]
I keep encountering this `make: *** No rule to make target 'html'.  Stop.` error when trying to run `make html` from the terminal. According to a few solutions online, I found that a certain 'Makefile' would be needed in the folder where I'm running `make html` from.

**Comment by jku** [comment]
easiest way to create docs locally is to run `tox` (or `tox -e docs` if you want to skip the tests and build just the docs), this should get you new docs in docs/build/html.

Also note that when you push a branch and get the CI test results, one of the results is a readthedocs build: you can just click "details" to see what it will look like on readthedocs.

**Comment by abs007** [comment]
> Also note that when you push a branch and get the CI test results, one of the results is a readthedocs build: you can just click "details" to see what it will look like on readthedocs.

It seems like it's working now.
