### ISSUE TITLE
ngclient: used trusted timestamp if new has equal version 

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#2023]
**Description of issue or feature request**:

The [specification was changed](https://github.com/theupdateframework/specification/compare/v1.0.29..v1.0.30) to say wrt client timestamp update:
> In case they [versions] are equal, discard the new
timestamp metadata and abort the update cycle.
This is normal and it shouldn't raise any error

To conform with spec v1.0.30, ngclient needs to be updated. See #1992 for discussion.

**Current behavior**:

Update cycle fails if new timestamp version is less (`<`) than trusted timestamp version (L224). Otherwise (`>=`) , update cycle continues and the new timestamp becomes the trusted timestamp (L241).

https://github.com/theupdateframework/python-tuf/blob/46979bb46d3054ca37fc0b9258574a126d975fcc/tuf/ngclient/_internal/trusted_metadata_set.py#L222-L242

**Expected behavior**:

Update cycle fails if new timestamp version is less (`<`) than trusted timestamp version. Otherwise (`>=`), update cycle continues. If new and old timestamp versions are equal (`=`), new timestamp is ignored and old timestamp remains trusted.  If new timestamp version is higher (`>`) new timestamp becomes the trusted timestamp.

**Comment by MVrachev** [comment]
I can fix that if you @lukpueh are not already working on it.
