### ISSUE TITLE
deps: hatchling update

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2030]
We pin hatchling in pyproject.toml: `build-system.requires = ["hatchling==0.22.0"]`. I think this is the correct choice: otherwise the build is not really reproducible.

It looks like Dependabot does not notice this as a dependency: so we're currently several versions behind.

Tasks:
* Update hatchling to current
* Figure out how we stay up-to-date?

**Comment by joshuagl** [comment]
Relevant dependabot feature request: https://github.com/dependabot/dependabot-core/issues/3290

**Comment by UDITBALUJA** [comment]
Hi, I would like to fix this issue. Can you please assign me this issue.

**Comment by jku** [comment]
Note that this might be an impossible request:
> Figure out how we stay up-to-date?

So a plain hatchling version bump (and preferably checking that the build result did not change) is fine.

**Comment by UDITBALUJA** [comment]
I have checked hatchling versions  1.9.0 and 1.10.0 and the build results seem to be fine.I'll also check for the latest version released on  9 Oct,2022 ,and will give update soon.
