### ISSUE TITLE
Socket timeout default value pretty onerous

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#204]
Don't know what I was thinking when I [set the default socket timeout value to be 1 second](https://github.com/theupdateframework/tuf/blob/2c55b94a8bfabf61404df3af5a7a04bc91191a1a/tuf/conf.py#L51-L52), but it turns out to be pretty impractical in practice (e.g. client fails to connect via WiFi to server on the same LAN). Minor issue, but should reconsider.

**Comment by lukpueh** [comment]
`SOCKET_TIMEOUT` has in the meanwhile been tweaked several times (see `git log -L :SOCKET_TIMEOUT:tuf/settings.py`). Currently it's at 4 seconds. And there is a pending PR that splits it into `SOCKET_CONNECT_TIMEOUT = 10` and `SOCKET_INTERBYTE_TIMEOUT = 4`. I think we can close this issue.
