### ISSUE TITLE
DownloadLengthMismatchError because requests automatically decodes gzip files

### ISSUE THREAD

**Issue by dennisvang** [theupdateframework/tuf#2047]
**Description of issue or feature request**:

If target is a gzip file, served with a `Content-Encoding: gzip` header, `requests` will automatically decode the file.

**Current behavior**:

As a result, the [default fetcher][2] for tuf ngclient raises a `DownloadLengthMismatchError`:

```
tuf.api.exceptions.DownloadLengthMismatchError: Downloaded x bytes exceeding the maximum allowed length of y
```

**Expected behavior**:

From the [requests docs][1]:

>An important note about using `Response.iter_content` versus `Response.raw`. `Response.iter_content` will automatically decode the `gzip` and `deflate` transfer-encodings. `Response.raw` is a raw stream of bytes – it does not transform the response content. If you really need access to the bytes as they were returned, use `Response.raw`.

I would expect tuf to access the `Reponse.raw` instead of `Response.iter_content` here:

https://github.com/theupdateframework/python-tuf/blob/b5e952cee3edb1c3363a8a7859cb548b13ab71f3/tuf/ngclient/_internal/requests_fetcher.py#L99

Note that `Response.raw` is a [urllib3.response.HTTPResponse][3], which also decodes `gzip` encoded content by default, but `requests` [disables this][4] by setting `decode_content=False`.

[1]: https://requests.readthedocs.io/en/latest/user/quickstart/#raw-response-content
[2]: https://github.com/theupdateframework/python-tuf/blob/b5e952cee3edb1c3363a8a7859cb548b13ab71f3/tuf/ngclient/_internal/requests_fetcher.py#L77
[3]: https://urllib3.readthedocs.io/en/latest/reference/urllib3.response.html#urllib3.response.HTTPResponse
[4]: https://github.com/psf/requests/blob/bda7f0171f8bba17989d3a2c28dfa9a9261b1b65/requests/adapters.py#L497

**Comment by joshuagl** [comment]
Thanks for the detailed report and for proposing a fix @dennisvang. Would you be interested in creating a Pull Request to implement the proposed fix?

**Comment by dennisvang** [comment]
@joshuagl Yes, I would be happy to create a pull request for this.

Actually I already started working on one, but it's taking a bit longer than anticipated.

**Comment by joshuagl** [comment]
Brilliant, thank you

**Comment by dennisvang** [comment]
@joshuagl I believe PR #2048 does the job, although I'm not entirely sure my method of testing is acceptable.

**Comment by lukpueh** [comment]
This is not a bug in the client but in the server. See https://github.com/theupdateframework/python-tuf/pull/1774 and https://github.com/theupdateframework/python-tuf/pull/2048#issuecomment-1188969803 pp. for details.
