### ISSUE TITLE
Provide a way to customize the default Requests session

### ISSUE THREAD

**Issue by KOLANICH** [theupdateframework/tuf#2072]
**Description of issue or feature request**:
The Requests session for each connection by default is created from scratch. And there is no sane way to customize it, for example to support `file://` URIs via https://github.com/dashea/requests-file. 

**Current behavior**:
`Session()` is called within `RequestsFetcher._get_session`

We can patch every session using

```python
def _get_session(self, url: str) -> requests.Session:
    s = super()._get_session(url)
    s.mount('file://', self.fileAdapter)
    return s
```

but it will patch the sessions from the `_sessions`.

**Expected behavior**:

1. A field with the default session is added.
2. A method (or property) `_get_default_session` is added that just returns the field
3. that method is called within `_get_session`

This way there are multiple ways to customize. If we want, we can provide a fresh session by redefining the method. Or we can customize the default session externally just by mutating the field.

**Comment by jku** [comment]
> there is no sane way to customize it

Custom FetcherInterface implementations are a way for you to control every aspect of the download. RequestsFetcher is maybe 50 lines of code (40 if you don't care about the multi-session-caching in `_get_session()`) so copy-pasting and creating a modified version seems fine. 

We didn't make RequestsFetcher part of the public API exactly because it's clear that people would want to modify the internal details (like `_get_session()`) and we didn't want to make them part of the public API... but I don't want to prevent you from deriving from RequestFetcher as long as you're aware it's not something we consider public API.

To give you another way to customize, you could keep deriving from RequestsFetcher and just re-implement `_get_session()` -- don't call `super()`, make it as simple as you want: `return requests.Session()` is likely the minimal implementation.

> Expected behavior:
> 
> 1. A field with the default session is added.
> 2. A method (or property) _get_default_session is added that just returns the field
> 3. that method is called within _get_session

I don't quite understand this... RequestsFetcher has no default session, what would the field contain?

**Comment by KOLANICH** [comment]
>Custom FetcherInterface implementations are a way for you to control every aspect of the download.

Custom `FetcherInterface` for `requests` without reusing your code is reinventing wheel.

>To give you another way to customize, you could keep deriving from RequestsFetcher and just re-implement _get_session() -- don't call super(), make it as simple as you want: return requests.Session() is likely the minimal implementation.

Reimplementing this method is also reinventing a wheel.

>RequestsFetcher is maybe 50 lines of code (40 if you don't care about the multi-session-caching in _get_session()) so copy-pasting and creating a modified version seems fine.

For me it doesn't seem fine if adding 4 lines of code into the upstream impl can eliminate the need to fork it.

>but I don't want to prevent you from deriving from RequestFetcher as long as you're aware it's not something we consider public API.

Yeah, it's OK. I added this for testing purposes to avoid spinning up a local http server. But I'm considering just adding this functionality into upstream with https://github.com/dashea/requests-file as an optional dependency. It can also simplify testing.

>I don't quite understand this... RequestsFetcher has no default session, what would the field contain?

Should we introduce it?

**Comment by jku** [comment]
With regards to the wheel re-invention comments: I am personally wary of adding complexity into python-tuf unless it makes life easier for many users. The project has seen the maintenance costs of excess complexity before and I personally would like to not see them again. This does not mean I'm against PRs making RequestsFetcher easier to derive from: I just don't want that to lead to too much added code complexity _in this project_.

> > I don't quite understand this... RequestsFetcher has no default session, what would the field contain?
> 
> Should we introduce it?

I mean, I literally don't know what the field could contain... So no, I don't yet see why we should introduce it.

Sessions are stored per-domain. The purpose (as documented in a code comment) is to:
* re-use sessions (so each request doesn't have to create a new one)
* but prevent subtle security issues with sharing a session between domains by storing one session per scheme+domain

The second point is arguably security overkill but it works fine so it's still there... The design should work fine with your file-scheme patch (which will make all file-URLs use a single session).

The above means that if you are only interested in modifying the session for file-URLs , you actually need to do it just once: 
when you initialize your fetcher you could do 
```python
# make sure the file:// session has a file adapter
s = self._get_session('file:///') # any file url will do
s.mount('file://', file_adapter)
```
and now you likely won't need to implement `_get_session()`.

**Comment by KOLANICH** [comment]
Thanks for the info, I have missed that aspect. I guess a redefineable factory method creating a session should be enough.
