### ISSUE TITLE
Build dependency hatchling: use 1.x versions

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#2082]
When hatchling was proposed to python-tuf in pr https://github.com/theupdateframework/python-tuf/pull/1896 the contributor @ofek said for `hatchling` version the following:
```
 It is quite stable and actively maintained, the only reason the version is 0.x is because 1.0.0 will drop support for Python 2.
```
I haven't checked his claim, but if he is correct we can bump the `hatchling` version we are using to `1.x`.

TODO: Consider using `hatchling` versions `1.X.Y`.

**Comment by ofek** [comment]
Yup I'd recommend upgrading to latest!

**Comment by jku** [comment]
yeah we absolutely want to use newest hatchling -- the only reason we're pinning the version is that we want the build to be reproducible so would like tool versions to change in a way that we control (and haven't managed to get dependabot to handle this version number)

**Comment by ofek** [comment]
Understood! A new change in metadata output is slightly different classifier sorting https://github.com/pypa/hatch/pull/412 based on https://github.com/pypa/trove-classifiers/blob/e9d1beaaab239f1b43a92e373cd5ef1be7753442/src/trove_classifiers/__init__.py#L4

**Comment by jku** [comment]
this duplicates #2030 I think
