### ISSUE TITLE
Should we replace urllib(2) with requests?

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#209]
Right now, we have some code copied over from pip to ensure that urllib(2) will verify SSL certificates and so on.

I think we are better off replacing the lower-level urllib(2) code with the [requests](http://docs.python-requests.org/en/latest/) library instead. Even pip does so now.

However, we need to check whether requests will allow us to control things like watching for a slow retrieval attack and so on.

**Comment by lukpueh** [comment]
`requests` was introduced with #781. Closing here.
