### ISSUE TITLE
Create a security policy

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#2096]
**Description of issue or feature request**:

Similar to [go-tuf](https://github.com/theupdateframework/go-tuf/issues/371), we should create a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) so that researchers can properly disclose security issues.

**Comment by joshuagl** [comment]
We have one, it's just not in a dedicated SECURITY.md as GitHub expects: https://github.com/theupdateframework/python-tuf#security-issues-and-bugs

We _might_ want to consider including more of the maintainers in the security reporting path somehow, but I don't have concrete suggestions.

**Comment by mnm678** [comment]
I think it's worth copying/moving the policy into SECURITY.md for easier discovery

**Comment by trishankatdatadog** [comment]
> I think it's worth copying/moving the policy into SECURITY.md for easier discovery

Agree: this is by default where people (like myself) will look in GitHub
