### ISSUE TITLE
Repository and developer tools should warn about large metadata

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#210]
Although we do have hashed delegations, we should ideally have the repository and developer tools warn administrators and developers about sufficiently (controlled by a `tuf.conf` parameter) large metadata.

(It might even be desirable to prevent altogether writing such large metadata.)

**Comment by trishankatdatadog** [comment]
Considered solved, because we have [upper bounds](https://github.com/theupdateframework/tuf/blob/530d4a8eef7082d6bcbae6f163bda80b37714893/tuf/settings.py) on the sizes of metadata downloaded.
