### ISSUE TITLE
Compress metadata by default

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#211]
From experiments, we have found that it is sensible to compress metadata by default. There may be edge cases where this does not make sense (e.g. for sufficiently small metadata), so an administrator or developer should be able to opt-out of this default by configuring the appropriate `tuf.conf` parameter.

Furthermore, it seems that bzip2 always compresses metadata better than gzip. However, we need to investigate other performance characteristics such as memory or time.

**Comment by trishankkarthik** [comment]
Looks like [Zstandard](https://code.facebook.com/posts/1658392934479273/smaller-and-faster-data-compression-with-zstandard/) might work nicely for JSON. Should run some measurements sometime.

**Comment by lukpueh** [comment]
Compression should not be handled by TUF itself (see [TAP10](https://github.com/theupdateframework/taps/blob/master/tap10.md)).
