### ISSUE TITLE
Toggle consistent snapshot in the repository root role

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#215]
Presently, we do `repository.write(consistent_snapshot=True)` whenever we want a consistent snapshot. I wonder whether this is always required, and whether the `consistent_snapshot` should be set on `repository.root` instead? Otherwise, we have to remember to keep setting `consistent_snapshot` whenever we want one, and this is prone to errors.

Is there a use-case where the `consistent_snapshot` is set on the root, and the user may want to make an exception?

**Comment by vladimir-v-diaz** [comment]
root.json now specifies whether the repository supports consistent snapshots.  See an example here: https://github.com/theupdateframework/tuf/blob/0ce016b7b19a0fc15443eed657a90246ec5df0aa/tests/repository_data/repository/metadata/root.json#L9-L14
