### ISSUE TITLE
Publish OSSF Scorecard results

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2160]
https://github.com/ossf/scorecard

Would be nice to get these results visible. They have a GitHub Action that we could use.

The installation instructions say:
> One Scorecards check ([Branch-Protection](https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection)) requires authentication using a Personal Access Token (PAT). If you want all Scorecards checks to run on a public repository, you will need to follow the optional Authentication step. If you don't, all checks will run except Branch-Protection.

The token is described as "read-only" but I don't understand why it would be read-only... maybe it is but I don't get how.

So:
* the github action would be nice
* the action should work without a token: I'm fine with skipping the branch-protection check

**Comment by spartan289** [comment]
hi i would like to work on this issue

**Comment by jku** [comment]
Hi, thanks!

As advice: I think the instructions in https://github.com/ossf/scorecard-action#workflow-setup might not work for you in this repository (the UI probably won't be there unless you are admin). Options:
* fork this repo and follow the above instructions in your repo, then make a PR of those changes to this repo
* just get the example  from https://github.com/ossf/scorecard-action#manual-action-setup  and fix at least  the main branch name

**Comment by spartan289** [comment]
Yes i will do it.

**Comment by jku** [comment]
oh they have manual setup instructions too  https://github.com/ossf/scorecard-action#manual-action-setup

**Comment by jku** [comment]
I think I'll try to enable this today.

(no slight on you spartan: it's just been 3 weeks since last comment, and I'd like to see the results of recetnt configuration changes)

**Comment by spartan289** [comment]
I tried, but it was always showing error

**Comment by jku** [comment]
I've added "ossf/scorecard-action@*" to allowed actions for this project -- based on @joshuagl review I figured there was consensus on this

**Comment by jku** [comment]
Now it works:
https://github.com/theupdateframework/python-tuf/actions/runs/3525418144/jobs/5912109928

[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/theupdateframework/python-tuf/badge)](https://api.securityscorecards.dev/projects/github.com/theupdateframework/python-tuf) :+1:
