### ISSUE TITLE
Allow generation of hash-prefixed versions of `TargetFile`s

### ISSUE THREAD

**Issue by yzhan289** [theupdateframework/tuf#2166]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
Allow generation of hash-prefixed versions of `TargetFile`s.

**Current behavior**:
Currently, python-tuf does not have the ability to generate hash-prefixed path names for targets files. One suggestion from @jku is to add a utility function in Metadata API's `TargetFile` like: 
```
Target.File.get_prefixed_paths() -> List[str]
```

**Expected behavior**:
The expected behavior is to able to get the hash-prefixed path names for any given targets file. 

Example: 
https://github.com/vmware-labs/repository-editor-for-tuf/blob/main/tufrepo/git_repo.py#L210

**Comment by trishankatdatadog** [comment]
Great idea! This might be a quick, easy win... 🙂

**Comment by jku** [comment]
I think it makes sense (although the result is likely still not as simple as you might hope: dealing with files vs URLs is complicated and python-tuf can't really make it easier without making a lot of assumptions). 

usage in a repository that wants to store actual target files and symlinks in the same directory would look like this (this is untested): 

```python
TARGET_PATH = "public/path/file.ext" # download URL path fragment
LOCALTARGETS="/home/jkukkonen/local_copy_of_targets_repo" # filesystem path

with open(f"{LOCALTARGETS}/{TARGET_PATH}", "w") as f:
    f.write("target data")

target = TargetFile.from_file(TARGET_PATH, f"{LOCALTARGETS}/{TARGET_PATH}")
for prefixed_path in target.get_prefixed_paths():
    # prefixed_path is e.g. "public/path/5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03.file.ext"
    os.symlink(TARGET_PATH, "f{LOCALTARGETS}/f{prefixed_path}")
```

it's still not _super_ simple, but there is a couple of good reasons for that
* python-tuf does not (and should not) translate between URLs and filesystem paths. The code above does this, with the understanding that it's the repository apps responsibility to make sure that works.
* targets can in some situations change their content over time -- but the old symlinks can't then just refer to the new content, that would be wrong: with the API we have this is possible to handle (although my example above does not do it)
