### ISSUE TITLE
code uses python 2 "__metaclass__"

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2196]
python-tuf and securesystemslib both use class variable `__metaclass__ = abc.ABCMeta` to implement abstract classes. This does nothing in Python3 -- classes can be instantiated even if they have that class variable set 

The actually supported methods are
```python
from abc import ABC
class MyABC(ABC)
```
and
```python
from abc import ABCMeta
class MyABC(metaclass=ABCMeta)
```
the latter may be safer (WRT multiple inheritance issues)

**Comment by aditya-shrivastavv** [comment]
Hey, I tried to work upon this issue. I found that for python version 3.4 and above the following code might work.
```
from abc import ABC
class MyABC(ABC):
    pass

MyABC.register(tuple)

assert issubclass(tuple, MyABC)
assert isinstance((), MyABC)
```
What do you think about this ? am i going in the right direction ? 
I am a beginner, want to contribute to this project 🫡.

**Comment by aditya-shrivastavv** [comment]
A class that has a **metaclass** derived from **ABCMeta** cannot be _instantiated_ unless all of its abstract methods and properties are _overridden_.
we can use a decorator: `@abc.abstractmethod`
This decorator requires that the class’s metaclass is ABCMeta or is derived from it.

**Comment by jku** [comment]
You're welcome. This should be a small task: there's only one or two instances of `__metaclass__` usage. They should be changed to use the keyword `metaclass=ABCMeta`, see last example in original report.

Please check docs/CONTRIBUTING.md for advice on signed-off-by and running linter and tests locally

**Comment by aditya-shrivastavv** [comment]
Thankyou for your guidence jussi, I am working upon it. 
I found a line in one of the file which might be causing this problem it says, `__metaclass__ = abc.ABCMeta`
I am a litte confused that should I change it to `__metaclass__ = ABCMeta` or `metaclass=ABCMeta` or they are both the same thing ?
I am still learning about all these thing, right now I am in my freshman year of college, I think it will take me time to get a hang of these things.
Please clear my silly doubt😅 and also can someone assign me this issue please?

**Comment by aditya-shrivastavv** [comment]
Okay I think i got it. I have used `metaclass = abc.ABCMeta` in place of `__metaclass__ = abc.ABCMeta`. also ran tox and it ran and finished successfully👍
![image](https://user-images.githubusercontent.com/81470938/206151370-50b0f0ea-0232-409a-9b11-0c78973f9bc8.png)
what do you think should i make a PR or any changes remaining? please suggest.
