### ISSUE TITLE
build: Stop depending on action-gh-release

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2212]
We use softprops/action-gh-release to upload release artifacts to GitHub releases. This makes the action a fairly critical part of our release pipeline. The latest release of action-gh-release includes, among other things, thousands of lines of changes to package-lock.json: Yay npm.

So I'm wondering if we can replace the action.  I think  `await github.rest.repos.createRelease(...)` using actions/github-script should do it... but someone would have to go through the trouble of testing that.

**Comment by jku** [comment]
well, `github.rest.repos.createRelease(...)` and then `rest.repos.uploadReleaseAsset(...)` to be exact. It does get a bit complicated since you need to read files from disk to upload them.

So there's no clearly good solution. I am still amazed that github deprecated their own actions for this.

**Comment by aditya-shrivastavv** [comment]
I will test it

**Comment by jku** [comment]
my hunch is that it will be a bit too complicated, but I'd be happy if someone tries it out.

I did some initial testing here https://github.com/jku/test-releases/blob/main/.github/workflows/cd.yml It's not complete but feel free to copy from that if you want (but note that I'm not a js developer, that could be all wrong).

**Comment by jku** [comment]
Current https://github.com/jku/test-releases/blob/main/.github/workflows/cd.yml seems about right (it releases static files right now but the same code should work in python-tuf). See example release https://github.com/jku/test-releases/releases/tag/v0.0.17

I think maintaining ~10 effective lines of javascript is a reasonable price to pay to not have a release dependency
