### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#2264]
**Description of issue or feature request**:

There have been 259 commits to the `develop` branch since the last release of python-tuf (2.0.0 on August 16th 2022), including the initial repository API. Let's make a release!

**Comment by jku** [comment]
The open question is if we try to get the Key changes (use the Key moved to securesystemslib instead of our own, #2165) in this release: I'm also fine with just doing a release now, then doing another soon-ish to get the key changes in use

**Comment by lukpueh** [comment]
> I'm also fine with just doing a release now, then doing another soon-ish to get the key changes in use

I think both is fine. There is loads of janitorial commits  + experimental repository module in `develop`. I need to check if there are any other substantial changes/additions. Either way, I think a release without #2165 is fair.

**Comment by jku** [comment]
I've tested current develop (or to be exact it was #2277 branch): sigstore master and 1.0.0 tests are all green.

In the longer term we (or sigstore-python) does need some better solution for this (they have now switched to depend on `tuf ~= 2.0.0` which does mean we can do API breaks without fear... but any bugs in our releases will break already released sigstore-python versions -- really not ideal). For this release that smoke test should do.
