### ISSUE TITLE
GitHub "required checks" is somehow not up-to-date

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2326]
See checks in PR #2324 for example

I'll try removing and re-adding the checks in settings...

**Comment by lukpueh** [comment]
I think that's a consequence of #2317. I tried changing the checks after merging that PR. But the new ones weren't available in the "recent checks" drop down then. Thanks for tracking the issue!

**Comment by jku** [comment]
looks like I got it to work, closing
