### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2382]
It's been a while since the last python-tuf release, so maybe time to bake one. I have not looked through the git log, not sure yet if this is a minor or point release.

Potential blockers:
* #2371 (and #2376) -- release infra improvement, would make sense to review & merge
* #2377 -- just a testing dependency update but a fairly major one
* anything else?

not blockers IMO:
* #2363 offline client work would be nice to get into a testable state but it's not ready yet
* #2378 It's close to ready but still a draft and so has not had review

**Comment by jku** [comment]
> I have not looked through the git log, not sure yet if this is a minor or point release.

This is likely actually a 3.0.0: We have not done a release since the moving Key to Securesystemslib and that is strictly speaking an API break.

**Comment by jku** [comment]
Opinions on Repository API stability? 

I'm still pretty much the only one who has used it so that makes me say "still unstable"...

**Comment by joshuagl** [comment]
Agree with "still unstable". Hopefully RSTUF will experiment with this soon to give more confidence in the API.
