### ISSUE TITLE
Write only dirty metadata

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#241]
### Observed

As @SantiagoTorres and I have mentioned before, the repository tool currently automatically writes the next version of metadata that is signed by any signing key loaded into memory.

This is counter-intuitive when we, say, load the unclaimed signing key to sign for only a few bins that have changed. However, all of the bins are signed.
### Expected

We expect only "dirty" metadata (which has seen explicit modification by the user) to be signed upon writing a repository from memory to disk.

A quick-and-dirty workaround we used is [here](https://github.com/dachshund/tuf/compare/write_dirty_targets_only), but certainly it does not constitute a well-designed long-term solution.

@JustinCappos noted that when nothing in the repository has changed, then only a new timestamp must be issued.

Thanks!

**Comment by vladimir-v-diaz** [comment]
The repository tool now writes metadata only for the roles that are dirty:
https://github.com/theupdateframework/tuf/blob/0ce016b7b19a0fc15443eed657a90246ec5df0aa/tuf/repository_tool.py#L233-L248
