### ISSUE TITLE
Wildcard in target paths?

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#242]
If I am not mistaken, presently TUF specifies that target paths are either files or directories, and previously TUF specified that target paths could contain the wildcard (`*`) character to denote a positive number of alphanumeric characters (without resorting to the full power of regular expressions in order to control security).

My question is: are we planning to allow wildcards in targets paths? This would make some delegation target paths more compact (e.g. `packages/*/D/Django/*`).

Thanks!

**Comment by dcoutts** [comment]
We would find this useful for the Haskell implementation for Hackage to implement certain existing policies compactly.

We have this cross-cutting "hackage trustee" user role. These users are allowed to edit certain files across all packages in the reporitory (".cabal" package metadata files, but not package ".tar.gz" files), whereas package authors can edit all the files but only for a specific package. To express this trustee policy we would want to have a path like "packages/*/*/*.cabal" (corresponding to package/$name/$version/$name.cabal).

**Comment by vladimir-v-diaz** [comment]
Using wildcards in file paths is now supported.  See https://github.com/theupdateframework/tuf/commit/81a147614bb6e07f0d8e2fda1cbd2c8833821d4b
