### ISSUE TITLE
Consistent snapshot prepends hash algorithm instead of value to target filename

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#244]
### Observed

Presently, if the user writes a repository with consistent snapshots, then the repository tool hard links the target `filename` to the alias `sha256.filename`.

I think this is because [the code iterates over the keys](https://github.com/theupdateframework/tuf/blob/d25aa1edd2fe787ec1fd9b2666d34fc147aa0118/tuf/repository_lib.py#L1505-L1507) (i.e. hash algorithms such as `sha256`) instead of the values (i.e. hash values) of the dictionary of hashes.
### Expected

The repository tool should replace the hash algorithm with its value instead.

Thanks!

**Comment by davedoesdev** [comment]
Is there any chance of a new release on PyPI please?
I'm coming up against this issue.

**Comment by vladimir-v-diaz** [comment]
There will soon be a 1.0 release on PyPI.  There have been a few major changes made to the framework, so we are still in the process of testing and finalizing these changes.

However, we can make a 1.0 pre-release this week.  Does this work for you?

**Comment by davedoesdev** [comment]
That would be great - thanks.

**Comment by davedoesdev** [comment]
Hi @vladimir-v-diaz  - any update on this please? I've got a package using tuf but don't want to release it before trying with the latest version.

**Comment by dachshund** [comment]
Hi @davedoesdev, if I'm not mistaken, I believe my colleague @vladimir-v-diaz is currently out of town. I'm sure he'll get back to you as soon as possible!

In the meantime, perhaps you could help us beta test the [latest code](https://github.com/theupdateframework/tuf/tree/1f4f7d4b63e8085f528981212acb6e66dc0d9fe5) on GitHub? It should be able to do [consistent snapshots](https://github.com/theupdateframework/tuf/tree/1f4f7d4b63e8085f528981212acb6e66dc0d9fe5/tuf#consistent-snapshots), and it would be great if you would please share your experience with us.

Thanks for your patience, and for helping us to test TUF!

**Comment by davedoesdev** [comment]
Sure, I'll see if I can get my unit tests working against it.

**Comment by davedoesdev** [comment]
Python 2.7 all my tests pass. However, on Python 3.4 there is an exception when writing the metadata:

```
 dtuf/__init__.py:69: in locked
    return _locked(self._master_repo_lock, None, f, self, *args, **kwargs)
dtuf/__init__.py:62: in _locked
    return f(self, *args, **kwargs)
dtuf/__init__.py:287: in create_metadata
    timestamp_key_password)
dtuf/__init__.py:274: in _add_metadata
    repository.write(consistent_snapshot=True)
../.local/lib/python3.4/site-packages/tuf/repository_tool.py:266: in write
    consistent_snapshot)
../.local/lib/python3.4/site-packages/tuf/repository_lib.py:170: in _generate_and_write_metadata
    metadata_filename)
../.local/lib/python3.4/site-packages/tuf/repository_lib.py:1808: in sign_metadata
    signature = tuf.keys.create_signature(key, signed)
../.local/lib/python3.4/site-packages/tuf/keys.py:713: in create_signature
    sig, method = tuf.pyca_crypto_keys.create_rsa_signature(private, data.encode('utf-8'))
../.local/lib/python3.4/site-packages/tuf/pyca_crypto_keys.py:298: in create_rsa_signature
    tuf.formats.DATA_SCHEMA.check_match(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tuf.schema.AnyString object at 0x7fe56188ea58>
object = b'{"_type":"Root","consistent_snapshot":true,"expires":"2017-01-03T13:58:25Z","keys":{"668b06dfd7b657d474740bf0e2f618e...timestamp":{"keyids":["a308d13194a921f4327d5b97fcc77b918f462474a196ecd7e8eacff1191786ff"],"threshold":1}},"version":0}'

    def check_match(self, object):
      if not isinstance(object, six.string_types):
>       raise tuf.FormatError('Expected a string but got '+repr(object))
E       tuf.FormatError: Expected a string but got b'{"_type":"Root","consistent_snapshot":true,"expires":"2017-01-03T13:58:25Z","keys":{"668b06dfd7b657d474740bf0e2f618e80a3476ad5bd15000cfd0db50402280a9":{"keytype":"rsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA1KuBUyufr0dqIfJOiKCJ\nGQtBaTjDYxW0z19cQFGuENriWEDFzY1QzTdKFhMMRaRAV+ya+PkFoCTV3kf427y8\nCuEHyfkCg9ovqWIFK2jql3vN33l1IbykO5czi2AngT7SYZk6uuI9I39G9Rc48w54\neqRf6+mPnrJuruxfh6h+2JGoqX7xFdevllXr2frTknqx6tLRLHArAMjg1xnMysuA\njfjWLoPIKSjRVEX7k7psQ1UUTv+kEpQv7A3cmiOTG9Jt3x1RlTHizHr650cJVZwH\neN/n2K69K4aKAMd7p8YQWCDMTqa3mXI3X69CRT7/nHEzm3C7Ujn+2gFU1QI2mT0d\n5LtWfX7ayoXHYTwLTNbvjcgZOyUAEXuru/1p8rgjeEgQKlhkEXB3zb3XjcbKeYjX\nftKtG3UagYw60dVdBw3WL40Lsi/gH2hJTO8T9fB4oYA4LfeFjPVPOuh9K7T/s8IT\n73SjmZDyO04jJYoRCrG1OUW7vFKoxZFLkkmXlsw3u0I5AgMBAAE=\n-----END PUBLIC KEY-----"}},"756ce3a37c8a7a48a306e5f134ce63d3523e9c06f942b9fdd2161dbcafb640d0":{"keytype":"rsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAo9rrj5lgNgbWTredchzA\n3usKMGfuLTVbvhSDX/WNmGG3wOEh7Ej4RP0i0UxBmqutl2xx2cw9eTA2nsbJtGTQ\nNBJKOK26Vw5kxL0OXirkTXsl0c9mItZFSYn9kne+R+e0TjQzWzYc5ZGFIlyNe8AX\nfOOXmnL6CPT1feUVTBBo239k1WJKLnRma0oa75SJ8DUxzITNoV0UitkI0trcjA0a\n5GtvEB9TitmwG5YPSleGujthCtAvgOyqelI8+D0T7n8RL+dZORGsjHLzmIQrTpW4\nVibWNPqBMHLSZIgpww5+SesrtJfRhtg34hXaaegS4LorMKa6LfpGL7twF9H4Ompm\nX8f7j8eENGMGLyvdEF5iRbXTzpdYhy17QGTXk7lt75MTShNCdVfyVywQxttoBbv+\nx6WFcsZI0tEbuQmWYaueNxH+lZngYsDUNY0knrDqiKhyV38QYzNV1WBNxj+X6Vir\nou+lS1qu53hzpt1+T9f94xheqN8F9+c3bgJD1h2JEYnlAgMBAAE=\n-----END PUBLIC KEY-----"}},"8c4f645e35f06c9ed9d8f17eed6de314017eee2c53a833d3690e616ab5420a86":{"keytype":"rsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA1En0iRHyhDz8B2/nq2D9\ncEVE5UGE8mGVoV/5/+bhFy7VC+Ovf8k6UtSMF3c3UT8mQFxcayuoDOH2R/iTdyCU\nNEwv78WhSwC6tldat4HpvnDGZUrJ6hLJV1c6QZdCGXYyKUciK2MVeR5r76RQ4wkh\n4foC0dfH7zqIIFJlG3MZsRQ4FBxCs/g/VJarreYj1l4oPeVOzYbVyiqB0QtTt9JX\nDZslUukY1XOeznlp47BOMcEKK5HI7SXxxoI9yTh86hIn12AHKpsyWD+p0p+WvY8E\n5yoSwdWee1NBoJ+EKYuC7gJcHyxWjI5LtjP72QPvyHfpwH/sLyty/g66y0Rk2ZPw\nQVy0EOik2P2N/zBOY371r3V4iq/AXk1Rxv4eEcHYaByMsJ5HkCl3Y2VkGqW4cSUh\n/WuPho5wlR9eh+6fekkWq/lAgQSsEhDzS9Yv66JvUZeAp/t6hzqZUdVGfUgGKf3/\n0Gt5zkRsvetLO5Fi241wqs6POenKMBfxg7HTgaGZSgDzAgMBAAE=\n-----END PUBLIC KEY-----"}},"a308d13194a921f4327d5b97fcc77b918f462474a196ecd7e8eacff1191786ff":{"keytype":"rsa","keyval":{"public":"-----BEGIN PUBLIC KEY-----\nMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAw/Fq5IBsaTyvNh9bbmKs\nrBfK0pan6DTMN1SUCLy3oa+JoTKzQOHxRvO+B/E1pICRkxqfQI7yTv6hQtDLQt9h\n3d8FbfugYilJ8JzFXS8Pn3iCDM9OMrS8FdnZXEm51wflwNoFSNQ2vGIG2gwJe9hR\nLsDSbQ+B6NA72EmXQWCa+EFyuycwqW57qQUIVsN1pWAMEiSByKl8fu+OMW9Bshtp\nhZGpaFdhkn76Hhdy9BxvHIE6NMbGQvWk1PO0NluyceZQVLaiCWOnk60BsxYdq++Y\nlM5/1XUDyiywDkVF8jE0y275W24AUeDTtD+8A5Ybwcj5JwkYqbuG+zcmNe6gNr99\n002RI4r1CJFd/xUishSrjr9lP1LC8xegDLZ2fr4CkIHK6oCOASrZUUINMbzxAZZi\ng93ipZBYHjz5wosQbsn8gxp/+pYoYgomm/r8n36ubm0UUoLk8ZiA1mu30puBlBJB\nnl/vVaMNJbzXTp3tEqp7gleJx7VXV954B5QV9Lt2Q6uVAgMBAAE=\n-----END PUBLIC KEY-----"}}},"roles":{"root":{"keyids":["8c4f645e35f06c9ed9d8f17eed6de314017eee2c53a833d3690e616ab5420a86"],"threshold":1},"snapshot":{"keyids":["668b06dfd7b657d474740bf0e2f618e80a3476ad5bd15000cfd0db50402280a9"],"threshold":1},"targets":{"keyids":["756ce3a37c8a7a48a306e5f134ce63d3523e9c06f942b9fdd2161dbcafb640d0"],"threshold":1},"timestamp":{"keyids":["a308d13194a921f4327d5b97fcc77b918f462474a196ecd7e8eacff1191786ff"],"threshold":1}},"version":0}'

../.local/lib/python3.4/site-packages/tuf/schema.py:201: FormatError
```

**Comment by dachshund** [comment]
@davedoesdev Looks like a str<->bytes Python 3 kind of bug. There should be an easy for this, but I'm afraid I'm unable to dedicate the time to fix this now, as I have some pressing deadlines :(

In the meantime, you may wish to work around this issue by patching your copy of TUF. If it works, we would appreciate a pull request!

Thanks for letting us know. We hope to issue a fix for this as soon as possible.

**Comment by davedoesdev** [comment]
https://github.com/theupdateframework/tuf/pull/301

**Comment by dachshund** [comment]
Looks good, thanks, @davedoesdev ! My colleague @vladimir-v-diaz is in charge of merging PRs, and I'll leave it to him to merge #301 as soon as he gets back.

Besides this issue, does everything else (most importantly, consistent snapshots) work for you?

**Comment by davedoesdev** [comment]
Yep - consistent snapshots worked on the released version, modulo this issue.
I do have to access these 'private' functions, however:

- `tuf.download._download_file`: I'm actually replacing this with my own version (my module, [dtuf](https://github.com/davedoesdev/dtuf), is storing metadata and targets in a Docker registry so I have to download from the registry instead). It'd be good to have a supported way of plugging in custom download behaviour.
- `tuf.download._check_downloaded_length`: I call this as part of my replacement `_download_file`. It would be nice for this to be public.
- `tuf.client.updater.Updater._ensure_not_expired`: I'm calling this as part of doing initial verification of a downloaded `root.json`, against a supplied root public key. I have to check it's not expired, then call `tuf.sig.verify` having placed the root public key in `tuf.keydb`. You can see the code [here](https://github.com/davedoesdev/dtuf). Is there a better way to do this?

Apologies for the lack of docs on `dtuf` - I'm just about to start them. I've just finished some unit tests, however (in the `test` directory) which exercise `tuf`.

**Comment by dachshund** [comment]
Good to know these issues, @davedoesdev, thanks for letting us know. I'm glad that consistent snapshots are working for you provided we address #301.

I'm afraid I don't immediately know the answer to your question about "Is there a better way to do this?" Hopefully my colleague will be able to answer that soon enough.

In the meantime, please keep stress-testing TUF, and let us know whether there's anything else you think we should fix!

**Comment by davedoesdev** [comment]
How's it looking for a new release?

**Comment by vladimir-v-diaz** [comment]
@davedoesdev 

We uploaded v0.10.0  (pre-release) to PyPI
https://pypi.python.org/pypi/tuf/0.10.0

**Comment by davedoesdev** [comment]
Thanks! My unit tests pass against it so hopefully in a few days I'll be able to release.
Great work, appreciate it.

**Comment by vladimir-v-diaz** [comment]
You're welcome.

FYI: Your other feature requests (access to the "private" functions) will be addressed in the following release, where the `download.py` module is modified to use `requests`.

And let us know when the Docker Registry Bindings are released, we look forward to listing your work on our website.

**Comment by davedoesdev** [comment]
@vladimir-v-diaz @dachshund 

I've now released dtuf:

https://github.com/davedoesdev/dtuf
https://pypi.python.org/pypi/python-dtuf

**Comment by davedoesdev** [comment]
@vladimir-v-diaz good suggestion, appreciate it. I'll make those modifications soon.

**Comment by davedoesdev** [comment]
@vladimir-v-diaz having thought this over, I'm not sure about this. If I override `tuf.client.updater.Updater.download_target()`, I'll end up copy-pasting a lot of code from the existing implementation. So if you fix a bug in there, I'm going to miss it.

**Comment by vladimir-v-diaz** [comment]
Can you please provide the reason(s) for why you need to override `tuf.download._download_file()`?
I suspect it has to do with needing to download registry blobs (that are not specified in metadata?), additional manifests, etc., but I want to first verify with you before I offer another suggestion.
 
Unfortunately, by replacing `download_file()`, you will also lose some of its protections (i.e., prevention of slow retrieval and endless data attacks).  You'd have to make sure to reimplement these protections
in the replaced function.

**Comment by davedoesdev** [comment]
I use `_download_file` to download the TUF metadata and the targets. Everything is stored in the registry.

**Comment by davedoesdev** [comment]
PS I see where you're doing the timeout etc. I'll have a think as to how to incorporate that into `dtuf`/`dxf`.

**Comment by davedoesdev** [comment]
Some things I'm missing:

- Call `_check_content_length` before reading
- Use `tuf.conf.CHUNK_SIZE` (at the moment, `dxf` reads in 8192 chunks)
- Re-use the average download speed check somehow. I'm using `requests` in `dxf` so it may have something.

One suggestion I have for you is to enable different types of connection and to have some interface that connections must implement.

**Comment by vladimir-v-diaz** [comment]
> I use _download_file to download the TUF metadata and the targets. Everything is stored in the registry.

Are you doing anything that _download_file() currently fails to accomplish?  What exactly is different in fetching Docker images that requires modification of these private TUF functions?  I'd like to understand why dtuf/dxf needs to override this function.

Just to make sure we're on the same page, see the following how-to section on downloading TUF metadata and requesting specific targets: https://github.com/theupdateframework/tuf/tree/develop/tuf/client#download-specific-target-file

**Comment by vladimir-v-diaz** [comment]
> One suggestion I have for you is to enable different types of connection and to have some interface that connections must implement.

Ahh, is it because of the connection type?  Would you prefer that TUF use HTTP libraries like `requests` rather than the stdlib?

> I'm using requests in dxf so it may have something.

`requests` is blocking (as in not non-blocking), but it may be possible to prevent endless data + slow retrieval attacks by using timeouts and streaming requests.

http://docs.python-requests.org/en/master/user/advanced/#timeouts
http://docs.python-requests.org/en/master/user/advanced/#streaming-requests

We wanted to also use `requests` but it doesn't support Python 2.6.  We'll add support for it in the future when we drop Python 2.6

**Comment by davedoesdev** [comment]
Fetching from the registry isn't a simple GET request. For manifests, `dxf` verifies its integrity (it is self-signed with a key embedded inside it). It also has to respond to authentication requests (involving a redirect to an auth server).

**Comment by vladimir-v-diaz** [comment]
Thanks for clarifying!

**Comment by davedoesdev** [comment]
I think I'll start by trying to override `_open_connection`, see how far I get.

**Comment by davedoesdev** [comment]
@vladimir-v-diaz here is the latest version which overrides `_open_connection`: https://github.com/davedoesdev/dtuf/blob/master/dtuf/__init__.py#L26

It'd be great to hear what you think.

**Comment by davedoesdev** [comment]
Are there likely to be any breaking changes in 1.0.0?

**Comment by vladimir-v-diaz** [comment]
Yes.  The biggest change is that a repository's delegation structure will resemble a graph.  There will also be tweaks made to consistent snapshots (root.json and snapshot.json are always referenced by their hashes, rather than their version numers) and the format of metadata.
