### ISSUE TITLE
Compact representation of a range of (hashed) delegated target paths

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#249]
Presently, if we delegate the space of hashed target paths, we do it with the [path_hash_prefixes](https://github.com/dachshund/tuf/blob/5f94d5be0d9c2140e440a7076c6ccfa6263864dd/docs/tuf-spec.txt#L606-L614) attribute.

Suppose there are 256 possible hash values of target paths, and 2 delegatees. Then, with the current scheme, the specification would be:

path_hash_prefixes: ["0", "1", "2", "3", "4", "5", "6", "7"]
path_hash_prefixes: ["8", "9", "a", "b", "c", "d", "e", "f"]

When we could just as easily have said:

path_hash_range: ["00", "7F"]
path_hash_range: ["80", "FF"]

We should update the specification to read and write accordingly.

**Comment by trishankatdatadog** [comment]
Closing because, as part of our calculations for [PEP 458](https://www.python.org/dev/peps/pep-0458/), we found that this is not the bandwidth bottleneck.
