### ISSUE TITLE
build: Enable python 3.12

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2499]
Python 3.12 has been released and seems to be supported by GH actions now.

Enable it in:
* GH actions test matrix:  `.github/workflows/_test.yml`
* pyproject language metadata: `pyproject.toml`
* readthedocs build config:  `.readthedocs.yaml`

Change is successful is tests for 3.12 pass and the readthedocs build is green.

(same sort of PR is welcome in https://github.com/secure-systems-lab/securesystemslib but that should not be needed for this one)

**Comment by jku** [comment]
For merging maintainer: The 3.12 tests can be added to branch protection requirements in : https://github.com/theupdateframework/python-tuf/settings/branches

**Comment by MiirzaBaig** [comment]
Can you assign me this issue?

**Comment by I-MirzaBaig** [comment]
Ok!

**Comment by Athul0491** [comment]
If the issue is still open, can you assign this to me?

**Comment by jku** [comment]
Sure I'll remove current assignment since nothing seems to have happened.

I think I won't assign it again but a PR is still very much appreciated: if you're working on it you can leave a comment saying so to notify anyone else. Comments are also welcome if something is unclear

Thanks!
