### ISSUE TITLE
investigate alternative hatchling version pinning 

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2529]
**Description of issue or feature request**:

Investigate if we could pin the hatchling version in a way that dependabot can manage.

Currently we do this in pyproject.toml:
`requires = ["hatchling==1.20.0"]`
And then call install like this:
`python3 -m pip install --constraint requirements/build.txt build`

What if instead we did 
`requires = ["hatchling"]`
and called build like this:
`PIP_CONSTRAINTS=requirements/build.txt python3 -m pip install build`
(with hatchling version added to build.txt)

I think this should work: The environment variable should carry over to the build isolation environment unlike the --constraint flag. 

**Current behavior**:

Dependabot does not update hatchling version.

**Expected behavior**:

Dependabot does update hatchling version when new versions are released

**Comment by lukpueh** [comment]
Neat! Manual updates are definitely not sustainable. I can try this out.

**Comment by joshuagl** [comment]
Very neat suggestion, thanks!
