### ISSUE TITLE
Suggested corrections for repository management tool

### ISSUE THREAD

**Issue by Pankh** [theupdateframework/tuf#253]
First, it is difficult to understand the difference between input and output in the content under the heading [Create root](https://github.com/Pankh/tuf/blob/develop/tuf/README.md#create-root)

Second, the output of repository.status() doesn't match with the documented output.
[Create root - repository.status()](https://github.com/Pankh/tuf/blob/develop/tuf/README.md#create-root)

Third, the expiration date in the documentation should be updated.
[Create timestamp, snapshot, targets](https://github.com/Pankh/tuf/blob/develop/tuf/README.md#create-timestamp-snapshot-targets)

**Comment by vladimir-v-diaz** [comment]
The documentation uses `>>>` for input, `#` for comments, and no symbols for output.

The output of status() in the document was verified to match what is currently printed.

The expiration was set to `>>> repository.timestamp.expiration = datetime.datetime(2080, 10, 28, 12, 8)`
