### ISSUE TITLE
modify paths for generic packaging

### ISSUE THREAD

**Issue by adrelanos** [theupdateframework/tuf#256]
I would like to help getting the "deb/rpm packaging" #129 ticket move forward. Since I don't want to pollute that ticket, I am suggesting a rather huge change here. Let me briefly explain "generic packaging".

-----

Whonix's packages (that mostly contain just scripts, config files and package dependencies) are mostly packaged using "[generic packaging](https://github.com/Whonix/anon-gw-anonymizer-config#generic-packaging)". It's about where files are stored, how the makefile works and distribution specific packaging tools.

In short, files in `etc/...` in root source folder will be installed to `/etc/...`, files in `usr/...` will be installed to `/usr/...` and so forth. This should make renaming, moving files around, packaging, etc. very simple. Packaging of most of Whonix's packages ([list](https://github.com/Whonix)) looks very similar.

The [makefile](https://github.com/Whonix/anon-gw-anonymizer-config/blob/master/Makefile), the [make-helper.bsh](https://github.com/Whonix/anon-gw-anonymizer-config/blob/master/make-helper.bsh) script are the same for any package and other files (such as licensing stuff) look very similar.

This makes packaging and maintenance real simple.

Does that make sense?

-----

We also have a few python packages.

* [example python tool](https://github.com/Whonix/whonix-setup-wizard)
* [example python lib](https://github.com/Whonix/python-guimessages)

Using that method - using the canonical, standard `debhelper` `dh_python2` way - we are able to produce Debian policy conform `.deb` packages, that means [`lintian`](https://lintian.debian.org/) is reporting zero warnings.

-----

Proposal:

You'd need to move files accordingly. Maybe you want several packages? Such as `tuf-shared`, `tuf-server`, `tuf-client`? In that case, create these three folders in the root of TUF's source folder. (Or alternatively split into three git repositories.) Then inside the `tuf-client` folder, add `tuf-client/etc/`, `tuf-client/usr/`, etc. folders accordingly and move files there. Please have a look at the example repositories above to find out where to best place files.

I'd then do my creating a pull request that adds the generic packaging. Can't promise anything, but I think this should be relatively easy. We could also contact [debian-mentors](http://mentors.debian.net/), they got a mailing list and irc channel helping with debian packaging questions.

**Comment by vladimir-v-diaz** [comment]
@adrelanos
Did you get a chance to test [stdeb](https://github.com/astraw/stdeb)?  Is stdeb and the debian build tools (as outlined in Debian's [Guide for Packaging Python Libraries](https://wiki.debian.org/Python/LibraryStyleGuide)) enough to address issue #129?  I would think that our standard directory layout wouldn't be a problem for these tools.

The feature request outlined here is to support Whonix's "generic packaging" scheme.  Correct?
I'm just not sure if you're requesting we change our directory structure on our master branch, or to help with porting the code base to the directory structure required for Whonix.  That is, a TUF w/ "generic package" repository like the whonix-repository tool: https://github.com/Whonix/whonix-repository.

**Comment by adrelanos** [comment]
> Did you get a chance to test stdeb?

Yes. Found it too complicated and confusing. Preferring debhelper dh-python2 method.

> Is stdeb and the debian build tools (as outlined in Debian's Guide for Packaging Python Libraries) enough to address issue #129?

Might be. Can't be of help for stdeb.

> The feature request outlined here is to support Whonix's "generic packaging" scheme. Correct?

Wipe the "Whonix" word. Unrelated to Whonix, which just happens to use "generic packaging" method. It's a suggestion to change the path for the "generic packaging" scheme that would help with packaging for any Debian (and maybe others) based distro.

> directory structure used by Whonix

It's not something to suit Whonix. It's something to suit the "generic packaging" solution.

> whonix-repository tool

That is totally unrelated here. It's just a tool to conditionally populate /etc/apt/sources.list.d/whonix.list or not.

**Comment by adrelanos** [comment]
Looks like no paths are being modified and we're going the dh-python2 packaging (#259 #262) route. Boldly closing this for cleanup, but feel free to reopen.
