### ISSUE TITLE
datetime.utcnow() is deprecated: stop using it

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2572]
[utcnow() reference docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow): 
> Deprecated since version 3.12: Use [datetime.now()](https://docs.python.org/3/library/datetime.html#datetime.datetime.now) with [UTC](https://docs.python.org/3/library/datetime.html#datetime.UTC) instead.

We have 23 uses of `utcnow()` (mostly tests and examples): all seem straight forward to change to `now()` with utc argument

**Comment by Mansur908** [comment]
Hello @jku. Could you please assign this issue to me? Thank you.
