### ISSUE TITLE
Is TUF a library or a collection of tools or both?

### ISSUE THREAD

**Issue by adrelanos** [theupdateframework/tuf#258]
To help with #129... I need to ask...

How do you envision TUF to appear on distributions?

Does TUF provide files that are supposed to be `import`ed, i.e. a python library?

Would you prefer having it installed in `/usr/bin/...`? 
Obviously `/usr/bin/sig.py` wouldn't be a good name. Something like `/usr/bin/tuf-sig`?

Or would it suffice to take the whole `tuf` folder (https://github.com/theupdateframework/tuf/tree/develop/tuf) and to install it's contents to `/usr/lib/tuf`? I.e. so you'd end up with a file `/usr/lib/tuf/sig.py` and so forth?

Applications based on TUF would then call external utilities such as `/usr/lib/tuf/sig.py`?

**Comment by vladimir-v-diaz** [comment]
"How do you envision TUF to appear on distributions?  Does TUF provide files that are supposed to be imported, i.e. a python library?"

Developers of software update systems can download and install the `tuf-0.9.9-py2.py3-none-any.whl` or `tuf-0.9.9.tar.gz` Python distributions so that they can integrate the framework with their software update system.  TUF is a library that is imported on the client side of the software update system.  The Python distribution also includes tools to generate and sign the TUF metadata that is added to the update system's software repository, but the framework does not require code to run on the server side.

The current pip installation steps should help illustrate how the framework is packaged:

``` Bash
$ pip install tuf
```
 This step above installs TUF's pure-python modules.  The software update system's client application may then import the library to perform software updates (import tuf.client.updater)
Importing the framework and requesting updates is outlined [here](https://github.com/theupdateframework/tuf/tree/develop/tuf/client#updaterpy)

```
$ pip install tuf[tools]
```
This step fetches TUF's C dependencies (PyCrypto & PyNaCl) so that repository maintainers can generate & sign TUF metadata.  Example use of the repository tools:

```Python
from tuf.repository_tool import *
repository = load_repository("/path/to/repository")
generate_and_write_ed25519_keypair('/path/to/ed25519_key')
...
repository.write()
```

"Would you prefer having it installed in /usr/bin/...? "
If you would rather avoid pip, then putting all the TUF python modules in /usr/lib/tuf makes sense.  However, you would need the C dependencies for the repository tools to work.  Note: The `tuf.repository_tool` module uses many of the modules imported by `tuf.client.updater`, so we just package them together.  `tuf-0.9.9-py2.py3-none-any.whl` is 192 KB.

**Comment by adrelanos** [comment]
Good news:
PyCrypto is in Debian, apparently. (https://packages.debian.org/search?keywords=python-pycrypto)

Bad news:
PyNaCl is not, apparently? So someone would have to package it for Debian first.

Quite harder than I anticipated.

-----

> Developers of software update systems can download and install the tuf-0.9.9-py2.py3-none-any.whl or tuf-0.9.9.tar.gz Python distributions so that they can integrate the framework with their software update system.

That's something as far I understand, Debian doesn't like. They don't like some application based on TUF (such as in future hopefully: pip), to include third party code:
https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code

(From perspective of pip: TUF is considered third party code.)

Debian wants to avoid code duplication:
https://wiki.debian.org/dedup.debian.net

They would require [that part of] TUF to be packages and installable comparable to python-yaml (https://packages.debian.org/de/jessie/python-yaml).

> If you would rather avoid pip

Well, as per "you", it's not about me personally. Rather Debian policy (and most likely others as well) are very strict. Too bureaucratic and strict for my taste sometimes.

While python-pip is installable from Debian (https://packages.debian.org/search?keywords=python-pip) and while you as a user of Debian, developing our own stuff, are welcome to install stuff using pip, it's different when it comes to packaging. As far I know, in these cases you are forbidden to depend on python-pip to download stuff.

Ironically what could help getting TUF packaged for Debian, would be getting TUF being integrated into pip first. Because when pip cannot be used without anymore, the maintainers of python-pip in Debian would have to package PyNaCl and TUF for Debian. Or if they can't do that for whatever reasons (time, interest, difficulty), at some point python-pip would be removed from Debian. But the latter is rather unlikely, I hope, since pip is quite popular.

Sorry to say, but due to the unexpected difficulty, I might not be able to help as much with packaging as I wanted.

**Comment by vladimir-v-diaz** [comment]
The repository tools do work without PyNaCl, you just lose the option of signing metadata with the Ed25519 signature scheme.  Generating RSA-PSS signatures with PyCrypto is still an option.

Unfortunately, the link you provided for PyCrypto is actually PyCryptopp (Python wrappers for the Crypto++ library).  What we currently support as an option for repository maintainers is [PyCrypto](https://pypi.python.org/pypi/pycrypto/2.6.1)), however, we can also add PyCryptopp to our "configurable crypto library" interface. (PyCryptopp appears to have bindings for Ed25519, AES, RSA signatures, etc., which will work nicely for us.)

For our repository tools it would be nice to eventually support the following libraries (we currently support the first three):

1. PyCA's Ed225519 (pure python, and only used to verify signatures on the client side): https://github.com/pyca/Ed25519
2. PyNaCl (libsodium backend to generate Ed25519 signatures): https://github.com/pyca/pynacl
3. PyCrypto (AES and RSA-PSS signatures): https://github.com/dlitz/pycrypto
4. PyCA's Cryptography (openssl backend)
5. PyCryptopp (Crypto++ backend)

Getting TUF packaged for Debian (today) shouldn't be a problem (the core client stuff is all pure-python and supports Ed25519), it's just that repository maintainers using our tools would have limited options if the PyNaCl, PyCrypto, etc., bindings are unavailable.

**Comment by Ayrx** [comment]
I got someone to kickstart packaging PyNaCl for debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776452

We'll see where it goes.

**Comment by vladimir-v-diaz** [comment]
:+1:

Thanks for making this happen.

**Comment by mithrandi** [comment]
I have just uploaded a python-nacl package, but it will need to go through [NEW](https://wiki.debian.org/NewQueue) processing before it will be available in Debian unstable. Once jessie-backports is open, I can also look at providing a [backport](http://backports.debian.org/) for Debian 8.0 ("jessie").

**Comment by vladimir-v-diaz** [comment]
Thank you, @mithrandi.

I will begin testing `python-nacl` and Terry's upcoming pyca/Cryptography pull request soon after they are available.

**Comment by adrelanos** [comment]
Made good progress on packaging tuf as a lib, so you can import it using `import tuf.client.updater` (#259 and #262).

To get back to the original question... Do you also want users to be able to run `tuf-something` in a terminal? I mean, do you want users to be able to use some of tuf's stuff as tools?

Or do you want users/programs to be able to run something like `/usr/lib/tuf/some-tuf-tool.py` in a terminal?

**Comment by vladimir-v-diaz** [comment]
We can treat `tuf/client/basic_client.py` as a command-line tool.

We used to have a few other command-line scripts, but the repository management tools are now imported or run in the Python interpreter (in interactive mode).  Adding a command-line interface for the repository management tools as been discussed, but this may be done later.  Let's just add `tuf/client/basic_client.py` for now.

**Comment by adrelanos** [comment]
By the way, if the following suffices, then the current packaging (#259 and #262) suffices.

```
/usr/share/pyshared/tuf/client/basic_client.py
```

```
Usage: basic_client.py [options]

basic_client.py: error: "--repo" must be set on the command-line.
```

We learn more about what Debian developers think about this as we progress with #259, #262 and #263 and start a discussion with them.

Okay, my original question in this ticket has been answered. Closeable.

**Comment by vladimir-v-diaz** [comment]
The `basic_client.py` usage output looks correct.  I'm closing this ticket and we'll continue with Debian packaging in #259 and #262.
