### ISSUE TITLE
dh-python2 packaging

### ISSUE THREAD

**Issue by adrelanos** [theupdateframework/tuf#259]
If you don't want to do #256, no problem. To help with #129 ...

Here is the deal:

I would try to come up with a pull request that ships a `Makefile`, a `make-helper.bsh` and a `debian/` folder. It would produce a "lintian clean" (= no issues reported by the Debian policy checking tool) package, using dh-python2, that would simply install all files from the `tuf` folder (https://github.com/theupdateframework/tuf/tree/develop/tuf) to the `/usr/lib/tuf/*` folder. I.e. `/usr/lib/tuf/sig.py` etc.

It would not address the PyNaCl dependency issue that I described here:
https://github.com/theupdateframework/tuf/issues/258#issuecomment-71125998

But this PyNaCl issue cannot be solved within TUF's own repository anyhow.

This work needs to be done at some point anyhow.

How does that sound?

**Comment by vladimir-v-diaz** [comment]
The `debian/` folder + Makefile + make-helper.bsh approach seems reasonable, it is similar to stdeb's `debianize` command that builds a `debian/` folder alongside setup.py.  A pull request would be appreciated.

Although I haven't tried stdeb, according to the documentation it should be simple:
1. Install `stdeb`
2. Navigate to TUF's root folder that contains `setup.py`
3. python setup.py --command-packages=stdeb.command bdist_deb

Step 3 generates Debian source and binary packages.

**Comment by lukpueh** [comment]
Fixed by https://github.com/theupdateframework/tuf/commit/a2532a15424fc667c4423f1795cfb7ea3399ea92. Thanks for the initiative, @adrelanos! Closing here.
