### ISSUE TITLE
SimpleEnvelope._DEFAULT_PAYLOAD_TYPE should be public?

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2598]
ngclient accesses `SimpleEnvelope._DEFAULT_PAYLOAD_TYPE`.

flake8-self linter complains about this, I think correctly. If we use the value from a different module, it should be public

CC @lukpueh for comment

**Comment by lukpueh** [comment]
I suppose I didn't see a reason to expose it to every user of the API. But flake8 is right, that ngclient is also just a user of that API. I'm with with making the variable public.

**Comment by h4l0gen** [comment]
Hi, I would like to work on it. I will create PR. 
Thank you 👍
