### ISSUE TITLE
should build job require prior test job to pass? 

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#2604]
**Description of issue or feature request**:

In #2317 we configured CI/CD tests to [`continue-on-error`](https://github.com/theupdateframework/python-tuf/blob/2d6fc743a487bb172c98a82c9a5a5c733eb134d4/.github/workflows/_test.yml#L36). I cannot remember (or guess from commits/PR/issue messages) why.

Moreover and IIUC this means that the build job, which [`needs`](https://github.com/theupdateframework/python-tuf/blob/2d6fc743a487bb172c98a82c9a5a5c733eb134d4/.github/workflows/cd.yml#L18) the test job to finish, will also trigger, if the tests fail. Is this intended?

See related in-toto/in-toto#732, which fixes the converse issue, where the build job unnecessarily required all test jobs to pass.

**Current behavior**:
build job triggers even if (all) tests fail

**Expected behavior**:
build job should maybe require tests to pass

**Bonus**
The [`experimental`](https://github.com/theupdateframework/python-tuf/blob/2d6fc743a487bb172c98a82c9a5a5c733eb134d4/.github/workflows/_test.yml#L48) setting in the test workflow is currently unused, and could be removed (or used like in the in-toto PR above).

**Comment by jku** [comment]
yeah, good question... I think the intention may have been:

`continue-on-error: ${{ matrix.experimental }}`

as in, allow failure if experimental is set but not otherwise

**Comment by lukpueh** [comment]
Yep, that's what recent GitHub docs show: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-preventing-a-specific-failing-matrix-job-from-failing-a-workflow-run

But we added `experimental` without `continue-on-error`. Could be that we (I?) thought that `experimental` had a special meaning in GHA. But it's actually just a random name.

Anyway, if we decide to require tests to pass prior to build, we can do `continue-on-error: ${{ matrix.experimental }}` as described.

**Comment by jku** [comment]
So I'm thinking I'll refactor this so that 
* with-sslib-main is not part of the matrix or even the workflow
* this way it does not prevent releases etc and the workflow is simpler
* we can add a separate workflow that has a PR trigger so we still get the green/red checkmark -- but it's separate from actual CI checkmark
