### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by Ayrx** [theupdateframework/tuf#261]
I have noticed that tuf doesn't follow PEP 8 in a few areas. Is this a deliberate choice?

**Comment by vladimir-v-diaz** [comment]
It's a deliberate choice.  The [code style guidelines](https://github.com/secure-systems-lab/code-style-guidelines/blob/master/README.md) we follow for the research projects in our lab are based on PEP 8 (two spaces per indendentation probably being one of the differences you noticed immediately).

**Comment by Ayrx** [comment]
Cool. :)
