### ISSUE TITLE
user-agent should maybe mention "python"?

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2631]
User agent set in tuf/ngclient/_internal/requests_fetcher.py is `tuf/5.0.0` -- this looks good but I think should be `python-tuf/5.0.0` instead as it should identify the complete project when visible in an access log.

**Comment by joshuagl** [comment]
💯 yes please

**Comment by h4l0gen** [comment]
Hii @jku @joshuagl, I am new contributor to TUF project. If this issue is available to take on, I would like to work on it. Can you assign it to me. Thank you!

**Comment by jku** [comment]
@h4l0gen thanks! Feel  free to just open a PR. No need to wait for assignments: your comment here should be enough notice.
