### ISSUE TITLE
Make Implementations command/code copy-pastable

### ISSUE THREAD

**Issue by h4l0gen** [theupdateframework/tuf#2637]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
Currently, the [implementation ](https://theupdateframework.readthedocs.io/en/latest/INSTALLATION.html) command/code is not copy-pastable. Giving an `copy` option in top right corner of code's box would address this issue. With this, we can pass the [CNCF assessment criteria](https://github.com/cncf/techdocs/blob/main/assessments/criteria.md#new-user-content).

**Current behavior**:
Not copy-pastable

**Expected behavior**:
Should be copy-pastable.

**Comment by h4l0gen** [comment]
I will create PR for this.

**Comment by h4l0gen** [comment]
@JustinCappos what you think on this. As per last point of [this ](https://github.com/cncf/techdocs/blob/main/assessments/criteria.md#new-user-content)criteria of CNCF assessment, we should have copy-pastable code. And we lack in that [here](https://theupdateframework.readthedocs.io/en/latest/INSTALLATION.html).

**Comment by jku** [comment]
> the implementation command/code is not copy-pastable.

The commands are copy-pastable just fine.

I'm not against adding a copy button if that's easily doable in Sphinx (but adding e.g. new doc build dependencies for this does not sound useful).

**Comment by h4l0gen** [comment]
Okay, I will give it a try, if that's easy to add, I will create PR. Thankyou.
