### ISSUE TITLE
Add CONTRIBUTING.md File to this Repo

### ISSUE THREAD

**Issue by Ayush9026** [theupdateframework/tuf#2638]
Please fill in the fields below to submit an issue or feature request.  The
more information that is provided, the better.

**Description of issue or feature request**:
The repository currently lacks a CONTRIBUTING.md file. This file is essential as it guides new contributors on how to get started with the project, outlines the code of conduct, provides guidelines for submitting issues and pull requests, and includes other relevant information for contributors.

**Current behavior**:
There is no CONTRIBUTING.md file present in the repository, which might lead to confusion for new contributors regarding the contribution process and guidelines.

**Expected behavior**:
A CONTRIBUTING.md file should be added to the root of the repository. This file should include:
- Instructions on how to set up the development environment.
- Guidelines for submitting issues and pull requests.
- Code of conduct.
- Style guides for coding, commits, and documentation.
- Any other relevant information for contributors.

This will help streamline the contribution process and ensure that all contributors

**Comment by h4l0gen** [comment]
Hi @Ayush9026, We already have it in [developer documentation -> contribute ](https://theupdateframework.readthedocs.io/en/latest/CONTRIBUTING.html)section.

**Comment by Ayush9026** [comment]
@h4l0gen okay.

**Comment by lukpueh** [comment]
CONTRIBUTING.md is in the docs/ directory of this repo, which is one of the canonical places according to [GitHub community](https://github.com/theupdateframework/python-tuf/community) standards

**Comment by lukpueh** [comment]
We could add a link to the [README](https://github.com/theupdateframework/python-tuf/blob/68e643566101df4225b04fe86976476f1ccfd3e5/README.md#L56-L58) though, e.g.:


 > - [Developer documentation](https://theupdateframework.readthedocs.io/), including [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) and [instructions for contributors](https://theupdateframework.readthedocs.io/en/latest/CONTRIBUTING.html)

@Ayush9026, what do you think?

**Comment by h4l0gen** [comment]
@lukpueh seems good. @Ayush9026 you would like to add this?

**Comment by Ayush9026** [comment]
Hi @lukpueh sir,

Thank you for the clarification. I agree that adding a link to the README would be very helpful. It would make the CONTRIBUTING.md file more accessible to new contributors who may not immediately think to look in the docs/ directory.

I'll go ahead and update the README to include a link to the CONTRIBUTING.md file, along with a brief description directing contributors to the relevant section of the developer documentation.

Thank you for your support and guidance.

Best regards,
Ayush

**Comment by jku** [comment]
I think specific action items were not found on this attempt so I'm closing for now: The contribution docs are linked from the README already, adding the same links again in another paragraph was not seen as useful.

To be clear, we do welcome improvements in docs as they certainly are not as good as they could be. Thanks for the work you did
