### ISSUE TITLE
Downloading PyNaCl on ubuntu

### ISSUE THREAD

**Issue by asm582** [theupdateframework/tuf#267]
Although the instruction says to download python dev tools that has all libraries, on ubuntu machine has to manually download PyNaCl from the following link:-

https://pypi.python.org/pypi/PyNaCl/
and then run :- 
python setup.py install 

May be i missed something or if not  should be add this to setup section?

**Comment by vladimir-v-diaz** [comment]
We actually have instructions for installing PyNaCl (and other repository management libraries) [here](https://github.com/theupdateframework/tuf#installation-of-optional-requirements-after-minimal-install).

```
$ pip install tuf[tools]
```

**Comment by asm582** [comment]
May be i missed something but i did the following steps:-
sudo  pip install tuf
   32  sudo pip install tuf[tools]
   33  sudo apt-get install python-dev
   34  sudo apt-get install libffi-dev
   35  vim repo.py
   36  python repo.py 

Below is the error output:-
clienttuf@clienttuf-VirtualBox:~/custominstallerbuilder/DEPENDENCIES/softwareupdater$ python repo.py 
Enter a password for the RSA key file: 
Confirm: 
Enter a password for the encrypted RSA file: 
Enter a password for the ED25519 key: 
Confirm: 
Traceback (most recent call last):
  File "repo.py", line 8, in <module>
    generate_and_write_ed25519_keypair('/home/clienttuf/custominstallerbuilder/repository/keystore//ed25519_key')
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_lib.py", line 979, in generate_and_write_ed25519_keypair
    ed25519_key = tuf.keys.generate_ed25519_key()
  File "/usr/local/lib/python2.7/dist-packages/tuf/keys.py", line 311, in generate_ed25519_key
    raise tuf.UnsupportedLibraryError(message)
tuf.UnsupportedLibraryError: The required PyNaCl library is unavailable.

**Comment by vladimir-v-diaz** [comment]
`python-dev` and `libffi-dev` should be installed before `tuf[tools]`.  Does line 32 actually succeed?

**Comment by asm582** [comment]
Yes line 32 succeeded without errors. 
To add even if i redo pip install tuf[tools] after python-dev and libffi-dev are installed it stills asks for PyNaCl library.

**Comment by vladimir-v-diaz** [comment]
Which version of pip are you using?  If it's `pip <= 1.5.6`, you need to use the following commands:

```
$ pip install --no-use-wheel tuf
$ pip install tuf[tools]
```

The extras_require feature doesn't work with pip <= 1.5.6 due to a bug: https://github.com/pypa/pip/issues/1885

**Comment by asm582** [comment]
my current version is:-

clienttuf@clienttuf-VirtualBox:~/custominstallerbuilder/DEPENDENCIES/softwareupdater$ pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

This is because i guess CIB uses the above version which is the default that python gives when we do sudo apt-get install python-pip

I think we need to update this page (https://seattle.poly.edu/wiki/CustomInstallerBuilderInstallation) for CIB to install  version which works using TUF.

**Comment by vladimir-v-diaz** [comment]
pip 1.5.4. should work with TUF.  You just need to use the `--no-use-wheel` option.

`pip uninstall tuf` and then try again.

```
$ pip install --no-use-wheel tuf
$ pip install tuf[tools]
```

You should see  a bunch of C module being installed for PyNaCl and PyCrypto.

**Comment by asm582** [comment]
After re-installing it works. Thanks!
