### ISSUE TITLE
Add CLI to the Repository Management Tools

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#270]
The [repository management tools](https://github.com/theupdateframework/tuf/tree/develop/tuf#repository-management) may either be imported into a Python module or used with the Python interpreter in interactive mode.

Build a CLI on top of the available functions/methods for users that prefer to also use the command-line.  Consider the use cases for the CLI: for simpler repositories?  Support all of the capabilities of the current tools?  The [Go implementation of TUF provides a good example of how the CLI](https://github.com/flynn/go-tuf#cli) should behave and what to support.

**Comment by lukpueh** [comment]
Closing due to uncertain future of TUF cli. Re-visit with #811.
