### ISSUE TITLE
Specification of delegations is confusing

### ISSUE THREAD

**Issue by edsko** [theupdateframework/tuf#271]
Target delegations are defined in Section 4.5 as

```
     { "keys" : {
           KEYID : KEY,
           ... },
       "roles" : [{
           "name": ROLE,
           "keyids" : [ KEYID, ... ] ,
           "threshold" : THRESHOLD,
           ("path_hash_prefixes" : [ HEX_DIGEST, ... ] |
            "paths" : [ PATHPATTERN, ... ])
       }, ... ]
     }
```

with no further definition of what a `ROLE` is, precisely. The natural assumption is that this definition must equal the definition of `ROLE` from Section 4.2:

```
ROLE is a dictionary whose "_type" field describes the role type.
```

but that is _not_ the intended interpretation here I think. At least, looking at the examples, it is intended to be filepath (or possibly a role name).

**Comment by dachshund** [comment]
I agree that the specification is still vague on some important things, and
requires some clarification. It is not yet as clear and rigorous as, say,
an IETF RFC. Thanks for raising these questions, Edsko.

May I ask why you are reading our specification, by the way?

**Comment by edsko** [comment]
We are implementing security for [Hackage](http://hackage.haskell.org/), the [Haskell](https://www.haskell.org/) package server (a close analogue of the Python package server you've implemented), and we are basing our design very closely on TUF. See https://github.com/well-typed/hackage-security for details, although it's still very early stages for us.

**Comment by dachshund** [comment]
Awesome! I think it's super cool that TUF is being ported to Haskell. Let
us know by raising questions such as this how we can help :)

**Comment by dcoutts** [comment]
@dachshund thanks for the encouragement. (@edsko and I are working on this together, background: http://www.well-typed.com/blog/2015/04/improving-hackage-security/)

One thing that I think would help to make the spec easier to understand is to include concrete examples, like those from your python implementation https://github.com/theupdateframework/tuf/tree/develop/examples/repository/metadata

I found looking at those examples clarified several things that are a bit ambiguous in the spec (abstract is fine, but has to be abstract and precise). I wouldn't worry about any loss of flexibility by showing concrete examples, you already make fairly clear where things can be adapted and extended (hash & sig algorithms, extra metadata etc).

**Comment by dachshund** [comment]
Makes sense, @dcoutts ! Thanks for the tip --- we'll certainly be taking this into account :+1:

**Comment by vladimir-v-diaz** [comment]
This issue (issue #271) has been fixed here: https://github.com/theupdateframework/tuf/commit/91b2405ab43f17e321278bed69f483ab5a03b427

Opened issue #273 to address @dcoutts's request of listing example metadata in the specification.
