### ISSUE TITLE
Dealing with "No updater or interposition warning" in TUF logs

### ISSUE THREAD

**Issue by asm582** [theupdateframework/tuf#275]
Opened this issue so that we can avoid configuration error while using TUF with seattle:-

Configuring TUF and seatlle we get "No updater or interposition warning" due the following configuration error:-

1) Make sure we have set the URL in TUF.interposition.json and softwareupdater.py appropriately for instance, we have hosted my current updatesite to http://192.168.1.21/updatesite/  which is nedeed to be configured in tuf.interpostion.json and the softwareupater,py must contain URL where the updated targets are actually present, for instance the updated target files were in the below path http://192.168.1.21/updatesite/targets/.

2)Since in Seattle we copy keys, it gave me the same error for an extra space that was added while pasting the generated keys.

3) If the above configurations are avoided, please keep observing logs the files eventually gets downloaded.

**Comment by vladimir-v-diaz** [comment]
Did you close this issue by mistake?

Are you saying that the current behavior of raising a warning in the log file is inadequate?  Do we need to improve the warning message? (for example, indicate which part of the configuration file is invalid)  Perhaps raising an error makes more sense for a misconfigured `tuf.interposition.json`?

**Comment by asm582** [comment]
Yes i closed it, cause i thought this may be informative. I was about to talk to you offline if we can raise some error regarding misconfiguration as  well...
