### ISSUE TITLE
Verify / Fix Potential Cycles in updater.target()

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#280]
Ensure the depth-first search of targets by the target() method does not lead to cycles.

Verify [these lines](https://github.com/theupdateframework/tuf/blob/develop/tuf/client/updater.py#L2303-L2315) of `_preorder_depth_first_walk()` and create a unit test.

**Comment by dachshund** [comment]
@JustinCappos first noticed this problem.

**Comment by trishankatdatadog** [comment]
It looks like we [fixed](https://github.com/theupdateframework/tuf/blob/530d4a8eef7082d6bcbae6f163bda80b37714893/tests/test_updater.py#L1618) it

**Comment by trishankatdatadog** [comment]
The PR was #326
