### ISSUE TITLE
Ambiguity in spec: should root info be updated when package download fails?

### ISSUE THREAD

**Issue by edsko** [theupdateframework/tuf#281]
Section 5.1 starts with "If it any point in the following process there is a problem ... the root file is downloaded and the process starts over". But it isn't entirely clear to me "the following process" refers to just the check for updates, or whether it also covers actually downloading a target file. I am assuming (and have implemented) the former, but I'm not sure.

**Comment by vladimir-v-diaz** [comment]
The former is correct, the root file is downloaded and the process starts over if any of the other top-level metadata cannot be successfully updated.

Here is the client application workflow, as outlined in section 5.1 of tuf-spec.txt, implemented in Python:
https://github.com/theupdateframework/tuf/blob/develop/tuf/client/updater.py#L563-L669

I'll try to remove the ambiguity from the specification.

**Comment by trishankatdatadog** [comment]
We fixed it in the specification by making updating the root the first thing
