### ISSUE TITLE
Question: how many retries in check for updates?

### ISSUE THREAD

**Issue by edsko** [theupdateframework/tuf#287]
The spec says:

> Note: If at any point in the following process there is a problem (e.g., only
> expired metadata can be retrieved), the Root file is downloaded and the process
> starts over.

What if on the next iteration there is another problem? Should we retry again (with some upper limit)? Or is this intended to be just once?

**Comment by vladimir-v-diaz** [comment]
That's right, retrying again after failing to update the Root file should only happen once to avoid an infinite loop.  In the reference implementation, we raise an error after the second failed attempt: https://github.com/theupdateframework/tuf/blob/develop/tuf/client/updater.py#L652-L669

The bit about avoiding an infinite loop is missing from the spec.

**Comment by trishankatdatadog** [comment]
We use `requests` now to handle downloads, which automatically retries a finite number of times.
