### ISSUE TITLE
Ready to use implementation on Windows?

### ISSUE THREAD

**Issue by ooxi** [theupdateframework/tuf#290]
Are you aware of a ready to use implementation for Windows? Ideally I specify a repository URL and the name of a Windows service. As soon as an update is available the service will be stopped, replaced by the updated version and started again.

**Comment by vladimir-v-diaz** [comment]
I'm not aware of an integration of TUF with Microsoft Windows Update, nor of software that supports the ideal approach you have outlined.  Let us know if you find one, or attempt to implement your outlined approach!

I recommend you give [Notary](https://github.com/docker/notary) (based on TUF) a try.  A demo of Notary is available here: http://www.ustream.tv/recorded/64499822#to01:54:00.  It might be usable for your use case.

If you meant something else, then I'm not sure what you mean by "ready to use implementation."  Can you please clarify?

Integrating TUF with a software update system is covered [here](https://github.com/theupdateframework/tuf/tree/develop/tuf/client#updaterpy), but I'll try to summarize below how integrators are expected to integrate the framework with the Python implementation.

This framework (TUF) is meant to be imported as a library by the software update system.  In your example, the software update system (it must already exist) keeps track of Windows services, and handles stopping and restarting them if an update is available.  You as an integrator would have to import the TUF library into this software update system and make specific calls provided by the framework to check and download updates.

Note:
We have thought about an extension to TUF where legacy updaters (or update systems that cannot be modified to use TUF) are interposed to securely fetch these updates with TUF metadata.  However, this extension isn't available yet.

**Comment by ooxi** [comment]
Ok thanks for the information!
