### ISSUE TITLE
Document the parameters used for RSASSA-PSS signatures

### ISSUE THREAD

**Issue by jawi** [theupdateframework/tuf#296]
The current implementation uses non-default parameters for RSASSA-PSS signatures which should be specified as such to make different clients interoperable. Something like `SHA256withRSA/PSS` might already be sufficient.

**Comment by vladimir-v-diaz** [comment]
We mention which underlying hash function is used with RSASSA-PSS signatures in the reference implementation here: https://github.com/theupdateframework/tuf/commit/cb1591e63da686842ba1e92bec652964786bc3d6

Thanks for opening this issue.
