### ISSUE TITLE
How about if the connection is lost?

### ISSUE THREAD

**Issue by Hanifkhushik** [theupdateframework/tuf#299]
Can any one tell me how TUF deals if during the updating procedure connection is lost

**Comment by Hanifkhushik** [comment]
Please someone reply for this.

**Comment by vladimir-v-diaz** [comment]
If the framework cannot successfully perform an update (this can either be TUF metadata or a package), an exception is raised.  In your case, an `IOError` (socket error) exception is raised for that particular repository mirror.  The framework also protects against slow retrieval of updates, so the exception raised can also be `tuf.SlowRetrievalError`.  See the "Slow retrieval attacks" entry here: https://github.com/theupdateframework/tuf/blob/develop/SECURITY.md#attacks-and-weaknesses

NOTE: In the reference implementation, you may specify one or more repository mirrors from which to download updates.  If a package or metadata file cannot be downloaded from a particular mirror, the exception raised when requesting a file from that mirror is stored in a dictionary.  The next available mirror is attempted next.  If an update cannot be performed from any mirror, a `tuf.NoWorkingMirror` exception is raised.   It is left to the software updater (that has integrated the framework) to determine how to handle to proceed when zero repository mirrors cannot satisfy the update request.  The software updater can log an error, try again later, etc.

**Comment by Hanifkhushik** [comment]
Thank you so much Dear. It really helped me to understand this.

**Comment by vladimir-v-diaz** [comment]
You are welcome.
