### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#306]
* Add instructions for contributors using Mac OS X.

* Update version of virtualenv listed in the instructions.

**Comment by vladimir-v-diaz** [comment]
@akanbrown Have you tried installing and using the tools with Mac OS X?  Did you have any trouble installing the developer headers?  At the moment, we only list instructions for apt.

```Bash
$ apt-get install python-dev
$ apt-get install libffi-dev
```

**Comment by akanbrown** [comment]
I first of all created a virtual environment with `virtualenv`.  Before installing anything, `pip list` outputted the following:
[before.txt](https://github.com/theupdateframework/tuf/files/402853/before.txt)

After running `pip install tuf`:
[aftertuf.txt](https://github.com/theupdateframework/tuf/files/402854/aftertuf.txt)

After running `pip install tuf[tools]`:
[aftertuftools.txt](https://github.com/theupdateframework/tuf/files/402855/aftertuftools.txt)

So, on Mac OS X:
`pip install tuf` installs iso8601 (0.1.11), six (1.10.0), and tuf (0.10.0).
and
`pip install tuf[tools]` installs cffi (1.7.0), pycparser (2.14), pycrypto (2.6.1), and PyNaCl (1.0.1).

I guess this means I don't need to install the headers?

**Comment by vladimir-v-diaz** [comment]
The README has since been updated many times to edit the installation instructions: https://github.com/theupdateframework/tuf/commits/develop/README.rst
