### ISSUE TITLE
tuf.interposition does not respect urllib/urllib2 module semantics

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#31]
Interposing with module B as a module A requires that B completely copies the behaviour of A (sometime even its bugs for backwards-compatibility).

Now, tuf.interposition is interposing as the urllib/urllib2 modules, and it does not completely copy their behaviour.

Examples:
- tuf.interposition does not respect proxy configuration.
- tuf.interposition raises exceptions (e.g. tuf.Error) that the urllib\* modules would never raise.
- tuf.interposition completely ignores custom protocol handlers or openers that the user might set with the urllib\* modules.

For each of these examples and more, we need to think about how to have tuf.interposition gracefully copy their behaviour.

**Comment by lukpueh** [comment]
`tuf.interposition` was removed in https://github.com/theupdateframework/tuf/pull/537. Closing.
