### ISSUE TITLE
Client: When repo provides metadata w/ version < what client already has, that is not logged.

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#316]
https://github.com/theupdateframework/tuf/blob/develop/tuf/client/updater.py#L1710-L1716

It is potentially useful information for the client to know that the repo they are communicating with has provided a metadata file older than what the client already has. In this case, either the mirror is outdated or malicious.

Currently, the behavior is identical to what happens if the version number is the same - which is to say, largely, nothing. (Nothing is updated. No exceptions are raised.)

**Comment by JustinCappos** [comment]
Good catch.  We should fix this.

**Comment by vladimir-v-diaz** [comment]
We should now log or raise an exception for replayed metadata: https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L2022-L2064
