### ISSUE TITLE
Do we really want to match and transform URL paths with regular expressions?

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#32]
Presently, we allow tuf.interposition users to [match and transform URL paths with regular expressions](https://github.com/akonst/tuf/tree/2aea94c00945e5d28ceeb1cfbe295ae2aa433bd9/tuf/interposition#matching-and-transforming-url-paths-with-regular-expressions).

There are a few use cases for this feature:
- Users mean "/path/to/directory/index.html" instead of "path/to/directory/".
- Users may want TUF to interpose for certain paths only.For example, for the domain "pypi.python.org", we may want to interpose for paths beginning with "/simple" or "/package", but not for paths beginning with "/search" because "/search" is a path for a web service.

The question is: more functionality is nicer for the developer, but will it affect default TUF security? For example, the user may match or mismatch URL paths against her intentions.

The first use case has a simpler fix where we simply get TUF to generate a duplicate target for the key "/path/to/directory/" when it sees files of the form "/path/to/directory/index.html". However, this fix does not handle the second use case.

**Comment by lukpueh** [comment]
`tuf.interposition` was removed in https://github.com/theupdateframework/tuf/pull/537. Closing.
