### ISSUE TITLE
Can I use the tuftools without using password for the keys?

### ISSUE THREAD

**Issue by codefx9** [theupdateframework/tuf#329]
Hi,
Is it possible to use tuftools without using password for the private keys?

Thanks.

**Comment by vladimir-v-diaz** [comment]
Unfortunately, we require a passphrase to encrypt/decrypt the private keys.  We can add an option to allow key files to be saved in plaintext.  Is this a feature you'd like?

**Comment by codefx9** [comment]
An option to not use password will be great. Then I can make the process unattended.

**Comment by vladimir-v-diaz** [comment]
Oh, if you want the process to be unattended you have the option of supplying the password as an argument.  For example:

```Python
# Import an existing private key.  Importing a private key requires a password, whereas
# importing a public key does not.
>>> rsa_private_key = import_rsa_privatekey_from_file("/path/to/key", password='my_password')
>>> ed25519_private_key = import_ed25519_privatekey_from_file("/path/to/key", password='my_password')
```

You are only prompted for a password (via command-line input) if the password argument is not given.

**Comment by codefx9** [comment]
Thanks. Passing `password` parameter solved my issue.
