### ISSUE TITLE
Repository structure mismatch

### ISSUE THREAD

**Issue by codefx9** [theupdateframework/tuf#330]
Hi,
I am trying to create a tuf repository using `tuftools` and using https://github.com/flynn/go-tuf to download binaries from the repository. But repository created by tuftools does neither match format used by go-tuf nor match the format in the tuf documentation. I saw 2 issues:

* `metdata.json` files should be at the top level.
* client folder seem to be have more than just root.json file when created via `create_tuf_client_directory()`

Thanks.

**Comment by vladimir-v-diaz** [comment]
We are in the process of making modifications to the format and organization of TUF metadata in v1.0 of the framework, and are aware of the inconsistencies with the implementation and specification.  You may test the latest v1.0 modifications [here](https://github.com/theupdateframework/tuf/pull/326), but please be aware that we are still reviewing and updating the pull request.

In addition, there are slight differences between go-tuf and our implementation.  These differences occur in parts of the framework that are not explicitly covered in the specification.  For example, the format of encrypted key files, how the client folder is organized, etc.

Once the 1.0 specification is finalized, I can enumerate the cases where our implementations differ.  However, the format, loading, and updating of metadata should eventually match in both implementations.  The go-tuf and Notary folks have been doing a good job keeping their implementations in sync.

**Comment by codefx9** [comment]
Thanks @vladimir-v-diaz . https://github.com/flynn/go-tuf/blob/master/client/interop_test.go#L31 interop_test from go-tuf package solves problems for me.
