### ISSUE TITLE
Packaging TUF for Debian

### ISSUE THREAD

**Issue by HulaHoopWhonix** [theupdateframework/tuf#336]
Can you please consider submitting a TUF package to Debian? I know that projects like Tor Browser and downstream privacy distros like TAILS and Whonix can [benefit](https://lists.torproject.org/pipermail/tor-dev/2016-June/011050.html) a lot from a TUF repository because conventional packaging is not an option.

**Comment by vladimir-v-diaz** [comment]
There still remains one issue (related to lintian and external code) to address in PR #262.
We have made a request to the authors of some of vendor'd packages and dependencies to also have them packaged for Debian or made available elsewhere.  I'll keep you updated on any progress.

**Comment by lukpueh** [comment]
See discussion in #263 for the current status of tuf in debian. Closing here.
