### ISSUE TITLE
high cpu usage on download

### ISSUE THREAD

**Issue by julianhille** [theupdateframework/tuf#338]
Im trying to have tuf on a device which is not very powerful.
It is an arm v7 with max 1ghz.

The cpu load was very high for the time the repository updates i found the cause to be the downloading while loop.

Normal update of a repository with one mirror. And nothing to update.

```
real	0m13.169s
user	0m9.796s
sys	0m0.600s
```

After adding [here](https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L318) 
    
    time.sleep(0.05)

The time where nearly the same but my CPU had enough power to process other things.

```
real	0m13.686s
user	0m2.840s
sys	0m0.352s
```

**Comment by SantiagoTorres** [comment]
> ```
> 
> After adding [here](https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L318) 
>     
>     time.sleep(0.05)

Also, it seems that there are some logger calls commented out?

https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L324
https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L345-L346

I think it's worth cleaning up now that we're at it.

Thanks,
-Santiago.

**Comment by vladimir-v-diaz** [comment]
What happens if you increase the chunk size?
https://github.com/theupdateframework/tuf/blob/develop/tuf/conf.py#L79-L80

Is there a substantial improvement in this case?

**Comment by julianhille** [comment]
I didn't expect to see an improvement and i didn't.
I doubled the CHUNK_SIZE and had these:

```
real	0m13.250s
user	0m9.984s
sys	0m0.656s
```

i also halve it:

```
real	0m12.762s
user	0m9.676s
sys	0m0.552s
```

So this does not seem to change anything.

**Comment by vladimir-v-diaz** [comment]
I'll take a closer look and try to determine why that while loop might be slow.
I tested an update example on my machine (Intel® Core™ i5-4210U CPU @ 1.70GHz × 4 ) and got the following times:

> real	0m3.166s
> user	0m3.142s
> sys	0m0.024s

However, I used [this](https://github.com/vladimir-v-diaz/tuf/tree/keyids_multihash_algorithms/tests/repository_data/repository/metadata) repository.  My client script performed a refresh() of top-level metadata (only timestamp.json was downloaded, verified, and found to be up to date).

**Comment by SantiagoTorres** [comment]
On Mon, Jun 27, 2016 at 02:14:30PM -0700, Vladimir Diaz wrote:
> I'll take a closer look and try to determine why that while loop might be slow.
> I tested an update example on my machine (Intel® Core™ i5-4210U CPU @ 1.70GHz × 4 ) and got the following times:
> 
> > real	0m3.166s
> > user	0m3.142s
> > sys	0m0.024s
> 
> However, I used [this](https://github.com/vladimir-v-diaz/tuf/tree/keyids_multihash_algorithms/tests/repository_data/repository/metadata) repository.  My client script performed a refresh() of top-level metadata (only timestamp.json was downloaded, verified, and found to be up to date).
> 

I'm curious, is this armv7 machine monocore? is it being tested on a
local network?

My assumption is that with multicore machines the process can be
bound to a single core while the rest figure everything out.

The sleep call might be just yielding early, so the machine can do
something else.

Thanks,
-Santiago.

**Comment by julianhille** [comment]
> I'm curious, is this armv7 machine monocore? is it being tested on a
> local network?

Yes and yes.

This is a normal case with python or with nearly every other coding language. If you do a while loop doing nothing you have a high cpu usage. So its quite common case. 

The code just walks through the loop over and over again without giving back resources.

**Comment by SantiagoTorres** [comment]
On Tue, Jun 28, 2016 at 01:25:34AM -0700, Julian Hille wrote:
> > I'm curious, is this armv7 machine monocore? is it being tested on a
> > local network?
> 
> Yes and yes.
> 
> This is a normal case with python or with nearly every other coding language. If you do a while loop doing nothing you have a high cpu usage. So its quite common case. 
> 
> The code just walks through the loop over and over again without giving back resources.

This is what I thought, with regular network latency I'm assuming that
the recv() call should block the process and yield the processor to
others in the system. With such low latency this is not the case.

I'm assuming that the right way to go is to add a loop that yields the
processor (e.g., sleep(0)) so that this doesn't happen.

**Comment by vladimir-v-diaz** [comment]
Okay, I'll go ahead and add a time.sleep(0.05) at the top of the loop to
give back resources.

Previously:

real    0m3.169s
user    0m3.137s
sys    0m0.035s


Now:

real    0m3.194s
user    0m0.169s
sys    0m0.020s


--
vladimir.v.diaz@gmail.com
PGP fingerprint = ACCF 9DCA 73B9 862F 93C5  6608 63F8 90AA 1D25 3935
--

**Comment by SantiagoTorres** [comment]
On Tue, Jun 28, 2016 at 08:19:08AM -0700, Vladimir Diaz wrote:
> Okay, I'll go ahead and add a time.sleep(0.05) at the top of the loop to
> give back resources.
> 
> Previously:
> 
> real    0m3.169s
> user    0m3.137s
> sys    0m0.035s
> 
> 
> Now:
> 
> real    0m3.194s
> user    0m0.169s
> sys    0m0.020s

I think that sleep with 0 as a parameter would just "yield". I'm not
sure; 0.05 should also the trick.

Thanks!
-Santiago.

**Comment by vladimir-v-diaz** [comment]
I tried with an argument of 0 and there wasn't much of a difference.

real	0m3.177s
user	0m2.889s
sys	0m0.288s

**Comment by vladimir-v-diaz** [comment]
Note: I removed the commented logging messages.  They previously flooded the logging file.

**Comment by vladimir-v-diaz** [comment]
@julianhille 
Thanks for reporting this issue.

**Comment by julianhille** [comment]
You're welcome.

**Comment by julianhille** [comment]
Im just curious but when / how will this be fixed?

**Comment by vladimir-v-diaz** [comment]
It was fixed in a pending pull request, but I went ahead and added the fix
in the "develop" branch.  It was fixed in the way it was discussed in the
issue/ticket.

--
vladimir.v.diaz@gmail.com
PGP fingerprint = ACCF 9DCA 73B9 862F 93C5  6608 63F8 90AA 1D25 3935
--

**Comment by julianhille** [comment]
thank you for quick response. I close this as it is in the dev branch.
