### ISSUE TITLE
Need support for multi-group / multi-threshold signing

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#346]
Currently, TUF delegations are limited to requiring a threshold number of signatures from one group of keys. Sometimes, a repository manager may want to provide a more elaborate set of requirements for who must sign a set of files.

Suppose there is a directory of targets in the repository that should be signed **both** by two keys from group A (developer keys, say) **and** by a key from group B (a change manager's key, say). That (requiring X keys out of group A and Y keys out of group B) is not currently possible in TUF.

An addition to the TUF spec is warranted to allow for this kind of complex trust arrangement.

**Comment by awwad** [comment]
[Signing Groups](https://gist.github.com/ecordell/a3f7925d12a37ca635209913a2e0a786) was a proposal put forward as a way of solving this problem and allowing this sort of multiple-constraint setup.

**Comment by awwad** [comment]
We have **[an alternative design](https://gist.github.com/awwad/07bcb8a576887cc0973f3067f83df3b3)** that should be flexible enough to address these concerns as well as a particular requirement for another project using TUF (Uptane).

The solution in the linked gist adds a new "MultiRoleDelegations" list to the "delegations" dictionary in Targets metadata. Please see that for more details.

**Comment by awwad** [comment]
Does this scheme suit your purposes, @ecordell?

**Comment by ecordell** [comment]
@awwad Looks fantastic to me! As far as I can tell we get all properties we wanted from signing groups from that proposal, with the additional benefit of reducing the chance for races.

**Comment by awwad** [comment]
[Alternative, normalized design proposal](https://gist.github.com/awwad/c10c251be3cf8e4bc3b52f63a1fa63bf), with roles and delegations fully decoupled. 

This should be easier to read than the previous and should lead to cleaner code. Delegations occur only in one place, and "roles" becomes similar to "keys": a resource for the delegations themselves, rather than one of two places delegations can be specified.

**Comment by awwad** [comment]
MRDs should probably be identifiable individually. Since they don't have names and there's no unique field at present, there's no means of specifically modifying one.

Could:
- Add a function to revoke all delegations from role X to role set [A, B, C] (so that modifying the delegation would take the form of revoking it and adding again). One problem with this is that it would mean that managing the order of delegations would be more of a nuisance (remove many, add back).
- Or add unique IDs to the MRDs, returning them from repository_tool.multi_role_delegate(), and altering functions like add_restricted_paths so that they can take the IDs. One problem with this is that it would mean that the metadata would be a little less deterministic.

**Comment by vladimir-v-diaz** [comment]
I'm closing this issue since [TAP 3](https://github.com/theupdateframework/taps/blob/master/tap3.md) (multi-role delegations) now supports this feature.
