### ISSUE TITLE
Wrong filenames given to be generated 

### ISSUE THREAD

**Issue by julianhille** [theupdateframework/tuf#347]
In line https://github.com/theupdateframework/tuf/blob/develop/tuf/repository_lib.py#L2163
it seems that the timestamp should be tested, but instead the snapshot filename is given to the function.
This seems like a copy and paste error from the part above this one.

    signable, snapshot_filename = \
      _generate_and_write_metadata('timestamp', snapshot_filename, False,
                                   targets_directory, metadata_directory,
                                   False, filenames)

**Comment by vladimir-v-diaz** [comment]
Good catch.  Thanks for reporting this issue.
Fixed in https://github.com/theupdateframework/tuf/pull/348
