### ISSUE TITLE
Add ECDSA to spec

### ISSUE THREAD

**Issue by titanous** [theupdateframework/tuf#355]
While I'd love to only use Ed25519 for everything, there is a lack of support in cryptographic smartcards/HSMs for Ed25519. Many devices do however support ECDSA, including the Yubikey 4.

I think the specification should include support for ECDSA keys and signatures. The most common will be the NIST P-256 curve signing SHA-256 hashes.

I propose the addition of a new key type and signature method: `ecdsa-sha2-nistp256` (uses SHA-256 for hashing). This is [used in OpenSSH](https://github.com/openssh/openssh-portable/blob/master/PROTOCOL) and specified in [RFC 5656](https://tools.ietf.org/html/rfc5656). I don't think there is any need for signature algorithm agility here, so the key type and signature method would be the same for simplicity.

**Comment by titanous** [comment]
We implemented this in flynn/go-tuf#98. Any thoughts before it gets rolled out into the wild?

**Comment by vladimir-v-diaz** [comment]
We are generally open to supporting new key types. This looks good to me.  I'll go ahead and revise the specification.  The Python implementation will also be updated to support this key type,

**Comment by vladimir-v-diaz** [comment]
PR to support ECDSA keys and signatures (in the reference implementation) submitted here: https://github.com/secure-systems-lab/ssl_crypto/pull/4

Note: crypto-related modules have been moved to a separate GitHub repository.

**Comment by vladimir-v-diaz** [comment]
ECDSA has been added to the specification in https://github.com/theupdateframework/tuf/pull/498 and implemented in https://github.com/secure-systems-lab/securesystemslib/pull/18.
