### ISSUE TITLE
[spec] Description of the snapshot role metadata format does not match example metadata

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#364]
The description of the snapshot role metadata format does not match the example metadata in [Section 4.4 of the TUF spec](https://github.com/theupdateframework/tuf/blob/0dac8e7b19272ecee365c7e2b4bdaa2fd68c0ee8/docs/tuf-spec.txt#L631-L659).

It should say that the version number of every target metadata file must be listed.
For the root metadata file, its version number, hashes, and length must be listed.

**Comment by vladimir-v-diaz** [comment]
The specification has been updated [here](https://github.com/theupdateframework/tuf/commit/fbd901422f939bb4613d79f930c6614d26058520) to match the new format
