### ISSUE TITLE
PEP8 / flake8 checks

### ISSUE THREAD

**Issue by julianhille** [theupdateframework/tuf#368]
i'd like to see coding conventions to be applied and tested automatically with tox.ini

**Comment by vladimir-v-diaz** [comment]
I like this request (we've discussed using flake8 in the past), although the coding convention wouldn't be PEP8 exactly.

We use [these](https://github.com/secure-systems-lab/code-style-guidelines#code-style-guidelines) code style guidelines.

**Comment by vladimir-v-diaz** [comment]
We now use [Pylint](https://www.pylint.org/) and [Bandit](https://wiki.openstack.org/wiki/Security/Projects/Bandit) for automatic static code analysis.  See our Travis CI configuration:
https://github.com/theupdateframework/tuf/blob/develop/.travis.yml
