### ISSUE TITLE
lock the repository if update / download running

### ISSUE THREAD

**Issue by julianhille** [theupdateframework/tuf#369]
The repository should be locked while updating so that not two concurrent processes do not change it at the same time.

**Comment by JustinCappos** [comment]
This is something we are leaving up to the repository developers.  Yes,
this needs to happen, just like one needs to serve content in some way
(e.g., using HTTP or FTP).  We don't prescribe a specific way to do this
and leave it up to the repository implementers.

**Comment by julianhille** [comment]
I thought it would just be very easy to add a flock to "the_repository_dir/.lock" with an configurable time_delta when to reclaim the lock if a process before may have been killed or cancelled and the flock file still exists.

**Comment by julianhille** [comment]
At least we should add a note to the readme that concurrent processes may harm the repo and that  the lock is up to the repository maintainer?

Just for completeness im talking about the update client :>

**Comment by JustinCappos** [comment]
Ah, sure.  We should update the docs in both the client and repository to make this clear.

@vladimir-v-diaz: can you take a look at this and ensure this is clear?

**Comment by trishankatdatadog** [comment]
This is connected to #49

**Comment by mnm678** [comment]
#972 added an explanation of this limitation to the readme.
