### ISSUE TITLE
Backtracking Documentation Missing

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#371]
The backtrack feature of normal delegations is not documented in the TUF specification (and should be). It's also not described in tuf/client/updater.py. It's only [discussed briefly in the repository tool code](https://github.com/theupdateframework/tuf/blob/fbc1265170dd3ff97e9849b4789e5f115da75d2d/tuf/repository_tool.py#L2121-L2130).

(Chanced upon this while scribbling a quick TAP for pinned delegations)

**Comment by vladimir-v-diaz** [comment]
The backtracking feature (called "terminating" now) has now been added to the specification:
https://github.com/awwad/tuf/blob/36dbb7b8a800dab407fe9ab961155ef0a6d9f7c9/tuf/client/updater.py#L281-L298
