### ISSUE TITLE
What does the HASH field indicates for

### ISSUE THREAD

**Issue by HuKeping** [theupdateframework/tuf#373]
Hi there,

Does it indicates the checksum of singed metadata or unsigned one?

For example, the signed timestamp metadata file is 
```
{
   "signatures": [
    {
     "keyid": "1a2b4110927d4cba257262f614896179ff85ca1f1353a41b5224ac474ca71cb4", 
     "method": "ed25519", 
     "sig": "90d2a06c7a6c2a6a93a9f5771eb2e5ce0c93dd580bebc2080d10894623cfd6eaed
             f4df84891d5aa37ace3ae3736a698e082e12c300dfe5aee92ea33a8f461f02"
    }
   ], 
   "signed": {
    "_type": "Timestamp", 
    "expires": "2030-01-01T00:00:00Z", 
    "meta": {
     "snapshot.json": {
      "hashes": {
       "sha256": "c14aeb4ac9f4a8fc0d83d12482b9197452f6adf3eb710e3b1e2b79e8d14cb681"
      }, 
      "length": 1007,
      "version": 1
     }
    }, 
    "version": 1
   }
   }
```

The sha256 `c14aeb4ac9f4a8fc0d83d12482b9197452f6adf3eb710e3b1e2b79e8d14cb681` is the checksum of signed snapshot.json or unsigned one(without the signatures part)?

**Comment by vladimir-v-diaz** [comment]
Hello, @HuKeping 

The checksum is of the entire file.  In the example listed, it would be for the `snapshot.json` file.
$ sha256sum snapshot.json
c14aeb4ac9f4a8fc0d83d12482b9197452f6adf3eb710e3b1e2b79e8d14cb681  snapshot.json

**Comment by vladimir-v-diaz** [comment]
Any signature listed in the `signatures` field is for the `signed` part of that metadata.

**Comment by HuKeping** [comment]
Thanks @vladimir-v-diaz !

**Comment by HuKeping** [comment]
FYI, the spec calls both the signed and unsigned metadata as xxx.json. Take root.json as an example

https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L518

https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L554

**Comment by vladimir-v-diaz** [comment]
Thanks for bringing this to our attention.  I agree that the specification can be clearer on what is signed and what is considered the metadata file.  I've tried to address this issue [here](https://github.com/theupdateframework/tuf/commit/3ab08e52f6b745546b65e404c06f832563c36cb7)

**Comment by HuKeping** [comment]
@vladimir-v-diaz  Thanks for the clean up!
