### ISSUE TITLE
RSA de-serialization is available using pyca-cryptography

### ISSUE THREAD

**Issue by SantiagoTorres** [theupdateframework/tuf#375]
I was reviewing the key-loading code for TUF and I noticed that pyca-cryptography uses pycrypto to de-serialize the keys. This doesn't seem to be necessary anymore, [as pyca-cryptography supports loading now](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/rsa/#key-loading).

I see that this was left as a [TODO](https://github.com/theupdateframework/tuf/blob/develop/tuf/pyca_crypto_keys.py#L531) throughout the module.

**Comment by vladimir-v-diaz** [comment]
This was added [here](https://github.com/vladimir-v-diaz/tuf/commit/d75d25a4e667903758dd43b8f9254cc49f28e381), but I haven't merged it into "develop" yet.

**Comment by vladimir-v-diaz** [comment]
Support for RSA de-serialization how now been merged with "develop": https://github.com/theupdateframework/tuf/pull/379/commits/d75d25a4e667903758dd43b8f9254cc49f28e381
