### ISSUE TITLE
Spec Version should be included in the signed metadata

### ISSUE THREAD

**Issue by endophage** [theupdateframework/tuf#377]
On the basis that there are significant changes, proposed and actual, to the spec since inception, a field indicating the version of the spec a TUF repo is based on should be included somewhere. I'd suggest the root.json is the most appropriate place for it. This will greatly help at the implementation level with identifying things like whether the JSON should include the `Private` field when calculating key IDs, whether to use `<version>.<role>` or `<checksum>.<role>`, etc...

**Comment by JustinCappos** [comment]
Sure, we should add this.

Note: We're finalizing 1.0 now and now have an official process for
proposing changes to TUF (
https://github.com/theupdateframework/taps/blob/master/tap1.md ).  So the
churn should be much less in the future.

**Comment by endophage** [comment]
Great! Seems like this passes the small test re. "Once the champion has asked the TUF community whether an idea has any chance of acceptance" so I'll put together a TAP and send it to the list.

**Comment by vladimir-v-diaz** [comment]
[TAP 6](https://github.com/theupdateframework/taps/blob/master/tap6.md) was created and accepted, and implemented in https://github.com/theupdateframework/tuf/pull/487.
