### ISSUE TITLE
Validating root.json

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#380]
Suppose that a repository has signed two consecutive versions of root.json as follows:

1.root.json
    threshold = 1
    trusted keys = key1
    signatures = key1.sig

2.root.json
    threshold = 2
    trusted keys = key2, key3
    signatures = key1.sig, key2.sig
(note: 2.root.json no longer lists key1 in its metadata, and is not signed by key3)

2.root.json is signed by key1 to satisfy the requirement that 2.root.json must be signed by a threshold of keys trusted by 1.root.json.

Should clients ensure during updating that 2.root.json is valid on its own?  In this example, 2.root.json can be validated by clients that have a copy of 1.root.json, however, 2.root.json would be considered invalid by clients that have only seen 2.root.json.  The second version of root would also fail to load successfully from disk (if the client validates its signatures).

Should the update from 1.root.json to 2.root.json fail in this scenario?

Clients should certainly verify that 2.root.json is valid on its own.  The update process should fail with a descriptive exception message.  We need to verify that this is the case in light of the recent changes made to the update process.

**Comment by JustinCappos** [comment]
I would be fine with rejecting in this case.  I do not see a reason for
this state to be desirable.  I'm happy to hear other opinions there is
disagreement...

**Comment by awwad** [comment]
This would be a matter of helping to protect repository maintainers from themselves.

It's of marginal utility but I agree that such a check (root valid per itself) should probably be performed, assuming it doesn't make a mess of the code to do so. It should be commented clearly.

I think there's a decent argument that if we do this it should be in the spec, but... it's so minor that it might just be noise.

**Comment by vladimir-v-diaz** [comment]
The client must now verify that the Root file is:

> signed by: (1) a threshold of keys specified in the trusted root metadata file (version N), and (2) a threshold of keys specified in the new root metadata file being validated (version N+1).

See subsection 1.3 of the specification's client workflow.
https://github.com/theupdateframework/specification/blob/c41be98adb84e9008ac68191834d2f0cca2620b4/tuf-spec.md#5-detailed-workflows
