### ISSUE TITLE
Partially written metadata and consistent files

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#393]
Reported by @FelixWang1994 

I notice there may be some mistakes in https://github.com/theupdateframework/tuf/blob/0ce016b7b19a0fc15443eed657a90246ec5df0aa/tuf/repository_lib.py#L239-L260
We may encounter into this "else" branch because of two situations:
1、If 'rolename' is a delegated role, then this is fine.
2、If 'rolename' is a top_level role and partially signed is allowed, then there may be a problem. Firstly, even if this is partially signed, can we directly write them into disk? Secondly, we do not need to call "write_metadata_file" with explicitly set "consistent_snapshot" true. The reason is the same as why we open issue https://github.com/theupdateframework/tuf/issues/391

**Comment by vladimir-v-diaz** [comment]
> If 'rolename' is a top_level role and partially signed is allowed, then there may be a problem. Firstly, even if this is partially signed, can we directly write them into disk?

Can you elaborate on what you mean by "can we directly write them into disk?"  I think partially signed metadata can be written to disk.  We'd like to support this so that multiple people can edit metadata and attach signatures independently.  The repository tool should be able to load partially signed metadata from disk (it is marked as partially loaded by the repository tool).  Note that metadata is first written to a staged directory before it is moved to the "live" repository.  Clients are not expected to fetch partially written metadata, as they will be rejected as unsigned metadata.

> Secondly, we do not need to call "write_metadata_file" with explicitly set "consistent_snapshot" true. The reason is the same as why we open issue #391

Are you saying that the first write_metadata_file() call in the following snippet should specify just `consistent_snapshot` and not `consistent_snapshot = True`?

```Python
# 'rolename' is a delegated role or a top-level role that is partially
  # signed, and thus its signatures should not be verified.
  else:
    signable = sign_metadata(metadata, signing_keyids, metadata_filename)
    _remove_invalid_and_duplicate_signatures(signable)
   
    # Root should always be written as if consistent_snapshot is True (i.e.,
    # <version>.root.json and root.json). 
    if rolename == 'root':
       filename = write_metadata_file(signable, metadata_filename,
                           metadata['version'], compression_algorithms,
                           consistent_snapshot=True)
    
    else: 
      filename = write_metadata_file(signable, metadata_filename,
                          metadata['version'], compression_algorithms,
                          consistent_snapshot)

return signable, filename
```

I think if we don't set `consistent_snapshot` to True (regardless of what was passed in by the caller),
then we will not write `<version>.root.json` to disk if `consistent_snapshot` = False.  We must always write `<version>.root.json` to disk to support root chaining.  The snippet of code above is only executed for metadata that should be partially written (no other writes of Root should have occurred at this point).

**Comment by FelixWang1994** [comment]
Thanks for your explain. Both answers are making sense. I didn't realize that we should always write `<version>.root.json` to disk.

**Comment by vladimir-v-diaz** [comment]
No problem!  Okay, I'm closing this issue since it should be possible to write partially signed consistent metadata.
