### ISSUE TITLE
Minor code doc issue: Misleading comments in download.py

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#409]
https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L197

Presumably, _download_file once checked (or was intended to check) file hashes: there is a [comment there](https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L197) to that effect. It does not do this; hashes are checked by a function that processed the value returned from _download_file (tuf.client.updater._get_file() via tuf.client.updater.verify_target_file).

This should be clarified in [that line](https://github.com/theupdateframework/tuf/blob/develop/tuf/download.py#L197). (Either remove mention of hashes or indicate that the caller should validate hashes.)

**Comment by vladimir-v-diaz** [comment]
The _download_file() docstring now reads:
https://github.com/theupdateframework/tuf/blob/8da05bba3a1226e3f9058df5a0ea46ee54fe1feb/tuf/download.py#L195-L199

Tip:  When providing GitHub links to source lines, you should link to a permanent version of the file.  What I usually do is enter 'y' in the GitHub browser window to generate these links.
https://help.github.com/articles/getting-permanent-links-to-files/
