### ISSUE TITLE
Bug in roledb use of repository_name in get_role_paths and get_delegated_rolenames

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#413]
[Here](https://github.com/theupdateframework/tuf/blob/develop/tuf/roledb.py#L881) and [here](https://github.com/theupdateframework/tuf/blob/develop/tuf/roledb.py#L945), there are calls from roledb functions to _check_rolename() that do not employ the repository_name argument, even though the functions they are being called from accept a repository_name argument and are thus intended to operate with support for multiple repositories.

The immediate effect is that get_delegated_rolenames and get_role_paths do not correctly function when using multiple repositories: they will always pull from the default repository instead.

I'm fixing this in awwad/tuf:pinning (just [this](https://github.com/awwad/tuf/commit/6687a375e3f73dc088d97b79c8b729efd2eb6637) and [this](https://github.com/awwad/tuf/commit/53217bd9fc3425cec8ca6d6bb754c49e3fa80d60) commit), along with the other fixes for full TUF support of multiple repositories. You may want to fix it here as well, since it's easy and it may be a little while before my TUF fork is merged.

**Comment by vladimir-v-diaz** [comment]
Thanks for reporting this issue.

Fix provided here: https://github.com/theupdateframework/tuf/pull/415/files?w=1
