### ISSUE TITLE
JSON Web Signature

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#43]
Following Daniel Holth's suggestion, investigate how [JSON Web Signature](https://tools.ietf.org/html/draft-ietf-jose-json-web-signature) would fit with TUF.

According to Monzur Muhammad: "He mentioned that it was more secure than RSA-2048 despite the key being a small size. You can use pip to install wheel, which can be used to generate/verify/sign keys."

**Comment by trishankatdatadog** [comment]
Not happening anytime soon, unfortunately.
