### ISSUE TITLE
TUF spec does not require a field called "compression_algorithms" but the client expects it

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#431]
My company is writing a TUF server are using this client to test against it. The spec does not name a field "compression_algorithms" in the root metadata, but the client fails if it is missing.

Can you either update the client to match the spec and mark the field as optional in the docs, or can you update the docs to make the field mandatory?

**Comment by JustinCappos** [comment]
Thanks, we'll take care of this.

**Comment by vladimir-v-diaz** [comment]
Thanks for bring this to our attention.  We'll update the specification to
include this field.

**Comment by vladimir-v-diaz** [comment]
The specification now includes the `compression_algorithms` attribute:
https://github.com/theupdateframework/tuf/blob/d28324fc6ba5aa4b763f66ce890816baac07684a/docs/tuf-spec.txt#L533-L551
