### ISSUE TITLE
TUF spec does not require a field called "delegations" in the target metadata but the client expects it

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#432]
Quoting from https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt#L699

Traceback:
```
  File "/home/heartsucker/code/misc/uptane/venv/lib/python3.5/site-packages/tuf/client/updater.py", line 277, in _load_pinned_metadata
    tuf.formats.PINNING_FILE_SCHEMA.check_match(pinned_metadata)
  File "/home/heartsucker/code/misc/uptane/venv/lib/python3.5/site-packages/tuf/schema.py", line 756, in check_match
    raise tuf.FormatError(message)
tuf.FormatError: Missing key 'delegations' in 'object'
```

**Comment by vladimir-v-diaz** [comment]
Can you share the branch which you are testing?  You are correct, the specification expects the "delegations" field to be optional.

**Comment by heartsucker** [comment]
The `venv` says I'm using 0.10.0.

**Comment by vladimir-v-diaz** [comment]
Judging by the function that is causing the error (_load_pinned_metadata) and the [relevant lines of code in awwad/tuf](https://github.com/awwad/tuf/blob/36dbb7b8a800dab407fe9ab961155ef0a6d9f7c9/tuf/client/updater.py#L281-L298), this appears to be a different kind of metadata (i.e., pinned.json and not targets metadata).
