### ISSUE TITLE
Update failed from HOST/metadata/root.json - pyca-cryptography missing

### ISSUE THREAD

**Issue by AStrunk** [theupdateframework/tuf#450]
Hi,
I am having trouble getting TUF to work on my Windows 10 machine x64 with Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 15:51:26) [MSC v.1900 32 bit (Intel)] on win32 installed.
I have installed TUF manually (git -> pip install .). My code works on my Linux machine, but not on my windows, I get the following error:

`[2017-05-31 13:23:23,771 UTC] [tuf.client.updater] [ERROR] [_get_metadata_file:1121@updater.py]
Update failed from http://server/metadata/root.json.
Traceback (most recent call last):
  File "c:\a\programming\tuf\tuf\client\updater.py", line 1117, in _get_metadata_file
    self._verify_uncompressed_metadata_file(file_object, metadata_role)
  File "c:\a\programming\tuf\tuf\client\updater.py", line 1009, in _verify_uncompressed_metadata_file
    valid = tuf.sig.verify(metadata_signable, metadata_role, self.repository_name)
  File "c:\a\programming\tuf\tuf\sig.py", line 288, in verify
    status = get_signature_status(signable, role, repository_name, threshold, keyids)
  File "c:\a\programming\tuf\tuf\sig.py", line 171, in get_signature_status
    valid_sig = securesystemslib.keys.verify_signature(key, signature, signed)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\securesystemslib\keys.py", line 1012, in verify_signature
    raise securesystemslib.exceptions.UnsupportedLibraryError('Metadata'
securesystemslib.exceptions.UnsupportedLibraryError: Metadata downloaded from the remote repository listed an RSA signature.  "pyca-cryptography" was set (in conf.py) to generate RSA signatures, but the "cryptography" library is not installed.  
$ pip install cryptography, or pip install securesystemslib[tools], or you can try switching your configuration (securesystemslib/settings.py) to use PyCrypto if that is available instead.
[2017-05-31 13:23:23,776 UTC] [tuf.client.updater] [ERROR] [_get_metadata_file:1133@updater.py]
Failed to update 'root.json' from all mirrors: {'http://server/metadata/root.json': UnsupportedLibraryError('Metadata downloaded from the remote repository listed an RSA signature.  "pyca-cryptography" was set (in conf.py) to generate RSA signatures, but the "cryptography" library is not installed.  \n$ pip install cryptography, or pip install securesystemslib[tools], or you can try switching your configuration (securesystemslib/settings.py) to use PyCrypto if that is available instead.',)}`

The problem is that cryptography and pycrypto are both installed. Do anyone of you know what could be missing here?

**Comment by vladimir-v-diaz** [comment]
Can you please verify that the cryptography library can indeed be imported on the Windows machine?
Try the following import statement:

```Python
from cryptography.hazmat.primitives.asymmetric import rsa
```

**Comment by AStrunk** [comment]
Yep. Is is imported.
`Type "help", "copyright", "credits" or "license" for more information.
>>> from cryptography.hazmat.primitives.asymmetric import rsa
>>> rsa
<module 'cryptography.hazmat.primitives.asymmetric.rsa' from 'C:\\a\\py3-env\\lib\\site-packages\\cryptography\\hazmat\\primitives\\asymmetric\\rsa.py'>`

I have now tried installing a clean virtual machine with windows 10, installed python 3.3, because this is the version both pyCrypto and cryptography officially should work on, but still get the same error.

**Comment by AStrunk** [comment]
OKay, so I "downgraded" to the "real" version 0.10.0 from pip install tuf, instead of doing a git clone.
I had to rewrite some of the code, since some af the functions used, was not named the same. But, now I get another error.

`Traceback (most recent call last):
  File "C:\a\client_tuf.py", line 41, in <module>
    updater.refresh()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 666, in refresh
    self._update_metadata('root', DEFAULT_ROOT_FILEINFO)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 1330, in _update_metadata
    compression, compressed_fileinfo)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 1043, in _unsafely_get_metadata_file
    download_safely=False)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 1231, in _get_file
    raise tuf.NoWorkingMirrorError(file_mirror_errors)
tuf.NoWorkingMirrorError: <exception str() failed>`


My first thought after looking through the updater.py is that, could it be something with the compression algorithm used? The default is gz which isn't standard on a Windows machine or am a looking in the wrong direction?

**Comment by AStrunk** [comment]
Ahh, had a look at the tuf.log, seems like it is still the same error:

`
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 1214, in _get_file
    verify_file_function(file_object)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 1030, in unsafely_verify_uncompressed_metadata_file
    metadata_role)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\client\updater.py", line 957, in _verify_uncompressed_metadata_file
    valid = tuf.sig.verify(metadata_signable, metadata_role)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\sig.py", line 218, in verify
    status = get_signature_status(signable, role)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\sig.py", line 132, in get_signature_status
    valid_sig = tuf.keys.verify_signature(key, signature, signed)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\tuf\keys.py", line 856, in verify_signature
    raise tuf.UnsupportedLibraryError(message)
tuf.UnsupportedLibraryError: Metadata downloaded from the remote repository specified an RSA signature.  Verifying RSA signatures requires pyca/cryptography.
$ pip install cryptography, or pip install tuf[tools].
[2017-06-01 11:32:00,386 UTC] [tuf.client.updater] [ERROR] [_get_file:1230@updater.py]
Failed to update root.json from all mirrors: {'http://server/metadata/root.json': UnsupportedLibraryError('Metadata downloaded from the remote repository specified an RSA signature.  Verifying RSA signatures requires pyca/cryptography.\n$ pip install cryptography, or pip install tuf[tools].',)}
`

**Comment by vladimir-v-diaz** [comment]
The error message strikes me as odd.  If you are indeed using the latest version of TUF and `securesystemslib`, the error message should not mention `pip install tuf[tools]`.  The latest version of securesystems should instead refer to `securesystemslib[tools]`  Could the version of TUF installed on your system not be the one available on Git?

Here are the relevant lines of code for your particular error message:
https://github.com/secure-systems-lab/securesystemslib/blob/b535fc26c5a71e22311f9557907244744f908fe8/securesystemslib/keys.py#L1010-L1019

**Comment by AStrunk** [comment]
Well, I tried with both the version from git (think that's the development branch) and the one from pip. Both versions say version 0.10.0, but are different. For example configuration is called tuf.conf in one and tuf.settings in the other.

**Comment by AStrunk** [comment]
I got it working with the pip install tuf method and using ED25519 instead of RSA. Looks like RSA was giving me issues.

**Comment by vladimir-v-diaz** [comment]
Sorry to hear!

What happens if you set the cryptography library to PyCrypto and try to use RSA signatures?  I will test things once I have access to a Windows machine.
