### ISSUE TITLE
Clarification needed on terminating delegations

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#453]
From the spec, the only place the word "terminating" is mentioned is here 

> 4.5.2.2. If the current delegation is a terminating delegation, then jump to step 5.
> 
> 4.5.2.3. Otherwise, if the current delegation is a non-terminating delegation, continue processing the next delegation, if any. Stop the search, and jump to step 5 as soon as a delegation returns a result.

How is a delegation marked as a terminating or not?

**Comment by vladimir-v-diaz** [comment]
Terminating delegations are added to the specification in pull request #433.  I might go ahead and merge it, excluding parts of the pull request that raised objections.

**Comment by vladimir-v-diaz** [comment]
Pull request #433 was merged [here](https://github.com/theupdateframework/tuf/commit/8ddc62c43ff05fee53776e54985071bf83a00c89).

Please have a look at the [new text](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L750-L802) and let us know if terminating delegations and prioritized delegations are adequately covered in the specification.

Here is how the reference implementation processes terminating delegations and prioritized delegations.
