### ISSUE TITLE
Inconsistent wording for the trusted Root file in spec's detailed workflow and unneeded subsection

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#458]
We should try to use a single, consistent word for the currently trusted Root file.

In particular,
[1.3 & 1.4](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L977-L985) refer to "current root metadata file"
[3.2](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1035-L1036) refers to the same file as the "previous root metadata file"

[4.2](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1076-L1078) and [4.4](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L1084-L1085) refer to the same file as the "latest root metadata file"

**Comment by awwad** [comment]
One option we discussed is to write at the end of 1.3 something like "Version N+1 is now the trusted root metadata file." and then use "trusted root file" in all cases.

Alternatively, we could update them all to "current root metadata file". This is somewhat less clear on careful reading, but perhaps clearer to someone skimming.

(As for 0 and 0.1: 0.1 is unnecessary for TUF's security and possibly confusing. 1.3(2) performs the same check. See comments [starting here](https://github.com/theupdateframework/taps/pull/46#discussion_r120980198).)

**Comment by jhdalek55** [comment]
Ok...let me try this again. I think if you are seeking to use one consistent term--which I agree should be done--"trusted root metadata file" is probably the best term to use. Whether its current or not, the important thing to emphasize is it is one that is most accurate.

**Comment by awwad** [comment]
It might be worth making these changes to 1.3 and 1.4: (Changes are bracketed [].)

    1.3. **Check signatures.** Version N+1 of the root metadata file MUST have
    been signed by: (1) a threshold of keys specified in the currently trusted root
    metadata file (version N), and (2) a threshold of keys specified in the
    [new] root metadata file [being validated] (version N+1).

    1.4. **Check for a rollback attack.** The version number of the [currently
    trusted] metadata file [(N)] must be less than or equal to the version number of [the
    new] root metadata file [(N+1)]. Effectively, this means checking that the version
    number signed in the [new] root metadata file is indeed N+1.

There's a bit of hand waving in 1.4 where we sort of imply that the new file doesn't have to have had version N+1 after all, even though we've been calling it N+1. If people think that's confusing, which I can imagine, it could be rewritten with versions identified as X and Y and given example values 6 and 7, say, in parentheticals. NBD, though.

**Comment by trishankkarthik** [comment]
It's not meant to be "hand waving", if that's what you're implying. I agree that we should make it clearer than the next should be N+1, not any other jump.

**Comment by joshuagl** [comment]
This issue has been resolved in the specification
