### ISSUE TITLE
What should happen if a step in the detailed client workflow fails?

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#459]
The [detailed client workflow](https://github.com/theupdateframework/tuf/blob/8ddc62c43ff05fee53776e54985071bf83a00c89/docs/tuf-spec.txt#L950-L1132) presents the steps that the client application must follow to download a target file.  It begins by explaining how the client updates top-level metadata and what it should do if an attack is detected.

What isn't explicitly stated is what the client should do if some of these steps fail.  For example, what should the client do if the supposedly new snapshot file contains invalid signatures?  Should the update process abort?  Should the client continue to trust local, but potentially outdated metadata?

**Comment by JustinCappos** [comment]
In the past we've left the behavior at this point up to the SU system's
implementer.  In some cases, the SU may want to continue and try to update.

To address your specific example, if the snapshot metadata is incorrectly
signed, I would think that almost all clients would prefer to abort and try
again later.  However, an updater used in situations where quickly applying
a potentially outdated update is better (perhaps if connectivity is very
infrequent and tends to corrupt files), then using cached metadata may be a
better choice.

**Comment by lukpueh** [comment]
The [latest version of the specification](https://github.com/theupdateframework/specification/blob/0f56aee998db130e6e1c43c5c7141217436b6d33/tuf-spec.md#5-detailed-workflows) explicitly states how a client should abort the update cycle if any of the steps fail. Closing...
