### ISSUE TITLE
Make metadata paths non-mandatory

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#463]
While talking with someone from the Rust community about implementing TUF on their infra, we ran into a potential issue. There is an existing directory layout and we want to drop TUF into it. We don't want tons of metadata "polluting" the domain's root. To avoid this, we want to dump the metadata in to its own dir such that the structure looks like this.

```
/metadata/
    |-- root.json
    |-- 1.root.json
    |-- <etc>
    |-- delegations/
        |-- some_delegation.json
        |-- a_dir/
            |-- some_sub_delegation.json
/targets_a
/targets_b  
```

Making the metadata's placement at the root be mandatory doesn't add any security benefits, and since it's already assumed because of different keys, hashes, data formats that no two TUF implementations can talk to each other, there's no reason to nail this down.

Related, I don't think it's a good idea to place the delegation's metadata **in** the path it delegates to. This comes up in the spec a few times, and it doesn't make sense.

For example:

```
/some_tuf
    |-- root.json
    |-- some_project.json
    |-- some_project/
        |-- some_sub_project/
        |-- some_sub_project.json
```

This means that `some_project` can never have a target called `some_sub_project.json`, which while likely not necessary, it seems like an odd thing to suggest. In fact, the spec should suggest prefixing all delegations with a common path like `delegations/` because this removes the possibility of overwriting top level metadata.

Together, these make CDN caching a pain. It would better to have all metadata under one path because then simple CDN rules could be:

1. Cache everything with long TTL by default
2. Except: do not cache `metadata/[^.]*.json` ever

(Yes, rule 1 would impede disaster recovery from a fast forward attack, but let's ignore that and assume cache invalidation is somewhat possible)

Related: https://github.com/heartsucker/rust-tuf/issues/69

**Comment by JustinCappos** [comment]
Sure, we are trying to address this in TAP 5.  (
https://github.com/theupdateframework/taps/blob/master/tap5.md )  We were
asked to approve TAP 7 before approving TAP 5, but I hope both will be
approved this month.

**Comment by heartsucker** [comment]
Linking to TAP 5 acceptance issue: https://github.com/theupdateframework/taps/issues/34

**Comment by vladimir-v-diaz** [comment]
@heartsucker 

I don't fully understand your request, or at least it is isn't 100% clear to me.

The specification requires that all metadata exist in a flat file directory relative to a base URL or endpoint.  For example, one repo can store all its metadata in `www.example.com/metadata/`, while another can opt to store metadata in `www.example.com/metadata/tuf_metadata`.

Is the issue due to the requirement that all metadata be accessed from one endpoint?
Do you wish to have the option of accessing metadata from subdirectories?

@JustinCappos Do you want to explain why we require metadata to be stored in a flat file directory (no subdirectories)?

**Comment by JustinCappos** [comment]
I do not see a reason to have relative paths in the delegation namespace.
The namespace should appear flat to delegators.  I do not think it matters
how implementers actually store the files, but directories must not be used
to cause the same name to have different meanings from different locations.

**Comment by vladimir-v-diaz** [comment]
@heartsucker 

An example @JustinCappos has used in the past and wishes to avoid:

www.example.com/metadata/root.json
www.example.com/metadata/delegations/root.json

Justin: So that it's clear to all of us, what should happen if a project developer uploads a delegation that already exists?

`www.example.com/metadata/bob.json` has already been uploaded by the `foo` project.  What if the `bar` project wants to upload their `bob.json`?  Should the repo always deny the request?

**Comment by JustinCappos** [comment]
It's expected that the repo has a way to handle namespace allocation /
conflicts.  This is always needed regardless of anything else or an
attacker can overwrite targets metadata.

**Comment by heartsucker** [comment]
> The specification requires that all metadata exist in a flat file directory relative to a base URL or endpoint. 

This is true, but there is no security reason to do that, and as we have discussed in the past, there is not assumed interoperability between different implementations, so this seems like something that wouldn't need to be required.

>  do not see a reason to have relative paths in the delegation namespace. The namespace should appear flat to delegators. I do not think it matters how implementers actually store the files, but directories must not be used to cause the same name to have different meanings from different locations.

Since my original comment, I generally agree that flat is sufficient for delegations, but I also see no reason to forbid nesting.

> I don't understand your request, or at least it is isn't 100% clear to me.

What I want to is stuff all my meta data in one directory, but then refer to it simply by name. For example, the `foo` delegation metadata is stored under `metadata/foo.json`, but in the `snapshot` and `targets` metadata, I can simply say `foo` since there is some parameters that tells a TUF client "always prefix metdata with this string before fetching."

**Comment by JustinCappos** [comment]
>
> What I want to is stuff all my meta data in one directory, but then refer
> to it simply by name. For example, the foo delegation metadata is stored
> under metadata/foo.json, but in the snapshot and targets metadata, I can
> simply say foo since there is some parameters that tells a TUF client
> "always prefix metdata with this string before fetching."
>
This should absolutely be allowed.  We're not trying to prevent this or
change this case.

**Comment by joshuagl** [comment]
I believe this is a specification issue and should be moved to the [theupdateframework/specification](https://github.com/theupdateframework/specification) repository?

**Comment by JustinCappos** [comment]
Yes, it does not belong here. Is this item obsolete or does the problem still exist?  I think all metadata lives in a single directory now.  I thought we changed that behavior a long time ago when we fixed some problems in the way we were storing delegated targets metadata.

**Comment by lukpueh** [comment]
Yes, I think we can close this. The directory structure for metadata is flat in the reference implementation and this are the relevant parts in the spec.

> **3.1.2 Metadata files**
   The filenames and directory structure of repository metadata are strictly
   defined.  The following are the metadata files of top-level roles relative
   to the base URL of metadata available from a given repository mirror.

[(L411-L415)](https://github.com/theupdateframework/specification/blame/ad0f82b6ad7307f618059654248665d2a2a0dd72/tuf-spec.md#L411-L415)

> **3.1.2.1 Metadata files for targets delegation**
   When the targets role delegates trust to other roles, each delegated role
   provides one signed metadata file.  As is the case with the directory
   structure of top-level metadata, the delegated files are relative to the
   base URL of metadata available from a given repository mirror.

 [(L446-L451)](https://github.com/theupdateframework/specification/blame/ad0f82b6ad7307f618059654248665d2a2a0dd72/tuf-spec.md#L446-L451)

> **4.4. File formats: snapshot.json**
   ...
   METAPATH is the file path of the metadata on the repository relative to the
   metadata base URL. For snapshot.json, these are top-level targets metadata
   and delegated targets metadata.

[(L738-L740)](https://github.com/theupdateframework/specification/blame/ad0f82b6ad7307f618059654248665d2a2a0dd72/tuf-spec.md#L738-L740)
