### ISSUE TITLE
Update spec to not include hashes/size in snapshot metadata

### ISSUE THREAD

**Issue by heartsucker** [theupdateframework/tuf#465]
As per the discussion here: https://github.com/heartsucker/rust-tuf/issues/104#issuecomment-313496672

**Comment by vladimir-v-diaz** [comment]
We need to also determine if it is necessary to list the hash and length of Snapshot in Timestamp.
See https://github.com/theupdateframework/tuf/blob/904fa9b8df8ab8c632a210a2b05fd741e366788a/docs/tuf-spec.txt#L909-L913

**Comment by JustinCappos** [comment]
The hash and length make sense to me.  Why wouldn't we have the hash and
length here?

The version of the snapshot file makes less sense, but I don't see a major
problem with it being there.

**Comment by vladimir-v-diaz** [comment]
Fixed in https://github.com/theupdateframework/tuf/pull/466 and implemented in https://github.com/theupdateframework/tuf/pull/469.
