### ISSUE TITLE
Ensure thread-safety

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#49]
Presently, there is no thread-safety for some important things, such as:
- Switching `tuf.conf` global configuration variables between different TUF clients.
- Downloading the same target files with the same TUF client.

**Comment by lukpueh** [comment]
Quick fix: Note in the readme that TUF might behave unexpectedly when concurrently downloading from the same location to the same location.

**Comment by mnm678** [comment]
#972 added an explanation of this limitation to the readme.
