### ISSUE TITLE
Create GOVERNANCE file

### ISSUE THREAD

**Issue by caniszczyk** [theupdateframework/tuf#507]
As part of being in the CNCF, a public/transparent governnace process is required.

How does the project add new maintainers? How do they get removed? How do projects get added/removed?

As for some examples, I recommend keeping it simple like this:
https://github.com/containernetworking/cni/blob/master/GOVERNANCE.md

**Comment by JustinCappos** [comment]
Okay, we've added a MAINTAINERS file.

I read over the best practices here: https://github.com/corei
nfrastructure/best-practices-badge/blob/master/doc/criteria.md but didn't
spot specifically what is needed by the CNCF.  However, I saw that
containerd had a bunch of additional useful information in their
MAINTAINERS file ( https://github.com/containerd/containerd/blob/
master/MAINTAINERS ).  Is this a good example for us to emulate?

Thanks,
Justin

**Comment by caniszczyk** [comment]
@JustinCappos the containerd example is a fine one (I'd ignore BDFL bits), I was just trying to point you to a simpler example

re: CNCF graduation criteria/requirements are here: https://github.com/cncf/toc/blob/master/process/graduation_criteria.adoc

**Comment by vladimir-v-diaz** [comment]
The governance file was merged in https://github.com/theupdateframework/tuf/pull/531.
