### ISSUE TITLE
Go through CII Best Practices Badge Program

### ISSUE THREAD

**Issue by caniszczyk** [theupdateframework/tuf#508]
As part of being part of CNCF, we expect graduated projects to pass the CII Best Practices program: https://bestpractices.coreinfrastructure.org/

When you have time, feel free to fill out and get the badge, most of these are security best practices that you're doing anyway.

**Comment by vladimir-v-diaz** [comment]
The project now passes the CII Best Practices program!
https://bestpractices.coreinfrastructure.org/projects/1351/
