### ISSUE TITLE
Track CNCF Project Maturity Level Requirements

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#521]
**Description of issue or feature request**:

Keep track of CNCF requirements.

- [x] Document that it is being used successfully in production by at least three independent end users which, in the TOC’s judgement, are of adequate quality and scope.

- [x] Have a healthy number of committers. A committer is defined as someone with the commit bit; i.e., someone who can accept contributions to some or all of the project.

- [x] Demonstrate a substantial ongoing flow of commits and merged contributions.

- [ ] Since these metrics can vary significantly depending on the type, scope and size of a project, the TOC has final judgement over the level of activity that is adequate to meet these criteria

- [x] Have committers from at least two organizations.

- [x] Have achieved and maintained a Core Infrastructure Initiative Best Practices Badge.
  - [x] Basic: 100% complete
  - [x] Silver
  - [ ] Gold

- [x] Adopt the CNCF Code of Conduct.

- [x] Explicitly define a project governance and committer process. This preferably is laid out in a GOVERNANCE.md file and references an OWNERS.md file showing the current and emeritus committers.

- [x] Have a public list of project adopters for at least the primary repo (e.g., ADOPTERS.md or logos on the project website).

- [ ] Receive a supermajority vote from the TOC to move to graduation stage.

**Comment by lukpueh** [comment]
[TUF has graduated within the CNCF](https://www.cncf.io/announcement/2019/12/18/cloud-native-computing-foundation-announces-tuf-graduation/). Closing...
