### ISSUE TITLE
A tool to determine whether metadata for a targets role has diverged from its data

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/tuf#55]
While it may not always be the case (for example, PyPI would almost certainly know when metadata for a targets role needs to be created or updated), sometimes (e.g. exception-handling or building automation tools) you need to ascertain whether metadata for a targets role has diverged from its data.

Here is a [prototype of such a tool](https://github.com/dachshund/pypi.updateframework.com/blob/4f3161f4466a59ca9188c0a8af918792f20a7fc0/metadata_matches_data.py).

**Comment by trishankatdatadog** [comment]
No longer needed

**Comment by awwad** [comment]
Should a use case for this emerge, it can be done far more easily after the consolidation of the internal representation of metadata (#846).
