### ISSUE TITLE
Publish GPG fingerprints and public keys used to verify TUF archives

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#556]
**Description of issue or feature request**:

It would be nice to have an official record of the GPG public keys used to verify TUF archives.

**Current behavior**:

Right now, I'm able to find only [one reference](https://github.com/theupdateframework/tuf/search?utf8=%E2%9C%93&q=3E87BB339378BC7B3DD0E5B25DEE9B97B0E2289A&type=) to this key.

**Expected behavior**:

Public keys should be published not only on GPG key servers, but also on other channels, such as the GitHub repository, web site, and Keybase. [Full fingerprint](https://evil32.com/) should also be used in any reference.

**Comment by vladimir-v-diaz** [comment]
The [maintainers doc](https://github.com/theupdateframework/tuf/blob/develop/MAINTAINERS.txt) includes the full GPG fingerprints for each maintainer in the project.  The [roadmap doc](https://github.com/theupdateframework/tuf/blob/develop/ROADMAP.md) indicates the signer for the latest release.

I think the installation instructions in the README explain how release archives can be verified.  They also link to the maintainers and roadmap docs.

**Comment by trishankatdatadog** [comment]
Nice, I missed this! Do you think it would be helpful to point to these in the installation instructions?

**Comment by trishankatdatadog** [comment]
Oops, I missed this, thanks for the pointer!

Think it would be helpful to publish an official copy of these public keys?

**Comment by vladimir-v-diaz** [comment]
Ahh, I should probably also link to the maintainer doc from the README.  Let me fix that.

How do you recommend we publish an official copy of the public keys?  On our lab's website?  Twitter account?

All of the public keys in maintainers.txt should be on GPG servers.

**Comment by trishankatdatadog** [comment]
Certainly I think a copy should be on the GitHub repo as well as the lab web site. Python has [a copy on its web site](https://www.python.org/static/files/pubkeys.txt), for example.

But that doesn't help too much with trust and revocation. I would also recommend looking into Keybase, but that is entirely optional.

**Comment by vladimir-v-diaz** [comment]
We now publish our PGP fingerprints on [GitHub](https://github.com/theupdateframework/tuf/blob/develop/docs/MAINTAINERS.txt) and the [website](https://theupdateframework.github.io/people.html).  All of our PGP keys can also be found on key servers.

I'll add our full public keys to the website soon.
