### ISSUE TITLE
Option to automatically generate key filename using the keyid

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#573]
**Description of issue or feature request**:

Presently, the user is required to manually specify the filename of generated private / public keys. However, in some cases, it may be useful to let the TUF repository / developer tool use the [keyid](https://github.com/theupdateframework/specification/blame/96534fb659b40eb9a642d732c2d83bbda778e4d5/tuf-spec.md#L541-L542) as the default filename (if none is specified).

Why? Because, in this manner, it is easy to find public keys on the repository, or private keys on disk, using their keyids.

**Current behavior**:

The user is required to manually specify the filenames of generated private / public keys. 

**Expected behavior**:

There should be an option to let the TUF repository / developer tool use the keyid as the default filename, if none is specified, and return this automatically generated filename to the user.

(Solving this issue might require solving #571, so that we can generate the keyid off the key in RAM before writing it to disk.)

**Comment by vladimir-v-diaz** [comment]
Please see the pending pull request for this feature request at https://github.com/secure-systems-lab/securesystemslib/pull/86.

For example:
<img width="1179" alt="screen shot 2018-01-11 at 4 44 35 pm" src="https://user-images.githubusercontent.com/3520883/34849469-7bd99972-f6f0-11e7-9f94-b662e2e773e9.png">

Note:  The wrapper functions from the the repository tool will be used by TUF users.

**Comment by vladimir-v-diaz** [comment]
I am requesting a code review from @lukpueh.

**Comment by trishankatdatadog** [comment]
On second thought, it would be good to print the full path of the key, not just the basepath. What do you guys think?

**Comment by lukpueh** [comment]
A read a comment somewhere in this PR's diff, that private key paths should not be written to any logs if not necessary. But as long if it is only the user's terminal I think it is okay and actually helpful.

**Comment by vladimir-v-diaz** [comment]
I agree.  We should just make sure not to print the full path in exception messages.

**Comment by vladimir-v-diaz** [comment]
This issue has been solved via upgrade to `securesystemslib` 0.10.9.
https://github.com/theupdateframework/tuf/pull/605
