### ISSUE TITLE
libeatmydata for running tests and installing dependencies under Travis CI

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#596]
**Description of issue or feature request**:

The integration and unit tests take a while to run under Travis CI.  Likewise, installing some of our dependencies have taken ages to complete in the past, but things have fortunately improved on this front.  @trishankatdatadog has directed me to an interesting project that can potentially address some of these concerns.

libeatmydata, as in lib-eat-my-data.
https://github.com/stewartsmith/libeatmydata

Debian uses it.  I notice some Python projects like Numpy use it, as well.

**Current behavior**:

Installing packages or running tests happen, slowly.

**Expected behavior**:

Dependencies are installed and unit tests run, quickly.

**Comment by vladimir-v-diaz** [comment]
@trishankkarthik 
Thanks for sharing this!  The IO issues with running the integration and unit tests have always bothered me.

**Comment by trishankatdatadog** [comment]
No problem --- hope it helps!

**Comment by MVrachev** [comment]
We have made improvements with the performance of the tests https://github.com/theupdateframework/tuf/pull/1096.

Still, if we want to optimize even more we can consider this.
What do you think @trishankatdatadog @joshuagl @lukpueh ?

**Comment by trishankatdatadog** [comment]
> What do you think @trishankatdatadog @joshuagl @lukpueh ?

As long as our tests can detect failures induced by libeatmydata, this should be a harmless improvement to make. But if our tests run quickly enough now, it's probably not worthwhile, and we can close this, and revisit in the future.

**Comment by lukpueh** [comment]
+1 closing
