### ISSUE TITLE
Basic setup/tutorial is unusable

### ISSUE THREAD

**Issue by douglasmccormickjr** [theupdateframework/tuf#601]
Trying to follow the python code and general tutorial for the "repository" and "updater" isn't leading to good/reliable results.  Let me be more specific:

## Repository Setup
URL: https://github.com/theupdateframework/tuf/blob/develop/tuf/README.md

Why isn't there a "repo.py init" or some general command that deploys the standard repo files for TUF?  Am I to type all those line of python in an active shell and build it by hand?  This really seems odd and particularly frustrating to me.  Further more, the repo setup (at the end when it's going into attack prevention types URL: https://github.com/theupdateframework/tuf/blob/develop/tuf/README.md#blocking-malicious-updates  strays off to a different tangent -- I don't get why it's going down that ally -- the one pager of everything seems way too much for getting the repo up and going.

I was expecting either a file or concise lines of code to get up and going fast.  Also, deployment/examples of running the repo on a server would be great too (it is covered a little bit though)

## Updater.py
URL: https://github.com/theupdateframework/tuf/blob/develop/tuf/client/README.md

I followed all the repository steps (as best as I could) and also did the whole "python -m server" in the repo directory (it should be noted that the server activation is different in 2.7 and 3.6 -- you could mention that).  Now that the repo is reachable on http://127.0.0.1:8001 and I launch the updater.py script (believe it should "fetch" files down from the server) I get some really strange error about some "updater" directory missing plus a "current" and "previous" directory missing (none of which were created on the repo setup...I'm extremely confused on how this TUF thing works.

## PyInstaller
I'd like to use it for my PyInstaller single file applications so there's a secure approach to fetching files online but I'm really confused by this whole thing.  It would be great for TUF to get to certain specifics or considerations for single file apps too (in terms of best practices or approaches that have worked well -- Pyupdater does have a whole tutorial/demo focusing on WxPython apps here https://github.com/wettenhj/pyupdater-wx-demo which is pretty nice).  Even looking online for some python examples/approaches, I'm totally lost.

Any help or guidance would be greatly appreciated.

**Comment by vladimir-v-diaz** [comment]
@douglasmccormickjr 
Thank you for providing feedback and sharing your experience with the tutorial!

> Why isn't there a "repo.py init" or some general command that deploys the standard repo files for TUF? Am I to type all those line of python in an active shell and build it by hand? This really seems odd and particularly frustrating to me.

I do share your concerns.  We are focusing next on adding a quickstart guide + a user-friendly CLI.  For now, I'll try to address any errors that you experience with the current setup.

> I get some really strange error about some "updater" directory missing plus a "current" and "previous" directory missing (none of which were created on the repo setup...I'm extremely confused on how this TUF thing works.

Are you running `basic_client.py` from the "client" directory?  The client directory, along with the required local metadata, can be created with `create_tuf_client_directory()`.  How to setup the client is covered in the [how to perform an update section](https://github.com/theupdateframework/tuf/tree/develop/tuf#how-to-perform-an-update).
