### ISSUE TITLE
Tutorial text for delegation should actually delegate a path

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#631]
The [delegation section of the TUF repository tutorial](https://github.com/theupdateframework/tuf/blob/develop/docs/TUTORIAL.md#delegations) shows two or three example delegation statements, but none of them include a path, meaning that the delegations are moot, which may be confusing to people.

They look like this:
```Python
repository.targets.delegate("unclaimed", [public_unclaimed_key], [])
```

but should probably instead look like this:
```Python
repository.targets.delegate("unclaimed", [public_unclaimed_key], ['/some_path/abc*])
```

It's understandable to want to keep the example simpler and avoid explaining paths and patterns, but I think it's probably important to include an example that has an effect.

**Comment by vladimir-v-diaz** [comment]
Dammit, we previously did use a glob pattern in the example (see https://github.com/theupdateframework/tuf/commit/6e4a69162f2864976ba5e5e09ad735daf2c59a81), but it wasn't retained when I reordered the arguments to delegate().  I'll go ahead and fix this and make sure the new CLI documentation uses an example with a glob pattern.
