### ISSUE TITLE
Bug in writing consistent snapshots?

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#650]
**Description of issue or feature request**:

I've run into this twice, and I'm fairly certain there's a bug in the current implementation of the TUF repository tool, but I could be wrong.

In any case, I have a setup with one delegated targets role that signs new targets. Let's call it the `targets/alice` role.

I made 2 snapshots where I updated targets in `targets/alice`. So, now I have `2.(timestamp|snapshot|alice).json` and `3.(timestamp|snapshot|alice).json`.

Then, let's say I forget to update any targets in `targets/alice`, but made another snapshot anyway. Now, TUF generated only `4.(timestamp|snapshot).json`.

Then, let's say I do updated targets in `targets/alice`. TUF still generates only `5.(timestamp|snapshot).json`, which both point to` 3.alice.json`.

**Current behavior**:

What the repository tool is doing now is that it is _overwriting_ `3.alice.json` instead of writing a new `(4|5).alice.json`. This is a problem, because the TUF updater gets fooled and thinks there's nothing _new_ to download if it previously downloaded `3.alice.json`.

**Expected behavior**:

The repository tool _should_ always generate a new, incremented version of a metadata file for any updated role.

**Comment by vladimir-v-diaz** [comment]
I wasn't able to reproduce the issue (see attached file), although it does use a simpler but similar setup as the one summarized in the issue.
[update.txt](https://github.com/theupdateframework/tuf/files/1826739/update.txt)

**Comment by vladimir-v-diaz** [comment]
The consistent metadata written to disk after running `python update.py`:

```Bash
$ tree repository/metadata.staged/
repository/metadata.staged/
├── 1.root.json
├── 1.snapshot.json
├── 1.targets.json
├── 1.timestamp.json
├── 1.wheels-signer.json
├── 2.snapshot.json
├── 2.timestamp.json
├── 2.wheels-signer.json
├── 3.snapshot.json
├── 3.timestamp.json
├── root.json
├── snapshot.json
├── targets.json
├── timestamp.json
└── wheels-signer.json

0 directories, 15 files
```

**Comment by trishankatdatadog** [comment]
I don't think those are the right conditions, actually, but I am seeing it once more in a separate environment. I'll try to reproduce once more when I find the time.

**Comment by vladimir-v-diaz** [comment]
This issue is fixed in https://github.com/theupdateframework/tuf/pull/667.
