### ISSUE TITLE
Add continuous integration solution for Windows

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#670]
**Description of issue or feature request**:

Travis is used as the sole continuous integration solution. However, it only runs the tests in unix-like systems.  

**Current behavior**:

The unit tests are only run by Travis on unix-like systems.

**Expected behavior**:

A continuous integration solution for Windows should also be supported.

**Comment by trishankatdatadog** [comment]
Good idea! In the industry, we use https://www.appveyor.com/
