### ISSUE TITLE
Increasing values used to detect slow retrieval attacks

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#728]
**Description of issue or feature request**:

The default values used in TUF (e.g., socket timeout, number of bytes received per second) may be too unforgiving in production environments.

**Current behavior**:

These default values cause TUF to be intolerant of "natural" latency issues, especially when SSL is turned on.

**Expected behavior**:

Consider doubling these values, so that TUF is more toleration of deviations that fall within the norm.

**Comment by vladimir-v-diaz** [comment]
I'm fine with tweaking these default values for production environments, or the common case.  Let's try to figure out the ideal values for them.

Here are the settings we should tweak:
https://github.com/theupdateframework/tuf/blob/625de9c4013b95fac56c730cf9cad5bd5bd07c36/tuf/settings.py#L81-L93

**Comment by trishankatdatadog** [comment]
I'm not sure what they should be either. We could do some measurements. Until then, we could try doubling them, at least.
