### ISSUE TITLE
Document how spec and code changes are released

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#746]
**Description of issue or feature request**:

The [ROADMAP](https://github.com/theupdateframework/tuf/blob/develop/docs/ROADMAP.md) doesn't adequately cover or explain how changes are introduced to the spec and codebase.  For instance, how are backwards-incompatible changes released?  Are there stable, alpha, beta releases?  Which branch contains the latest changes and design?

**Comment by vladimir-v-diaz** [comment]
The release schedule can also be captured via [TAP](https://github.com/theupdateframework/taps#tuf-augmentation-proposals-taps)s, similar to Python's information PEPs (e.g., PEP [569](https://www.python.org/dev/peps/pep-0569/) and [373](https://www.python.org/dev/peps/pep-0373/)).

Informational TAPs on releases was requested by @trishankatdatadog.  Thanks!

**Comment by trishankatdatadog** [comment]
Thank you, sir!

**Comment by joshuagl** [comment]
There's a WIP TAP to address how spec changes are released https://github.com/theupdateframework/taps/pull/107

**Comment by MVrachev** [comment]
If this TAP theupdateframework/taps#107 is merged do we need that issue, yet?

**Comment by mnm678** [comment]
I believe that TAP and the [release process](https://github.com/theupdateframework/tuf/blob/develop/docs/RELEASE.md) both document this issue. I will close this issue, feel free to reopen if this is still a concern.
