### ISSUE TITLE
Mock test CLI and complete docstrings

### ISSUE THREAD

**Issue by vladimir-v-diaz** [theupdateframework/tuf#763]
**Description of issue or feature request**:

The CLI and supporting were reviewed in #741, but `repo.py` still needs mock tests and docstrings.

**Comment by michizhou** [comment]
Hi @vladimir-v-diaz, if it's alright with you, I would be glad to take a look at resolving this issue! Just let me know what types of mock tests and docstrings you would like me to include or edit in `repo.py`.

**Comment by alyptik** [comment]
@michizhou That's very alright! Unfortunately, I'm not completely sure on what type of docstrings/mock tests were meant, so I'll let @vladimir-v-diaz clarify what should be edited/included.

**Comment by awwad** [comment]
I'd hazard that what is meant here is two things:
- While there is documentation for the CLI ([general doc](https://github.com/theupdateframework/tuf/blob/develop/docs/CLI.md); [more CLI examples](https://github.com/theupdateframework/tuf/blob/develop/docs/CLI_EXAMPLES.md)), there is some need for more explanation of the arguments and/or more examples of use in in the docstrings of the CLI scripts.
   - [ ] [repo.py](https://github.com/theupdateframework/tuf/blob/develop/tuf/scripts/repo.py) has examples in the docstring, but the command-line arguments themselves are not listed and individually explained. That should probably be done, or if parse_arguments() seems conveniently readable enough (probably not), the docstring of the module should point to it.
   - [ ] The same goes for [client.py](https://github.com/theupdateframework/tuf/blob/develop/tuf/scripts/client.py), but it could probably use a few more examples in addition to the explanation of command line arguments.
 - Vlad may have been suggesting [doctest](https://docs.python.org/2/library/doctest.html), which would need to be used differently for these CLI modules than it is for other modules. I don't know if this would be helpful for the CLI modules. Currently, doctest is used for repository_lib.py, repository_tool.py, developer_tool.py, and formats.py. It is seemingly not linked to our continuous integration testing, though. I think that's a project for another issue, so I'd focus on the first bullet here instead.

**Comment by awwad** [comment]
He could also have meant the addition of testing via something like the usual unittest scheme that TUF uses (see all the tests in `tests/`) to test the CLI scripts. This is a larger and more important task.

Either would be helpful. Please let me know which you'd rather work on and I'll give you more instruction as necessary.

**Comment by michizhou** [comment]
@awwad I would like to get started with the documentation part of it. Once that is taken care of, I would be glad to help add additional testing for the CLI scripts and possibly look into the use of doctest. Let me know if that works for you. Thanks!

**Comment by michizhou** [comment]
@awwad Just wanted to follow up with you on working with the documentation of the CLI script docstrings. I would appreciate it if you could give me more instruction and guidance on getting started.

**Comment by awwad** [comment]
Sorry, I didn't realize you were waiting for more.  The [two checklist items in the first bullet of the comment above](https://github.com/theupdateframework/tuf/issues/763#issuecomment-428683061) were what I had in mind for the documentation bit.

It might be hard for me to tell what introduction is necessary, so questions would be very helpful. 😃

If you need to get a feel for what's going on, I'd [try out the command line tool, following these tutorials](https://github.com/theupdateframework/tuf/blob/develop/docs/CLI.md) until you feel confident.

**Comment by michizhou** [comment]
@awwad I have just pushed a new PR that addresses the concerns over documentation in the CLI test scripts (i.e. `repo.py` and `client.py`) with new command-line descriptions and examples added. Let me know if you need me to make any additional changes. Thanks!

**Comment by michizhou** [comment]
@awwad Just wanted to follow up with you again since I did create a PR that addresses this issue over a week ago. I would appreciate it if you could look it over and review it. Thanks!

**Comment by awwad** [comment]
#796 merged.  Thanks, @michizhou!

repo.py still needs docstrings for a number of its functions before I can close this.

**Comment by michizhou** [comment]
@awwad Not a problem! Just wanted to let you know that I recently opened a new PR that should help definitely resolve this issue, as I have provided docstrings for all functions that don't have one already.

**Comment by michizhou** [comment]
@awwad Just wanted to follow up with you on the fact that I have resolved the missing docstrings issue for repo.py in a separate PR (#805) that I opened up nearly two weeks ago. I would appreciate it if you could review my changes and let me know if any more modifications need to be made. Thanks!

**Comment by michizhou** [comment]
@awwad I apologize for bothering you again, but it has been over three weeks since I last made a new PR (#805) that should resolve the issue of missing docstrings in repo.py. I would really appreciate it if you could review at your earliest convenience so that we can close this issue. Please let me know if you have any concerns or if you think any more changes to the docstrings need to be made. Thanks.

**Comment by lukpueh** [comment]
Closing due to uncertain future of TUF cli. Re-visit with #811.
