### ISSUE TITLE
Spam in Travis-CI for some Python versions only

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#777]
In only some builds on Python 3.4 builds on Travis-CI, you can see long spans of spam like the following in the Travis-CI logs.

Here's one example where the [Python 3.4 build](https://travis-ci.org/theupdateframework/tuf/jobs/398001484)) has some bizarre spam, but not the [2.7](https://travis-ci.org/theupdateframework/tuf/jobs/398001483) and [3.6](https://travis-ci.org/theupdateframework/tuf/jobs/398001486) builds:
- ...`ampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTimestampLargeTime`...
- ...`Adding a verification key that has already been used. Adding a verification key that has already been used. Adding a verification key that has already been used. Adding a verification key that has already been used. Adding a verification key that has already been used. Adding a verification key that has already been used. Adding a verification key that has already been used. `...
- ...`We do not have a console handler. We do not have a console handler. We do not have a console handler. We do not have a console handler. We do not have a console handler.`...

In another set of builds, the [2.7](https://travis-ci.org/theupdateframework/tuf/jobs/397934445) is quiet, [3.4](https://travis-ci.org/theupdateframework/tuf/jobs/397934446) is fairly quiet, and [3.6](https://travis-ci.org/theupdateframework/tuf/jobs/397934448) is quite noisy with such fascinating output strings as ...`badbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbad`...

One would expect the behavior to be similar.... I can't think of how a few odd Travis-CI instances might explain all this.

**Comment by MVrachev** [comment]
I don't think I have seen such cases of spam from the time I started contributing to TUF.

This issue is somehow related to https://github.com/theupdateframework/tuf/issues/838, but I feel we don't need it anymore.
Have you seen spams like this @joshuagl @lukpueh ?

**Comment by jku** [comment]
No, not like this. I suggest closing.

From the logs I can make a wild guess and say that running test_log.py somehow broke the logging at the time (as the "console handler" spam is always first) and any tests after that got their default output (warning and above) printed.

**Comment by joshuagl** [comment]
Thanks both, closing
