### ISSUE TITLE
TUF deployment roadmap for PyPI

### ISSUE THREAD

**Issue by LucidOne** [theupdateframework/tuf#816]
Is there a timeline for when TUF might be deployed to PyPI or what issues are blocking deployment?

Thanks!

**Comment by JustinCappos** [comment]
We've been prodding them to try to get this going.  We're very interested
in helping to get this into Warehouse, but our understanding is that they
still aren't ready.

Datadog did do a pip integration of TUF that they are using with their
customers.  So the client side should be easy to do...

**Comment by brainwane** [comment]
Please see https://github.com/pypa/warehouse/issues/5247#issuecomment-525920011 !

**Comment by brainwane** [comment]
More progress: https://github.com/python/peps/pull/1177

**Comment by trishankatdatadog** [comment]
[Tracked separately by PyPI](https://pyfound.blogspot.com/2019/09/pypi-security-q4-2019-request-for.html), so closing this issue
