### ISSUE TITLE
Related tools

### ISSUE THREAD

**Issue by HavardLine** [theupdateframework/tuf#835]
**Description of issue or feature request**:
Hi there. TUF is cool. We are now able to move files securely to our clients.

Next step is out of scope for TUF. File comparison, file update and generating useful logs.

Do you know any existing tools that do this?

**Comment by JustinCappos** [comment]
I'm not really sure how to answer this.  There are a ton of tools in all areas that relate to this.  It's a bit off topic for TUF though.  We're focused on maximizing update security, which necessitates us not adding a bunch of unrelated functionality...
