### ISSUE TITLE
Creating a TAP to forbid leading path separators in targets?

### ISSUE THREAD

**Issue by erickt** [theupdateframework/tuf#837]
Good morning,

I noticed that in #679 @vladimir-v-diaz banned the python tuf library from having leading path separators in paths. However, the current 1.0 draft has example targets.json with [leading slashes](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#the-update-framework-specification). Should the spec be updated, possibly with a TAP to forbid this?

I ran into this because I'm trying to upgrade [go-tuf](https://github.com/flynn/go-tuf) from the 0.9 spec to 1.0 draft, and one of the interoperability tests between go-tuf and python tuf is failing because due to go-tuf prefixing it's paths with a `'/'`. I can adjust for this, but if #679 fixes ambiguity in path delegation, then it would be great to get this into the spec before it is finalized.

**Comment by trishankatdatadog** [comment]
Hi @erickt, I'm afraid I was responsible for asking @vladimir-v-diaz to make that change. It makes it much easier for clients to construct the right paths on disk without being surprised (otherwise libraries like Python do the "wrong" thing, unsurprisingly).

Would be great if you could send a quick PR to clarify this, thanks 🙏

**Comment by JustinCappos** [comment]
FYI: I don't see this as a TAP-level change.  I agree with Trishank that a
PR, appropriately reviewed and discussed will be fine.

**Comment by erickt** [comment]
@trishankatdatadog that sounds reasonable. Where would be the right place in the project to clarify this?

**Comment by trishankatdatadog** [comment]
@erickt I would say in Section 4.5 of the spec, where we discuss `TARGETPATH`. Thanks in advance :)

**Comment by trishankatdatadog** [comment]
@erickt I would say in Section 4.5 of the spec, where we discuss `TARGETPATH`. Thanks in advance :)

**Comment by erickt** [comment]
FYI my [patch](https://github.com/theupdateframework/specification/pull/39) to recommend against leading path separators, so I think this can be closed.
