### ISSUE TITLE
Make the repo script usable from other scripts

### ISSUE THREAD

**Issue by cminyard** [theupdateframework/tuf#873]
The repo.py script is a useful tool by itself, and it has useful functions in it for other scripts.

My proposal is to split up argument parsing so that another script can provide all the functions from repo.py and add its own on top of that.  repo.py has some useful function by itself.

I would also like to make the code that writes updated targets it's own function.  If you have a script that modifies target files, it's going to have to duplicate that code, and duplication is bad.

I'm working on a project that takes manifest files and a set of files they point to and automatically populates a repository in a way that some client code can automatically tell what is new, updated, and deleted and call a program with that information.  That's at https://github.com/MontaVista-OpenSourceTechnology/meta-tuf and it currently requires the attached patches to TUF.  Basically to make TUF a little easier to use.
[0001-Split-up-parse_arguments.patch.txt](https://github.com/theupdateframework/tuf/files/3214554/0001-Split-up-parse_arguments.patch.txt)
[0002-Split-out-write_updated_targets-from-add_targets.patch.txt](https://github.com/theupdateframework/tuf/files/3214556/0002-Split-out-write_updated_targets-from-add_targets.patch.txt)

**Comment by lukpueh** [comment]
Closing due to uncertain future of TUF cli. Re-visit with #811.
