### ISSUE TITLE
Rename and rework repo.py and client.py

### ISSUE THREAD

**Issue by cminyard** [theupdateframework/tuf#874]
repo.py and especially client.py are really terrible names for those scripts.  However, repo.py is a useful tool by itself and for use by other scripts.

I propose to move repo.py and client.py down a level into the tuf directory and create tuf-repo and tuf-client scripts that call into them.  I can generate a patch, if you like.

**Comment by joshuagl** [comment]
This issue should probably be closed in favour of #881, it's effectively a duplicate (though this issue was chronologically duplicated by #881, the latter has a lot more discussion).

**Comment by lukpueh** [comment]
Closing in favor of #881
