### ISSUE TITLE
Changing signature schemes without rotating the keys

### ISSUE THREAD

**Issue by danixeee** [theupdateframework/tuf#920]
**Description of issue or feature request**:

[This PR](https://github.com/secure-systems-lab/securesystemslib/pull/173) added support for using `pkcs#1v1.5` signature scheme for RSA keys.

_Key-id_ represents a hash of _keytype_, _key_value_ and `scheme` values ([def _get_keyid](https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/keys.py#L602)) which now allows us to use one same key with multiple signature schemes.

If we just want to change signature schemes we need to do a key rotation (although private keys didn't change), which can be tricky in some cases.

For e.g. (rotating a root keys - changing schemes)

We have 3 root keys with scheme _rsassa-pss-sha256_:
- 123
- 456
- 789

Now we need to add same keys with different scheme _rsa-pkcs1v15-sha256_:
- 321
- 654
- 987

NOTE: Key id _123_ and _321_ both have the same private key!

If root threshold is set to 2 (num of keys - 1), someone will be able to use just one key and to sign metadata file twice (with different schemes) with that key. Increasing a threshold to 3 solves this problem, but should we add a feature to change signature schemes without rotating the keys?

Does `scheme` value still make sense to be used when calculating `key-id` hash?

**Comment by lukpueh** [comment]
The current implementation:
1. does not require or check canonical keyids (although it still uses them via `securesystemslib` key creation and import interfaces)
2. checks signature thresholds based on unique keyids only (see @jku's 48b58d9be984ee578e58c64ab1921daecff00f0c)

This means keyids no longer depend on the used signature scheme and metadata owners are responsible to choose the keyid<->key mappings such that thresholds can not be subverted.

---
For context, while both items above go against the [current spec](https://theupdateframework.github.io/specification/v1.0.28/index.html#root-keyid)... 

(wrt 1)
> Clients MUST calculate each KEYID to verify this [the canonical form] is correct for the associated key 

(wrt 2)
> Clients MUST ensure that for any KEYID represented in this key list and in other files, only one unique key has that KEYID

... this strategy does align with the general direction of the spec (see the [recently](https://github.com/theupdateframework/taps/pull/151) accepted [TAP 12](https://github.com/theupdateframework/taps/blob/master/tap12.md)).
