### ISSUE TITLE
Duplicate definitions of schemas

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#927]
**Description of issue or feature request**:

There are duplicate definitions of schemas. For example, `ROLE_SCHEMA` is defined twice ([here](https://github.com/theupdateframework/tuf/blob/b4e565f055286e8af1ae2546022705ddb0672608/tuf/formats.py#L123-L134) and [here](https://github.com/theupdateframework/tuf/blob/b4e565f055286e8af1ae2546022705ddb0672608/tuf/formats.py#L219-L228)) in [formats.py](https://github.com/theupdateframework/tuf/blob/b4e565f055286e8af1ae2546022705ddb0672608/tuf/formats.py).

**Current behavior**:

Duplicated definitions.

**Expected behavior**:

Non-duplicated definitions.

**Comment by lukpueh** [comment]
Thanks, @trishankatdatadog!

Independently of solving the duplicate definition, I would appreciate your take on this schema-related issue https://github.com/secure-systems-lab/securesystemslib/issues/183.

**Comment by adityasaky** [comment]
There was an effort to reduce confusions between roles and delegations in the reference implementation and clean up the schemas and roledb. Is #846 relevant here?

Edit: https://github.com/theupdateframework/tuf/pull/846/files#diff-342188447c824198a41061eb376e1898L103-L110

**Comment by lukpueh** [comment]
Thanks, @adityasaky! Looks like we (probably I) should soon start to finish the work, @awwad started in #660/#846.

**Comment by trishankatdatadog** [comment]
@lukpueh @adityasaky I agree, this needs a larger fix, but we should be able to quickly dedup this right now in TUF at least...
