### ISSUE TITLE
AppVeyor builds for Python 2.7 keep timing out

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#940]
**Description of issue or feature request**:
Since recently AppVeyor Python 2.7 builds always fail by exceeding the maximum build execution time, i.e. 60 minutes. While time outs have happened in the past, they occurred more randomly and and also on different Python versions.

NOTE: 
Our TUF AppVeyor GitHub apps integration was recently changed from [OAuth to GitHub App](https://www.appveyor.com/blog/2018/10/02/github-apps-integration/). In the course of doing so the corresponding organizational account was changed too. While this is unlikely to be related to the issue new builds need to be accessed under https://ci.appveyor.com/project/theupdateframework/tuf. Past builds can still be found under https://ci.appveyor.com/project/securesystemslab/tuf-j90sw/history.

**Current behavior**:
AppVeyor builds on Python 2.7 always fail due to timeouts

**Expected behavior**:
AppVeyor should normally not time out on Python 2.7

**Comment by lukpueh** [comment]
Might be worth to check out [windows support on Travis](https://docs.travis-ci.com/user/reference/windows/), to see if it's mature enough yet to replace AppVeyor.

**Comment by trishankatdatadog** [comment]
Or maybe use Azure?

**Comment by lukpueh** [comment]
While [troubleshooting failing tests on AppVeyor for the in-toto repo](https://github.com/in-toto/in-toto/pull/345#issuecomment-578853435) a few days ago, I read up on Travis CI Windows/Python support. It still [seems quite beta](https://travis-ci.community/t/python-support-on-windows/).  I too very briefly looked into alternatives, and concluded that we should at least try to solve this issue on AppVeyor before we setup anything new.

@joshuagl has created a new ticket for this issue at https://github.com/theupdateframework/tuf/issues/965, which provides more details. Closing here...
