### ISSUE TITLE
SemVer for spec_version breaks pre-SemVer clients

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#949]
**Description of issue or feature request**:

0.12 has [adopted](https://github.com/theupdateframework/tuf/blob/3d96fb1933c65c2f4abf6b014f768953b0307cc6/tuf/formats.py#L79-L86) [SemVer for spec_version](https://github.com/theupdateframework/specification/pull/51). However, this strict checking now prevents 0.12 from [loading](https://github.com/theupdateframework/tuf/blob/3d96fb1933c65c2f4abf6b014f768953b0307cc6/tuf/repository_tool.py#L2909) repositories written with 0.11 and less.

**Current behavior**:

0.12 fails to load repositories written with 0.11 and less.

**Expected behavior**:

0.12 should be able to _load_ repositories written with 0.11 (and, optionally, less), so that repositories can migrate from 0.11 to 0.12.

**Comment by lukpueh** [comment]
Addressed in #950
