### ISSUE TITLE
No need to tolerate repositories written with pre-SemVer spec_version

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#951]
**Description of issue or feature request**:

Undo #949 and #950 

**Current behavior**:

**Expected behavior**:

**Comment by jku** [comment]
We tried this but at least the sigstore (go-tuf) metadata I tested still isn't using semver.

It would be nice if we could avoid this but legacy spec_version seems harmless -- and accepting it allows us to interop test other aspects of metadata -- so we're currently accepting "X.Y" in deserialization.
